### ISSUE TITLE
弃用较老的 TLS 版本

### ISSUE THREAD

**Issue by haimaren** [alibaba/higress#1027]
![image](https://github.com/alibaba/higress/assets/26118792/f16bc7f4-49d1-4601-a892-6ab245d6adb5)
如图阿里云网关支持配置这块,,,higress不清楚如何实现,我目前使用的higress版本为1.4.0

**Comment by johnlanni** [comment]
目前开源版本还没提供tls版本设置的注解

**Comment by yingjianjian** [comment]
Before the open source version provides the relevant capability, envoyfilter can be used to implement this capability first
Refer to the following configuration:
`apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: dis-tls
  namespace: higress-system
spec:
  configPatches:
  - applyTo: FILTER_CHAIN
    match:
      context: GATEWAY
      listener:
        name: 0.0.0.0_443
    patch:
      operation: MERGE
      value:
        transport_socket:
          name: envoy.transport_sockets.tls
          typed_config:
            '@type': type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
            common_tls_context:
              tls_params:
                tls_maximum_protocol_version: TLSv1_3
                tls_minimum_protocol_version: TLSv1_2
  workloadSelector:
    labels:
      app: higress-gateway`
