### ISSUE TITLE
higress 域名配置如何支持非80、443端口

### ISSUE THREAD

**Issue by gavin347951** [alibaba/higress#1039]
## Why do you need it?
 Is your feature request related to a problem? Please describe in details

## How could it be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by johnlanni** [comment]
https://github.com/alibaba/higress/blob/12cc44b3247fbbaae1fdd7ecfb3f5e04492a3dfb/helm/core/values.yaml#L435C3-L436

@gavin347951 这两个配置
