### ISSUE TITLE
【GLCC】Higress Console 支持通过表单配置 Wasm 插件

### ISSUE THREAD

**Issue by CH3CHO** [alibaba/higress#1043]
GitLink编程夏令营（GLCC），是在CCF中国计算机学会指导下，由CCF开源发展委员会（CCF ODC）举办的面向全国高校学生的暑期编程活动。活动将覆盖近千所高校，并联合各大开源基金会、开源企业、开源社区、开源专家，旨在鼓励青年学生通过参加真实的开源软件开发，提升自身技术能力，为开源社区输送优秀人才。为青年学生提供开放友好的交流平台，希望进一步推动国内开源社区的繁荣发展。

Higress将会参加本次的[“GitLink编程夏令营（GLCC）”](https://www.gitlink.org.cn/glcc)

# 背景

Higress 支持通过 Wasm 插件来对网关的功能进行功展，并且内置了多种 Wasm 插件。用户可以通过 Higress Console 的页面直接进行插件的配置操作。但目前，Higress COnsole 的插件配置页面仅支持使用 YAML 进行配置，用户使用体验较差。而按照 Higress 的插件规范，每一个插件均会以 [OpenAPI Specification](https://swagger.io/docs/specification/data-models/data-types/) 提供其配置的数据模型。Higress Console 可以基于这一数据模型自动生成表单，向用户提供更友好便捷的插件配置体验。

# 目标

Higress Console 可以基于插件的配置数据模型自动生成配置表单，并与后端服务进行配置交互。

# 难度

中等

# 导师

董艺荃（@CH3CHO）
ch3cho@qq.com

# 产出要求

1. 可以基于插件的配置数据模型自动生成配置表单
2. 支持 OpenAPI Specification 中的所有数据类型
3. 支持将表单输入转换与 YAML 数据之间进行相互转换，以便与后端服务进行交互
4. 支持基于数据模型中的限制条件生成数据有效性校验规则（可选）

# 能力要求

1. 熟练掌握 TypeScript/JavaScript 语言
2. 熟悉基于 React 框架进行前端应用开发的优先考虑
3. 了解 OpenAPI Specification 的优先考虑

**Comment by guluguluhhhh** [comment]
im wujinhua，i want to have a try

**Comment by CH3CHO** [comment]
fixed by https://github.com/higress-group/higress-console/pull/322
