### ISSUE TITLE
是否有计划支持service-weight注解

### ISSUE THREAD

**Issue by phantooom** [alibaba/higress#1044]
在阿里维护的ingress版本中支持过 nginx.ingress.kubernetes.io/service-weight 这个注解用来做权重分流策略。
https://help.aliyun.com/zh/ack/ack-managed-and-ack-dedicated/user-guide/use-the-nginx-ingress-controller-for-canary-releases-and-blue-green-deployments#section-vrs-t38-h3b

相比原生的nginx-ingress 使用nginx.ingress.kubernetes.io/canary-weight 我觉得在API层面更容易理解，也比较符合直觉。

请问是否有计划在higress中支持这个注解。

**Comment by johnlanni** [comment]
https://github.com/alibaba/higress/blob/main/samples/nacos-discovery/multi-destination.yaml

可以参考下这个 destination 注解

**Comment by phantooom** [comment]
请教下这个注解支持转发到 headless 类型的service吗，我看例子中是mcp。

**Comment by johnlanni** [comment]
@phantooom 支持的，直接写FQDN就行
