### ISSUE TITLE
jwt-auth claims to headers failed

### ISSUE THREAD

**Issue by pepesi** [alibaba/higress#1074]
我正在测试基于特定jwt claims的限流，发现没有生效，redis中甚至没有相关key，日志看到获取头失败。

jwt-auth中配置了claims_to_headers 将 identity 添加到header，在cluster-key-rate-limit的插件中获取不到头。

我注意到 https://github.com/alibaba/higress/blob/e389313aa3c6fd4b602bf24f82307b3f828d98ff/plugins/wasm-go/extensions/jwt-auth/handler/verify.go#L101 这儿的这个变量似乎没有被填充。

这儿是否需要 token.UnsafeClaimsWithoutVerification(&rawClaims) ？

**Comment by johnlanni** [comment]
你用的是go版本的jwt-auth插件？目前插件市场里的jwt-auth是cpp版本的

**Comment by pepesi** [comment]
我编译安装的，go版本的
