### ISSUE TITLE
moonshot contextCache  潜在的问题

### ISSUE THREAD

**Issue by pepesi** [alibaba/higress#1082]
moonshot 在获取基于文件的缓存内容时，可能出现潜在的token不匹配的情况，当提供了多个不属于同一个owner的api_key的时候，可能出现跨用户访问资源的情况。
需要在单次请求的时候使用相同的api_key。从业务角度出发，这可能也是一个让人疑惑的点，当配置了多个key的情况下，配置中是一个文件id的情况，在多次请求下，也会出现随机命中缓存的情况，这可能在配置了多api_key的情况下禁用内容缓存？

**Comment by johnlanni** [comment]
嗯 可以在文档中备注一下 使用context cache时，确保配置的api key没有跨账号
