### ISSUE TITLE
There is no docs about config plugins for the ingress way.

### ISSUE THREAD

**Issue by jaggerwang** [alibaba/higress#1093]
### Ⅰ. Issue Description

I known it can config policy(plugin) for some route in web console, but web console not support complex usage, I need to use ingress. In the docs, there is only plugin paramters description, but how can I add plugin in ingress?

### Ⅵ. Environment:

- Higress version:  v1.4.1
- OS : macOS
- Others: Kubernetes v1.28

**Comment by CH3CHO** [comment]
Checkout this: https://higress.io/zh-cn/docs/plugins/intro

**Comment by jaggerwang** [comment]
Thanks！
