### ISSUE TITLE
按照Wasm 插件镜像规范构建出的镜像不可用

### ISSUE THREAD

**Issue by Beatrueman** [alibaba/higress#1100]
我按照[Wasm 插件镜像规范](https://higress.io/zh-cn/docs/user/wasm-image-spec)构建了`basic-auth`和`request-block`，但是构建出的镜像不可用，`gateway`日志报错提示相同

```
[Envoy (Epoch 0)] [2024-07-07 02:49:32.889][25][error][wasm] Function: _start failed: Uncaught RuntimeError: unreachable
Proxy-Wasm plugin in-VM backtrace:
  0:  0x15a5 - runtime._panic
  1:  0x14318 - github.com/higress-group/nottinygc.init#1
  2:  0x13fe9 - runtime.initAll
  3:  0x13f5a - runtime.run
  4:  0x13f4a - _start
[Envoy (Epoch 0)] [2024-07-07 02:49:32.889][25][error][wasm] Wasm VM failed Failed to initialize Wasm code
[Envoy (Epoch 0)] [2024-07-07 02:49:32.890][25][warning][config] gRPC config for type.googleapis.com/envoy.config.core.v3.TypedExtensionConfig rejected: Unable to create Wasm HTTP filter higress.basic
```

我的镜像构建流程

```
GO_VERSION="1.19"
TINYGO_VERSION="0.25.0"
ORAS_VERSION="1.0.0"
PLUGIN_NAME="request-block"
BUILDER_IMAGE="higress-registry.cn-hangzhou.cr.aliyuncs.com/plugins/wasm-go-builder:go${GO_VERSION}-tinygo${TINYGO_VERSION}-oras${ORAS_VERSION}"
docker run -v ${PWD}:/workspace -e PLUGIN_NAME=${PLUGIN_NAME} -it --rm ${BUILDER_IMAGE} /bin/bash

cd /workspace/plugins/wasm-go/extensions/${PLUGIN_NAME}
export GOPROXY=https://goproxy.cn 
go mod tidy
tinygo build -o ./plugin.wasm -scheduler=none -target=wasi ./main.go

tar czvf plugin.tar.gz plugin.wasm
oras push reg.myharbor.com/library/request-block:1.0.0 ./plugin.tar.gz:application/vnd.oci.image.layer.v1.tar+gzip 
```

_Originally posted by @Beatrueman in https://github.com/alibaba/higress/discussions/1099_

**Comment by hanxiantao** [comment]
> 我按照[Wasm 插件镜像规范](https://higress.io/zh-cn/docs/user/wasm-image-spec)构建了`basic-auth`和`request-block`，但是构建出的镜像不可用，`gateway`日志报错提示相同
> 
> ```
> [Envoy (Epoch 0)] [2024-07-07 02:49:32.889][25][error][wasm] Function: _start failed: Uncaught RuntimeError: unreachable
> Proxy-Wasm plugin in-VM backtrace:
>   0:  0x15a5 - runtime._panic
>   1:  0x14318 - github.com/higress-group/nottinygc.init#1
>   2:  0x13fe9 - runtime.initAll
>   3:  0x13f5a - runtime.run
>   4:  0x13f4a - _start
> [Envoy (Epoch 0)] [2024-07-07 02:49:32.889][25][error][wasm] Wasm VM failed Failed to initialize Wasm code
> [Envoy (Epoch 0)] [2024-07-07 02:49:32.890][25][warning][config] gRPC config for type.googleapis.com/envoy.config.core.v3.TypedExtensionConfig rejected: Unable to create Wasm HTTP filter higress.basic
> ```
> 
> 我的镜像构建流程
> 
> ```
> GO_VERSION="1.19"
> TINYGO_VERSION="0.25.0"
> ORAS_VERSION="1.0.0"
> PLUGIN_NAME="request-block"
> BUILDER_IMAGE="higress-registry.cn-hangzhou.cr.aliyuncs.com/plugins/wasm-go-builder:go${GO_VERSION}-tinygo${TINYGO_VERSION}-oras${ORAS_VERSION}"
> docker run -v ${PWD}:/workspace -e PLUGIN_NAME=${PLUGIN_NAME} -it --rm ${BUILDER_IMAGE} /bin/bash
> 
> cd /workspace/plugins/wasm-go/extensions/${PLUGIN_NAME}
> export GOPROXY=https://goproxy.cn 
> go mod tidy
> tinygo build -o ./plugin.wasm -scheduler=none -target=wasi ./main.go
> 
> tar czvf plugin.tar.gz plugin.wasm
> oras push reg.myharbor.com/library/request-block:1.0.0 ./plugin.tar.gz:application/vnd.oci.image.layer.v1.tar+gzip 
> ```
> 
> _Originally posted by @Beatrueman in #1099_

`tinygo build -o /plugin.wasm -scheduler=none -gc=custom -tags='custommalloc nottinygc_finalizer' -target=wasi ./`构建wasm的命令改成这个试下呢

**Comment by CH3CHO** [comment]
看一下这个文档：https://higress.io/zh-cn/docs/user/wasm-go#3-%E7%BC%96%E8%AF%91%E7%94%9F%E6%88%90-wasm-%E6%96%87%E4%BB%B6

**Comment by Beatrueman** [comment]
解决了，我认为是这篇文档https://higress.io/zh-cn/docs/user/wasm-image-spec中的部分未更新导致的。
第一个是TinyGO的版本，这里的TinyGO版本应该是0.28.1。
![image](https://github.com/alibaba/higress/assets/121592304/1c298415-45d3-4de0-a549-56992c5d4b2f)
第二个是TinyGO编译命令，为什么这篇文档里要用这条编译命令呢？
![image](https://github.com/alibaba/higress/assets/121592304/058cdf28-6d6e-4c37-86ca-4d6bf067aa82)

**Comment by CH3CHO** [comment]
> 解决了，我认为是这篇文档[https://higress.io/zh-cn/docs/user/wasm-image-spec中的部分未更新导致的。](https://higress.io/zh-cn/docs/user/wasm-image-spec%E4%B8%AD%E7%9A%84%E9%83%A8%E5%88%86%E6%9C%AA%E6%9B%B4%E6%96%B0%E5%AF%BC%E8%87%B4%E7%9A%84%E3%80%82) 第一个是TinyGO的版本，这里的TinyGO版本应该是0.28.1。 ![image](https://private-user-images.githubusercontent.com/121592304/346418420-1c298415-45d3-4de0-a549-56992c5d4b2f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0MDk0MzYsIm5iZiI6MTcyMDQwOTEzNiwicGF0aCI6Ii8xMjE1OTIzMDQvMzQ2NDE4NDIwLTFjMjk4NDE1LTQ1ZDMtNGRlMC1hNTQ5LTU2OTkyYzVkNGIyZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOFQwMzI1MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MmZiNGE0Zjk5ZDBiOTQwMGU2ZGYxZmYwOTU3NjFmNzM1YWZmZTAwOWY2Mjc5OWZhZjFlZGZlMmFlYjZiN2EyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BvIhOdPqU4lNA7ALQh2dQyNtF5og9SmPv_aJt9LVgZM) 第二个是TinyGO编译命令，为什么这篇文档里要用这条编译命令呢？ ![image](https://private-user-images.githubusercontent.com/121592304/346418516-058cdf28-6d6e-4c37-86ca-4d6bf067aa82.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0MDk0MzYsIm5iZiI6MTcyMDQwOTEzNiwicGF0aCI6Ii8xMjE1OTIzMDQvMzQ2NDE4NTE2LTA1OGNkZjI4LTZkNmUtNGMzNy04NmNhLTRkNmJmMDY3YWE4Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOFQwMzI1MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NDYwOGI1YTU4Y2JjZmFlMDlmMjdiNDE2ZGQ0NTFhZWY0OWNmODkwNmViZDllMWVjNmM1OTI3MGNlMzM0NmM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AWWBOzIT-I0vl4c9i8X2dMcy8U2bbu1Pq-sCLVnTJC0)

这个文档我来更新一下。

**Comment by CH3CHO** [comment]
> > 解决了，我认为是这篇文档[https://higress.io/zh-cn/docs/user/wasm-image-spec中的部分未更新导致的。](https://higress.io/zh-cn/docs/user/wasm-image-spec%E4%B8%AD%E7%9A%84%E9%83%A8%E5%88%86%E6%9C%AA%E6%9B%B4%E6%96%B0%E5%AF%BC%E8%87%B4%E7%9A%84%E3%80%82)
> 这个文档我来更新一下。

@Beatrueman 文档已更新。

**Comment by Beatrueman** [comment]
> > > 解决了，我认为是这篇文档[https://higress.io/zh-cn/docs/user/wasm-image-spec中的部分未更新导致的。](https://higress.io/zh-cn/docs/user/wasm-image-spec%E4%B8%AD%E7%9A%84%E9%83%A8%E5%88%86%E6%9C%AA%E6%9B%B4%E6%96%B0%E5%AF%BC%E8%87%B4%E7%9A%84%E3%80%82)
> > > 这个文档我来更新一下。
> 
> @Beatrueman已更新。

TinyGO的版本是不是也得更新一下😊
![Screenshot_2024-07-08-13-59-41-142_com android chrome](https://github.com/alibaba/higress/assets/121592304/fe6837f4-3687-4dc2-8aba-f2d58455d7ca)

**Comment by CH3CHO** [comment]
> TinyGO的版本是不是也得更新一下😊

已提交 PR：https://github.com/alibaba/higress/issues/1100
