### ISSUE TITLE
m1电脑 使用kind 本地环境测试 -> 创建 Ingress 资源并测试

### ISSUE THREAD

**Issue by heimanba** [alibaba/higress#111]
- [ ] I have searched the [issues](https://github.com/alibaba/higress/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
1. 本地使用kind测试
![image](https://user-images.githubusercontent.com/5129967/207000852-42e0b064-ac98-45c3-ae35-b12cabdcb057.png)

2. 应用启动报错
![image](https://user-images.githubusercontent.com/5129967/207001258-5e258d77-0fdc-4d5c-bbc6-42588c82d58a.png)

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### III. Environment:

- Higress version:  
- OS : macos m1
- Others:

**Comment by xcbeyond** [comment]
@heimanba 这是由于higress官方暂未提供 higress-registry.cn-hangzhou.cr.aliyuncs.com/higress/http-echo 的arm镜像导致的，可以其他类似的arm镜像代替、验证/体验。
