### ISSUE TITLE
higress接入Skywaking没有数据

### ISSUE THREAD

**Issue by liuflylove666** [alibaba/higress#1122]
higress-config
  
tracing:
    enable: true
    sampling: 100
    timeout: 500
    skywalking:
      service: oap-svc.skywalking.svc.cluster.local
      port: 11800

![WechatIMG66](https://github.com/user-attachments/assets/bd2cc0fc-097b-4d0e-8073-f53f997d79bd)

**Comment by johnlanni** [comment]
https://higress.io/zh-cn/docs/user/configurations

![image](https://github.com/user-attachments/assets/94d5b73a-cc75-426e-b289-97dc56605a78)

应该是目前这里配置的 service 没有自动推给数据面，可以先全局打开这个参数配置开关
