### ISSUE TITLE
Higress是否支持跨K8s集群路由

### ISSUE THREAD

**Issue by GEN-LD** [alibaba/higress#1125]
## Why do you need it?
  由于业务需要，我需要将Higress部署在一个K8s集群，路由到其他K8s集群的service，了解到Higress支持跨K8s集群路由的能力，但我没找到相关文档~
  想确认下higress开源版本是否已支持跨集群路由能力，如果没有，后续是否有支持跨集群路由的计划？

**Comment by johnlanni** [comment]
https://github.com/alibaba/higress/issues/848

有issue在跟进
