### ISSUE TITLE
如何设置 higress 不处理 original-host 这个 header 

### ISSUE THREAD

**Issue by whitebear009** [alibaba/higress#1133]
我们有个业务 nginx 配置了转发规则到 higress 域名（原本是 ingress-nginx的时候没问题），转发时设置了 
`proxy_set_header original-host $host;`
这个自定义 header 头。

转发到 higress 的时候发现被改写了，原本期望是业务 nginx 的域名，变成了 higress 的域名。
我在 higress-gateway 的日志中打印出了这个header 头，发现所有的请求都有这个 header。后来发现是貌似是 higress 用的 envoy 的版本刚好会覆盖这个 header？ 参考 https://github.com/alibaba/higress/blob/c0f2cafdc8754a74a84c62b6e091cec532ef0b3b/envoy/1.20/patches/envoy/20231008-fallback-origin-cluster.patch#L38

这个 original-host 的 header 貌似不是标准 HTTP Header，好像刚好跟我们业务上重名了。

怎么设置 envoy 不改写这个 header 呢 ? （对 envoy 不太熟）

另外我看 enovy 1.20（https://github.com/envoyproxy/envoy/blob/v1.20.0/source/common/http/headers.h） 对应的代码里貌似也没这个变量，不知道是不是我版本选的不对

————
update：看到了这个 header 也是之前另一个 patch 增加的，https://github.com/alibaba/higress/blob/c0f2cafdc8754a74a84c62b6e091cec532ef0b3b/envoy/1.20/patches/envoy/20221027-init.patch#L8146

**Comment by CH3CHO** [comment]
请 @johnlanni 看一下

**Comment by johnlanni** [comment]
下个版本我们调整下这个header，改成 x-envoy-original-host

**Comment by whitebear009** [comment]
好的，谢谢

**Comment by whitebear009** [comment]
@johnlanni 您好，请问这个有预期发布时间吗，因为最近发现我们这边有挺多业务依赖这个字段。如果有其他能暂时绕过的方法最好了～

**Comment by johnlanni** [comment]
@whitebear009 好的 这两天更新一个小版本

**Comment by whitebear009** [comment]
非常感谢

**Comment by johnlanni** [comment]
已经发布 1.4.2
