### ISSUE TITLE
Higress-nacos对接，目标服务没有动态生成

### ISSUE THREAD

**Issue by liuflylove666** [alibaba/higress#1134]
Higress配置完成nacos对接，目标服务选不到nacos目标服务。
查看higress-controller日志无明显报错信息

解决：
重新部署higress-controller pod后有目标服务了

**Comment by CH3CHO** [comment]
用户是先配置了一个没有服务的ns和group。后续修改ns和group配置后，没有直接加载到服务列表。重启controller后服务发现正常工作。

**Comment by CH3CHO** [comment]
我本地没有重现这个问题。你可以再尝试一下看看。

**Comment by CH3CHO** [comment]
已与用户沟通，后续再观察，遇到的话再行处理。
