### ISSUE TITLE
Higress的AI插件GeoIP插件设计

### ISSUE THREAD

**Issue by ranxuxin001** [alibaba/higress#1158]
背景：
    目前随着人工智能时代的到来，基于大模型训练的知识问答系统也应运而生。Higress作为AI代理服务能够接收用户的提问请求，然后根据查询缓存结果判断是否把该请求转发给上游llvm chat api服务获取精确回答。作为AI代理服务的Higress还可以搜集大量用户的地理位置信息，分析用户地理位置与用户提问内容的关联关系，从而能够更精确，本地化的回答用户的提问，提高用户体验感。另一方面，Higress需要具备根据用户地理位置信息，评估风险，紧急时候能够根据用户地理信息屏蔽用户请求，防止恶意攻击的能力。另外，Higress也需要根据用户地理位置，代理用户请求到与用户较近的llvm chat api上游服务器节点（类似CDN的作用），缩短用户请求的网络传输距离，减少请求时间。

GeoIP插件设计：
1. 注册GeoIP插件：
    在ProcessRequestHeadersBy处理请求头阶段注册插件的回调函数onHttpRequestHeader。当请求进入onHttpRequestHeader( ) 函数时，如果用户是直接连接Higress，就取remote_address作为用户IP。如果用户通过代理服务访问Higress，请求里包含请求头X-forwarded-for，就解析XFF头取第一个IP地址作为原始用户IP。（如下图）

2. 录入地理位置信息到GeoIP插件
    进入Maxmind官网https://www.maxmind.com/。   首先创建账户，然后到注册的邮箱里点击连接激活账户。再到下载页面选择精确到城市的数据库下载，如GeoLite2-City-CSV_20240723.zip。解压缩后得到ip网段cidr对应id的信息文件GeoLite2-City-Blocks-IPv4.csv和id 对应城市等地理位置信息的文件GeoLite2-City-Locations-en.csv。可以写个脚本把从这两个文件里提取出cidr 对应地理位置信息的数据，然后把该数据以key，value格式写入GeoIP插件的配置yaml里（提取出的数据如下图）。然后注册GeoIP插件的parseConfig( )函数。用gjson获取yaml配置里的cidr和地理位置信息的映射数据，并且存入radixtree基数树。树节点的key是cidr字符串，data字段是地理位置信息，包括洲，国家，城市，邮编，地区。

![ipgeo](https://github.com/user-attachments/assets/3873bfb8-e852-4b6c-a485-75fd5e6d78f2)

    

3. 查询用户地理位置：
    当GeoIP插件解析出用户IP后，建立一个从32到15的循环，因为数据里的cidr网络位是在32到15范围内的，比如用户的ip是88.111.92.120，对应的地理位置数据里cidr是88.111.92.0/25。然后用golang库函数net.ParseCIDR(“88.111.92.120/32”)计算出用户ip在网络位是32时的cidr。再拿该cidr到radixtree里查找相同key的树节点。如果找到了树节点，就取该节点的data字段得到地理位置信息。如果没有找到树节点，则进入下一个for循环，然后用golang库函数net.ParseCIDR(“88.111.92.120/31”)计算出用户ip在网络位是31时的cidr。依次循环查找，直到找到树节点为止。如果所有网络位的cidr都找不到树节点，就返回空结构体(pseudo代码如下图)。

![pseudo](https://github.com/user-attachments/assets/6fed4c86-aab2-4414-ae8a-33a5f5903995)

4. GeoIP插件与其他插件交互
    由于每个请求里都包含用户ip信息，而一个请求会经过Higress请求生命周期里各个阶段的插件，因此可以让GeoIP插件通过请求上下文context传递ip和地理位置信息给请求经过的其他后续阶段的插件，如ctx.SetContext(GeoIPContextKey, ip和地理位置结构体)。 其他插件通过ctx.GetContext(GeoIPContextKey) 获取ip和地理位置结构体。然后对用户ip，访问内容和地理位置信息做统计分析，或者选择性屏蔽指定地区的用户访问。

**Comment by johnlanni** [comment]
maxmind的国内数据不太准，可以看下这个的评价比较好：https://gitee.com/lionsoul/ip2region

**Comment by johnlanni** [comment]
由于每个请求里都包含用户ip信息，而一个请求会经过Higress请求生命周期里各个阶段的插件，因此可以让GeoIP插件通过请求上下文context传递ip和地理位置信息给请求经过的其他后续阶段的插件，如ctx.SetContext(GeoIPContextKey, ip和地理位置结构体)。 其他插件通过ctx.GetContext(GeoIPContextKey) 获取ip和地理位置结构体。然后对用户ip，访问内容和地理位置信息做统计分析，或者选择性屏蔽指定地区的用户访问。

---

setContext 是没有办法跨插件的。不过可以通过setProperty设置到metadata中，这样其他插件可以通过getProperty获取到。

AI Proxy 可以支持解析，从而支持注入一些包含用户地理位置信息的 system prompt。对于本地生活相关的问答会有帮助。

**Comment by ranxuxin001** [comment]
@johnlanni  感谢提示。我把上面推荐的ip2region ip地理信息库实现到geoip插件里了。查询ip地理位置很准确，速度特别快。然后用了proxywasm.SetProperty([]string{"geoIpData"}, geoIpPro)  把ip地理信息结构体传给后续的插件了。我在阿里ECS上higress里验证了功能。准备提交pr。
