### ISSUE TITLE
新增固定地址返回400错误

### ISSUE THREAD

**Issue by MuJianxuan** [alibaba/higress#1160]
服务来源>>创建服务来源>>新增固定地址服务
点击确定的时候提示验证异常
![image](https://github.com/user-attachments/assets/beba955c-d454-4814-8ae8-210a4ed2f80c)

提交内容不合法
错误详情（错误码：400）
Method: post
RequestURL: http://localhost:8080/v1/service-sources
Headers: {"Authorization":"\"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTkzOTY4NjgsImF1ZCI6IntcImlkXCI6MSxcInVzZXJuYW1lXCI6XCJhZG1pblwiLFwicm9sZVwiOjIsXCJjcmVhdGVEdFwiOlwiMjAyNC0wNi0yNSAxODowODozOVwiLFwidXBkYXRlRHRcIjpcIjIwMjQtMDYtMjUgMTg6MDg6MzlcIn0ifQ.7R4puDgIAkMsliIx8o4aCxcbHNAZuc9YIlN7IQD-bJs\"","Accept":"application/json, text/plain, */*","Content-Type":"application/json"}
Data: {"success":false,"message":"com.alibaba.higress.sdk.exception.ValidationException: serviceSource body is not valid.","data":null}

大佬，这是为何，难道是 有页面缓存导致的吗

**Comment by MuJianxuan** [comment]
清楚缓存后也是这样的结果；
忘记说系统信息了：
使用官网最新的脚本部署的，
os：windows
平台：docker
部署脚本：
curl -fsSL https://higress.io/standalone/get-higress.sh | bash -s -- -a -c nacos://172.16.138.66:8848 --nacos-username=nacos --nacos-password=nacos
nacos的服务应该是正常的，不过这个我得试一下，还没试

**Comment by CH3CHO** [comment]
服务地址填 111。你是认真的吗？

**Comment by CH3CHO** [comment]
> > 服务地址填 111。你是认真的吗？
> 
> 不要在意这些小东西，问题是 为毛我保存不进去

因为服务端有格式校验啊，你这里填的不是IP和端口，所以校验不通过。

**Comment by MuJianxuan** [comment]
> > > 服务地址填 111。你是认真的吗？
> > 
> > 
> > 不要在意这些小东西，问题是 为毛我保存不进去
> 
> 因为服务端有格式校验啊，你这里填的不是IP和端口，所以校验不通过。

这么简单，难受，谢谢

**Comment by MuJianxuan** [comment]
这个已解决
