### ISSUE TITLE
Higress-gateway  forward the request to the ip address which is not exist in cluster.

### ISSUE THREAD

**Issue by haifzhu** [alibaba/higress#1165]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via [ASRC](https://security.alibaba.com/)(Alibaba Security Response Center) where the issue will be triaged appropriately.**

- [ X ] I have searched the [issues](https://github.com/alibaba/higress/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
One higress-gateway instance(pod) forward the request to the ip address which is not exist in cluster。

~~~
Spec:
  Http:
    Match:
      Uri:
        Prefix:  /api/biz-eco/isv/zjzwdata
    Route:
      Destination:
        Host:  web-isv-zjzwdata
        Port:
          Number:  8080
~~~

![image](https://github.com/user-attachments/assets/934f2be2-fa1d-44b3-8a7b-9d0234efb712)

![image](https://github.com/user-attachments/assets/1b40c329-25d6-42b0-ae25-3f79c0cad9b6)

the request match the right route rule, but the upstream_host is not exact the right one(10.11.16.173:8080) but is (10.11.27.185:8080)

Another higress-gateway instance is forward right ip address.

![image](https://github.com/user-attachments/assets/fe3d2ba3-9aa8-42c0-b53e-19a441cfb13c)

### Ⅱ. Describe what happened

higress-gateway has warning logs dump.

  If there is an exception, please attach the exception trace:

```
[Envoy (Epoch 0)] [2024-07-31 03:24:42.398][41][warning][client] [C42155999] Connection is closed by peer during connecting.
[Envoy (Epoch 0)] [2024-07-31 03:24:42.421][41][warning][client] [C42156000] Connection is closed by peer during connecting.
[Envoy (Epoch 0)] [2024-07-31 03:24:42.468][41][warning][client] [C42156001] Connection is closed by peer during connecting.
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- Higress version:  1.4.1
- OS :  CentOS Linux 7 (Core)   5.4.8-1.el7.elrepo.x86_64
- Others:

**Comment by johnlanni** [comment]
https://github.com/alibaba/higress/issues/1129#issuecomment-2257273945

应该是这个问题导致的，近期会backport一下

**Comment by haifzhu** [comment]
好，目前已经在环境配置了PILOT_XDS_SEND_TIMEOUT变量

**Comment by johnlanni** [comment]
已经发布了 2.0.0-rc.1  修复了此问题
