### ISSUE TITLE
higress-gateway would be OOMkilled when modify virtualservice many times.

### ISSUE THREAD

**Issue by haifzhu** [alibaba/higress#1167]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via [ASRC](https://security.alibaba.com/)(Alibaba Security Response Center) where the issue will be triaged appropriately.**

- [ X] I have searched the [issues](https://github.com/alibaba/higress/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

From the issue appearance, higress-gateway would be OOMkilled when modify virtualservice many times.
The memory resource limit is set to 14G, it uses 8G normally。
When we change the virtualservices resource many times, the memory of higress-gateway would be exhausted。

![image](https://github.com/user-attachments/assets/90afb16c-35cf-410e-80f1-1998cb1885bb)

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. change virtualservice many times 
2. the memory used of higress-gateway will be increased.

### Ⅵ. Environment:

- Higress version:  1.4.1
- OS : Centos 7
- Others:

**Comment by haifzhu** [comment]
生产环境这个问题比较明显，变更了两次，内存使用持续升高： 
![image](https://github.com/user-attachments/assets/11425187-8aea-457e-b503-6937191b14c1)
怀疑跟流量有关系。

**Comment by johnlanni** [comment]
https://github.com/envoyproxy/envoy/commit/646802449498fb8db78563eca6004825718a4825

是这个问题，你们的业务有 websocket，websocket 连接未断开，对应的 http 请求就不会结束，就会把 rds config 的 shared_ptr  维持住，频繁变更 rds，内存就会一直增加。

新版本在收到 upstream header 之后就会释放这个 shared_ptr， 可以解决这个问题。 higress 2.0版本会升级一下。

**Comment by johnlanni** [comment]
已经发布 2.0.0-rc.1 修复了此问题

**Comment by ishells** [comment]
想请问下2.0.0版本已经解决了内存泄露的问题吗？

我尝试新部署2.0.0版本的higress，然后一次性添加了300多个ingress对象（ingress->svc->deployment，deployment的replicas都为0），查看higress-gateway和higress-controller的监控，内存占用都提升了很多没有降下来（此时后端deployment replicas都还为0，暂未对外）

> higress-gateway 监控
![image](https://github.com/user-attachments/assets/bd60a58b-882d-496e-9280-e8b560ed2f62)

> higress-controller 监控
![image](https://github.com/user-attachments/assets/0a71aa37-482c-451a-88de-4a78469f6377)

> 新添加ingress对象后端的deployment
![image](https://github.com/user-attachments/assets/bca5da31-3958-44fa-a162-663a09cb9546)

**Comment by snailAlice** [comment]
> [envoyproxy/envoy@6468024](https://github.com/envoyproxy/envoy/commit/646802449498fb8db78563eca6004825718a4825)
> 
> 是这个问题，你们的业务有 websocket，websocket 连接未断开，对应的 http 请求就不会结束，就会把 rds config 的 shared_ptr 维持住，频繁变更 rds，内存就会一直增加。
> 
> 新版本在收到 upstream header 之后就会释放这个 shared_ptr， 可以解决这个问题。 higress 2.0版本会升级一下。

你好，我们使用了升级后的2.0.7的版本，但是这个现象是仍然存在的，变更的时候会导致内存上升，但是目前过段时间内存会被释放，如果是频繁的变更还是会导致网关内存的OOM情况的出现，请问这个有解决的方式嘛。

![Image](https://github.com/user-attachments/assets/b62117e1-60c6-478c-94d3-d16d5ea7de77)

![Image](https://github.com/user-attachments/assets/8ce87082-54a6-4977-af44-ba69be97cd67)
