### ISSUE TITLE
重写后导致请求路径结尾携带斜杠（/）

### ISSUE THREAD

**Issue by DaZhang98** [alibaba/higress#1242]
- [x] I have searched the [issues](https://github.com/alibaba/higress/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
使用重写插件时，即使路径部分不以斜杠结尾，结尾也会拼接斜杠（/）。

### Ⅱ. Describe what happened

界面配置如下：
![7e4d53eb28d97795ef5fa32bd698a95e_cr](https://github.com/user-attachments/assets/59faf430-3019-4599-94b9-cc13b2d5d136)

重写前URL为：https://1.2.3.4/prod-api/common/downloadattach?fileName=aaaa.doc
重写后URL为：http://backend/common/downloadattach/?fileName=aaaa.doc

### Ⅲ. Describe what you expected to happen
重写后的URL应该是：http://backend/common/downloadattach?fileName=aaaa.doc

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. 如上图配置Higress重写策略
2. 请求一个不以斜杠结尾的路径

### Ⅵ. Environment:

- Higress version:  v1.4.1
- OS : CentOS 7
- Others:

**Comment by CH3CHO** [comment]
这个我研究一下。

**Comment by johnlanni** [comment]
2.0.0-rc.1  已经发布，可以升级验证下，因为目前还是 rc 版本，helm install 时注意加上 --devel 参数
