### ISSUE TITLE
认证鉴权插件如何在特定路由生效

### ISSUE THREAD

**Issue by ytwang0320** [alibaba/higress#125]
请问higress的auth wasm插件如何在特定路由生效。

我尝试在本地用envoy加载(https://github.com/alibaba/higress/tree/main/plugins/wasm-cpp/extensions/basic_auth)的wasm插件, 认证可以对特定域名生效，但是无法对特定路由生效。
请问如何配置？

**Comment by ytwang0320** [comment]
配置：
static_resources:
  listeners:
  - name: main
    address:
      socket_address: { address: 0.0.0.0, port_value: 80 }
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          access_log:
          - name: envoy.access_loggers.file
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
              path: "/tmp/log"
              log_format: 
                text_format: "%ROUTE_NAME% %START_TIME% %RESPONSE_CODE% %REQ(USER-AGENT)%\"\n"
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match: { prefix: "/" }
                route: { cluster: web_service }
            - name: local_service2
              domains: ["test.qiyi.domain"]
              routes:
              - match: { prefix: "/" }
                route: { cluster: web_service }
          http_filters:
            - name: envoy.filters.http.wasm
              typed_config:
               '@type': type.googleapis.com/udpa.type.v1.TypedStruct
               type_url: type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm
               value:
                 config:
                   configuration:
                     "@type": "type.googleapis.com/google.protobuf.StringValue"
                     value: |
                      {   
                        "_rules_": [
                           {   "_match_route_" : ["local_service2"],
                            "consumers" : [
                              {"credential" : "getuser1:123456", "name" : "consumer1"},
                              {"credential" : "getuser2:123456", "name" : "consumer2"}
                            ]
                           }
                        ]
                      }
                   vm_config:
                     vm_id: basic_auth
                     runtime: "envoy.wasm.runtime.v8"
                     code:
                       local:
                         filename: /usr/local/lib/rider/plugins/basic_auth.wasm
            - name: envoy.filters.http.router

**Comment by johnlanni** [comment]
要用higress发行的envoy才可以，可以记个issue提供一个单独的envoy image

**Comment by ytwang0320** [comment]
getValue({"route_name"}, &route_name);
我这边看是route_name获取不到，这个是higress这边加的吗。

**Comment by johnlanni** [comment]
是的
