### ISSUE TITLE
为什么OnResponseBody方法中可以使用 proxywasm.ReplaceHttpRequestHeaders

### ISSUE THREAD

**Issue by mark8s** [alibaba/higress#1269]
我有个疑问，我在几个Ai插件中，如 [ai-transformer](https://github.com/alibaba/higress/tree/main/plugins/wasm-go/extensions/ai-transformer) 和 [ai-security-guard](https://github.com/alibaba/higress/tree/main/plugins/wasm-go/extensions/ai-security-guard)，都看到这种写法，如下:

在onHttpResponseBody方法中使用`proxywasm.ReplaceHttpResponseHeaders(reconvertHeaders(hdsMap))`出处 ai-security-guard ：
```
func onHttpResponseBody(ctx wrapper.HttpContext, config AISecurityConfig, body []byte, log wrapper.Log) types.Action {
						hdsMap := ctx.GetContext("headers").(map[string][]string)
						delete(hdsMap, "content-length")
						hdsMap[":status"] = []string{"403"}
						**proxywasm.ReplaceHttpResponseHeaders(reconvertHeaders(hdsMap))**
						proxywasm.ReplaceHttpResponseBody(jsonData)
						proxywasm.SetProperty([]string{"risklabel"}, []byte(respResult.Array()[0].Get("Label").String()))
}
```

在onHttpResponseBody方法中`proxywasm.ReplaceHttpResponseHeaders(newHeaders)`出处 ai-transformer：
```
func onHttpResponseBody(ctx wrapper.HttpContext, config AITransformerConfig, body []byte, log wrapper.Log) types.Action {
			newHeaders, newBody, err := extraceHttpFrame(gjson.GetBytes(responseBody, "output.text").String())
			if err == nil {
				**proxywasm.ReplaceHttpResponseHeaders(newHeaders)**
				proxywasm.ReplaceHttpResponseBody(newBody)
			}
			proxywasm.ResumeHttpResponse()
}
```

但是 proxywasm.ReplaceHttpResponseHeaders() ,它难道不是只能用于 OnHttpResponseHeaders 阶段吗？ 写在这里难道没问题吗？

这是它的说明：
```
// ReplaceHttpResponseHeaders is used for replacing HTTP response headers
// with given headers. Only available during
// types.HttpContext.OnHttpResponseHeaders.
func ReplaceHttpResponseHeaders(headers [][2]string) error {
	return setMap(internal.MapTypeHttpResponseHeaders, headers)
}
```

有知道的吗？理论上这样执行并不会生效，上面也并不没有处理异常，如果处理了异常应该会报错才对。

_Originally posted by @mark8s in https://github.com/alibaba/higress/discussions/1268_

**Comment by 2456868764** [comment]
1. 在 onHttpResponseHeaders 阶段返回了 types.HeaderStopIteration 状态，这个状态表示 header 还不能继续交给下一个 filter 来处理，但是可以继续处理 response body 部分，所以在 onHttpResponseBody 阶段可以修改 headers.
2. 需要编译时启用 `EXTRA_TAGS=proxy_wasm_version_0_2_100` 标签来修改 Proxy Wasm ABI

```shell
tinygo build -scheduler=none -target=wasi -gc=custom -tags='custommalloc nottinygc_finalizer proxy_wasm_version_0_2_100' -o ./build/plugin.wasm main.go
```

**Comment by 2456868764** [comment]
> @2456868764 谢谢，请问这是higress做的处理，还是说原生的 tetratelabs/proxy-wasm-go-sdk 也支持？？

开发 Higress Wasm 插件 用的是 Higress 提供 SDK github.com/higress-group/proxy-wasm-go-sdk ，不是 原生的 tetratelabs/proxy-wasm-go-sdk。

**Comment by CH3CHO** [comment]
> @2456868764 谢谢，请问这是higress做的处理，还是说原生的 tetratelabs/proxy-wasm-go-sdk 也支持？？

是 Higress 做的处理。而且这个功能是要修改 Envoy 本体的，只靠 sdk 实现不了这个。
