### ISSUE TITLE
官方考虑支持 k3s一键安装脚本么

### ISSUE THREAD

**Issue by clywm520** [alibaba/higress#1281]
k3s按照官方提供的k8s helm 部署脚本，不能直接访问443。
可以提供k3s一键安装可用的脚本么？

k3s v1.25.16

**Comment by clywm520** [comment]
最好加上 支持http3功能的

**Comment by CH3CHO** [comment]
如果你只是安装了但没有配置路由，Higress是不会监听任何端口的。你需要配一个HTTPS路由来让Higress监听443端口。

**Comment by clywm520** [comment]
@CH3CHO  强烈建议你亲自试一下 k3s v1.25.16  安装 higress,现在的版本，各种坑，各种访问不了.即使配置了路由，也访问不了. 
比如：
1. helm repo add higress.cn https://higress.cn/helm-charts
2. helm upgrade --install higress -n higress-system higress.cn/higress --create-namespace --render-subchart-notes
3.  hgctl dashboard console -l 0.0.0.0
4. 访问 8080配置路由，域名。
5. 根据域名访问 443端口 访问不了。
6. kubectl logs  higress-gateway 报了一个警告，不支持tls1.3。

**Comment by clywm520** [comment]
最好官网提供一下，可用的 k3s安装教程哈。

**Comment by CH3CHO** [comment]
> [Envoy (Epoch 0)] [2024-09-05 05:51:46.628][23][warning][config] gRPC config for type.googleapis.com/envoy.config.listener.v3.Listener rejected: Error adding/updating listener(s) 0.0.0.0_443: Failed to load certificate chain from , only P-256 ECDSA certificates are supported

这就是你用的证书算法Envoy不支持么

**Comment by clywm520** [comment]
ec-384 不支持么？如何解决呢？

**Comment by CH3CHO** [comment]
官方暂时还没有支持。可以关注这个 issue：https://github.com/envoyproxy/envoy/issues/10855

**Comment by clywm520** [comment]
2024-09-05T06:53:28.572930Z     warning envoy quic external/envoy/source/common/quic/active_quic_listener.cc:334       Efficient routing of QUIC packets to the correct worker is not supported or not implemented by Envoy on this platform. QUIC performance may be degraded.       thread=23

  2.0.0-rc.1 也不支持http3

**Comment by johnlanni** [comment]
> 2024-09-05T06:53:28.572930Z warning envoy quic external/envoy/source/common/quic/active_quic_listener.cc:334 Efficient routing of QUIC packets to the correct worker is not supported or not implemented by Envoy on this platform. QUIC performance may be degraded. thread=23
> 
> 2.0.0-rc.1 也不支持http3

支持的，这个报错是当前没有开启基于 BPF 的 H3 路由特性
