### ISSUE TITLE
503 - upstream connect error or disconnect/reset before headers. reset reason: connection termination"

### ISSUE THREAD

**Issue by JunJieLiu51520** [alibaba/higress#1282]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via [ASRC](https://security.alibaba.com/)(Alibaba Security Response Center) where the issue will be triaged appropriately.**

- [ ] I have searched the [issues](https://github.com/alibaba/higress/issues) of this repository and believe that this is not a duplicate.

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- Higress version:  
- OS :
- Others:

**Comment by johnlanni** [comment]
看报错是后端关闭了连接，请提供详细的场景说明，以及对应的访问日志

**Comment by LiujunjieALiling** [comment]
1. 在 20:47:38 和 20:48:13 分别发生了 503 错误
![image (5)](https://github.com/user-attachments/assets/3614b3a3-b668-427d-afcc-f07d07ca1200)

2. tcpdump 抓包发现后端服务触发了 RST
![image (6)](https://github.com/user-attachments/assets/53849b8e-a9da-4bc7-b1d1-17775a19e29f)

先是 TCP 连接空闲了 2s ，然后后端发送了 FIN 包，再然后后端 RST TCP 连接，higress 此时依然在发送请求给后端，但是后端已经断开连接， 所以请求结果是    

![image](https://github.com/user-attachments/assets/0b49a8ad-7aa9-4e78-8c7d-63be431a943f)

**Comment by LiujunjieALiling** [comment]
higress-config如下：

 addXRealIpHeader: false
    disableXEnvoyHeaders: false
    downstream:
      connectionBufferLimits: 32768
      http2:
        initialConnectionWindowSize: 1048576
        initialStreamWindowSize: 65535
        maxConcurrentStreams: 100
      idleTimeout: 7200
      maxRequestHeadersKb: 60
    upstream:
      connectionBufferLimits: 1048576
      idleTimeout: 600

**Comment by johnlanni** [comment]
那就是 upstream 的 idleTimout 配的太大，超过了后端服务的idleTimeout，连接断开的时候网关收到FIN包，和复用连接发送请求这两个行为是存在 race 的，需要调小网关的 upstream  idle timeout

**Comment by LiujunjieALiling** [comment]
> 那就是 upstream 的 idleTimout 配的太大，超过了后端服务的idleTimeout，连接断开的时候网关收到FIN包，和复用连接发送请求这两个行为是存在 race 的，需要调小网关的 upstream idle timeout

那这个值建议先调整到多少呢？

**Comment by johnlanni** [comment]
@LiujunjieALiling 要看下后端的coonection idle timeout是多少，得比这个值小

**Comment by johnlanni** [comment]
还有个办法就是重试，因为 POST 是非幂等，所以higress默认配置没有对 POST 请求开重试。如果你们评估 POST 可以重试，可以参考这个注解配置：https://higress.io/docs/latest/user/annotation-use-case/#%E9%87%8D%E8%AF%95

设置上 non_idempotent

**Comment by LiujunjieALiling** [comment]
> 还有个办法就是重试，因为 POST 是非幂等，所以higress默认配置没有对 POST 请求开重试。如果你们评估 POST 可以重试，可以参考这个注解配置：https://higress.io/docs/latest/user/annotation-use-case/#%E9%87%8D%E8%AF%95
> 
> 设置上 non_idempotent

好的，我们评估一下，先尝试一下改超时时间行不行

**Comment by johnlanni** [comment]
solved

**Comment by resisterdkdk** [comment]
@johnlanni 请问这里如果我对接的是千问的大模型，这个超时调整成什么比较合适

---
@johnlanni Please tell me if I am connecting to Qianwen’s large model, what should I adjust the timeout to?
