### ISSUE TITLE
v1.4.2安装后eureka发现不了服务ip

### ISSUE THREAD

**Issue by lcfang** [alibaba/higress#1284]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via [ASRC](https://security.alibaba.com/)(Alibaba Security Response Center) where the issue will be triaged appropriately.**

- [x] I have searched the [issues](https://github.com/alibaba/higress/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
使用k8s 1.28版本 helm部署higress1.4.2后（console和gateway配置成NodePort类型service），容器均能正常启动，console能正常访问，但是配置路由后访问服务报错

### Ⅱ. Describe what happened
console能够正常访问，配置路由策略成功，但是通过网关访问报错：
![c969d5af283063a7101bf544419b31e](https://github.com/user-attachments/assets/2587899a-08c1-43a5-a7f4-8bcccfe2c51a)
看到console中报了很多错误，不确定是否有影响：
![eb16044331581d4ce147975e56842062](https://github.com/user-attachments/assets/306e3d60-2a9a-4da3-96a2-65461e817b87)

controller中看感觉f服务发现是没有问题的，但是没有看到路由规则下发的日志，在gateway中没有看到什么重要信息

### Ⅲ. Describe what you expected to happen
路由下发成功后通过网关访问正常

### Ⅳ. How to reproduce it (as minimally and precisely as possible)
1. 配置eureka服务发现
2. 配置路由
3. 配置策略：url重定向

### Ⅵ. Environment:

- Higress version:  v1.4.2
- OS : kylin
- Others: k8s v1.28

**Comment by CH3CHO** [comment]
这个 Console 的错误日志是不影响功能的，下个版本会移除。

**Comment by CH3CHO** [comment]
请提供配置样例以供重现验证。

**Comment by lcfang** [comment]
就简单配置了一个路由和重定向规则，访问不通。
在gateway中查看cluster和endpoint情况：
![image](https://github.com/user-attachments/assets/abe459cf-a691-4a1c-9220-b4030bef8b16)
![image](https://github.com/user-attachments/assets/57ca7ead-0e88-4847-8760-80404d0ac9d5)
在controller中查看serviceentry和vs都事正常的：
![image](https://github.com/user-attachments/assets/72975b1f-5536-4317-81f2-c6099c5b3d25)
在controller和gateway中没看到什么异常，在gateway中只看到循环在报下面的wariwarning：
![image](https://github.com/user-attachments/assets/70237456-3e71-4ac7-9988-f5eca34f39e3)

**Comment by johnlanni** [comment]
你这个是建了一个固定IP的服务，配了域名？

**Comment by johnlanni** [comment]
控制台下发的吗？mcpbridge看下

**Comment by lcfang** [comment]
> 你这个是建了一个固定IP的服务，配了域名？

没有配置域名


> 控制台下发的吗？mcpbridge看下

是控制台下发的，只有一个default的mcpbridge，里面是eureka注册中心的配置

**Comment by lcfang** [comment]
通过在controller中执行`curl http://localhost:15014/debug/configz`获取configz，查找gateway中循环报warning的域名信息，发现有一个该域名是某一个服务的endpoints地址，在console的服务列表中搜索服务也能够查到：
![image](https://github.com/user-attachments/assets/943a6a53-9f2f-4a0f-891b-6fe6d0321bf6)
![image](https://github.com/user-attachments/assets/a669c2ff-e59d-487a-b3d6-cffcf5c4febf)
该服务在注册中心中查不到了，已经下掉了，于是将controller重启，gateway中不再刷上面的warning了，到gateway中查路由不生效的服务对应的endpoints也能查到了，再次访问服务就正常了。
不知道是不是因为存在注册地址是路由的服务导致的该问题，明天尝试复现一下。

**Comment by lcfang** [comment]
今天该服务再次注册到了注册中心，重启了controller和gateway后复现了该问题，但是发现并不是所有的EDS都下发失败，部分是好的，部分没有，看不出什么规律，下面是在gateway中查看cluster看到的：
![image](https://github.com/user-attachments/assets/373313bf-9cf5-4431-9c67-c5bf70c98f18)
