### ISSUE TITLE
higress 目前没有导出 wasmcustom 指标数据

### ISSUE THREAD

**Issue by machine3** [alibaba/higress#1302]
ai- statistics插件开启后会在 envoy /stats 上生成指标
```
route_upstream_model_input_token{ai_route="openai",ai_cluster="qwen",ai_model="qwen-max"} 21
route_upstream_model_output_token{ai_route="openai",ai_cluster="qwen",ai_model="qwen-max"} 17
```
但是这个指标在 /stats/promtheus 上查不到，没有暴露出来

**Comment by johnlanni** [comment]
@machine3 麻烦问题说明清楚一些哈

**Comment by machine3** [comment]
> @machine3 麻烦问题说明清楚一些哈

更改了描述

**Comment by johnlanni** [comment]
@machine3 请求 15000端口 /stats/prometheus 看不到吗，新版本确定是有的，你升级到2.0.0看看呢？
![image](https://github.com/user-attachments/assets/64199c74-6425-4898-8501-14054f8027a3)
