### ISSUE TITLE
When replacing nginx with higress, do you only need to modify the ingressClassName in ingress, or do you need to configure other content? The current configuration is 404 after higress.

### ISSUE THREAD

**Issue by biao-lvwan** [alibaba/higress#1306]
![image](https://github.com/user-attachments/assets/3684ab86-3cfa-4cf0-9639-02f1eed24ebb)
![image](https://github.com/user-attachments/assets/a4c3917c-5d15-437f-91e9-1acc8cae7d0b)
![image](https://github.com/user-attachments/assets/87cb18a0-fb38-4c62-bf4d-8f8b180f1b39)
![image](https://github.com/user-attachments/assets/a0de0e43-0899-4d8c-948f-aa8cbf80a24d)
There is no error log in the container  ,What else needs to be configured?

**Comment by biao-lvwan** [comment]
![image](https://github.com/user-attachments/assets/5f9d9223-5b2e-4748-9476-120bdc440e00)

**Comment by biao-lvwan** [comment]
![image](https://github.com/user-attachments/assets/011abcd1-8e6f-4d48-8e4f-d7b2563e2e90)

**Comment by biao-lvwan** [comment]
It has been resolved after consultation in the community group

**Comment by CH3CHO** [comment]
DNS configurations need to be updated as well.
