### ISSUE TITLE
插件【JWT 认证】支持将解析后的数据放到请求中

### ISSUE THREAD

**Issue by abclint** [alibaba/higress#1313]
## Why do you need it?
 Is your feature request related to a problem? Please describe in details

## How could it be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.
网关经过jwt解析后， 可以修改请求或者响应，比如将解析内容放入请求header或者body中，或者自定义响应内容

**Comment by johnlanni** [comment]
![Uploading image.png…]()
可以使用这个配置

**Comment by abclint** [comment]
很棒👍，问题解决了！
