### ISSUE TITLE
【skywalking】使用docker部署nacos + higress时，higress 的探针数据未体现在 skywalking链路上

### ISSUE THREAD

**Issue by JonSmall** [alibaba/higress#1314]
1. 我使用docker-compose 部署了全套的微服务栈
2. 采用了docker 部署 nacos + skywalking + higress，下层微服务探针均可在skywalking 出现数据，
但是higress的数据未体现在skywalking上
3. 目前，higress 的config 如何在nacos上配置，以及skywalking的配置如何在 higress上配置，官网没有实际的操作手册
希望大大们给出一个解决方案，跪求，谢谢

**Comment by CH3CHO** [comment]
现在这块配置不是很友好，你可以先对照这篇文档进行操作：https://github.com/CH3CHO/higress-notes
