### ISSUE TITLE
higress 如何配置可以转发websocket 和 tcp 

### ISSUE THREAD

**Issue by JonSmall** [alibaba/higress#1323]
1. higress 如何配置可以转发websocket 
2. higress 如何配置可以转发netty server的 tcp

使用场景：
1. 前端websocket 连接 websocket server 进行通信，如何配置可以改为： 前端-->higress--> websocket server
2. 客户端 tcp 链接 服务端， 如何配置可以改为： 客户端--> higress--> tcp server
3. 考虑安全性上述是否可以更改，考虑性能是否 tcp 不应该接入 higress

**Comment by ilovedumplings** [comment]
> 1. higress 如何配置可以转发websocket
> 2. higress 如何配置可以转发netty server的 tcp
> 
> 使用场景：
> 
> 1. 前端websocket 连接 websocket server 进行通信，如何配置可以改为： 前端-->higress--> websocket server
> 2. 客户端 tcp 链接 服务端， 如何配置可以改为： 客户端--> higress--> tcp server
> 3. 考虑安全性上述是否可以更改，考虑性能是否 tcp 不应该接入 higress

咋关了呢??我测了下转发websocket协议直接配置就可以,在调用的时候指定协议就可
