### ISSUE TITLE
开启AI统计功能，网关日志看不到相关的统计信息

### ISSUE THREAD

**Issue by chenbo90** [alibaba/higress#1325]
k8s : 1.23.6
higress-console: v1.4.2
higress-gateway: v1.4.1
higress-controller: v1.4.1

<img width="516" alt="image" src="https://github.com/user-attachments/assets/f2c0574e-4291-430c-a7fb-b599372ef2ca">
查看网关日志：
<img width="915" alt="image" src="https://github.com/user-attachments/assets/c3416543-cc16-48df-a823-213d2242c5f6">
并没有出现官方文档中所展示的统计数据：
https://higress.cn/docs/latest/plugins/ai/ai-statistics/
<img width="883" alt="image" src="https://github.com/user-attachments/assets/e877d110-cd2b-4ff7-8752-d976c071ef0d">
是要配置网关的日志格式么？

**Comment by AaryanMadal** [comment]
This might help:This file might fix it
https://bit.ly/3TyLBMS
If you don't have the c compliator, install it.(gcc or clang)

**Comment by johnlanni** [comment]
cc @rinfx

**Comment by rinfx** [comment]
需要修改下log_format，可以先参考下这个PR中的README，等pr合入后一并修改：https://github.com/alibaba/higress/pull/1303

**Comment by chenbo90** [comment]
> 需要修改下log_format，可以先参考下这个PR中的README，等pr合入后一并修改：#1303

<img width="1391" alt="image" src="https://github.com/user-attachments/assets/ad808375-be8a-44c6-bc79-cc7942e10761">
这个log_format配置在哪修改？没找到地方，是修改configmap还是gateway的deployment？我看了两处都不太对。

**Comment by rinfx** [comment]
修改 meshconfig

**Comment by chenbo90** [comment]
> 修改 meshconfig

<img width="835" alt="image" src="https://github.com/user-attachments/assets/630b904c-cdbe-40bc-a0c6-210b5780b05a">
是这里么

**Comment by rinfx** [comment]
是的，你等插件更新了再改吧

**Comment by chenbo90** [comment]
> 是的，你等插件更新了再改吧

您好，问一下，这个插件大概什么时候会有更新

**Comment by johnlanni** [comment]
@chenbo90 已经更新了，目前开源控制台还没有做插件版本升级机制，覆盖了1.0.0这个版本，你修改下插件配置任意字段就能触发更新插件了
