### ISSUE TITLE
非标准的ingress配置导致rancher/rancher-agent崩溃

### ISSUE THREAD

**Issue by ningpengtao-coder** [alibaba/higress#1330]
因为不是标准的ingress配置，缺少了service相关的内容，导致以下错误，是否考虑自定义crd？这样影响会小一些。
E0920 02:14:37.957633      53 runtime.go:79] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 25651 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x3741200?, 0x6c4c5a0})
	/go/pkg/mod/k8s.io/apimachinery@v0.24.5/pkg/util/runtime/runtime.go:75 +0x99
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xfffffffe?})
	/go/pkg/mod/k8s.io/apimachinery@v0.24.5/pkg/util/runtime/runtime.go:49 +0x75
panic({0x3741200, 0x6c4c5a0})
	/usr/lib64/go/1.19/src/runtime/panic.go:884 +0x212
github.com/rancher/rancher/pkg/controllers/managementagent/endpoints.convertIngressToServicePublicEndpointsMap({0x487d5c8?, 0xc016028900}, 0x0)
	/go/src/github.com/rancher/rancher/pkg/controllers/managementagent/endpoints/endpoints.go:312 +0x9af

**Comment by CH3CHO** [comment]
你可以搜索一下这里的 issues，这个是低版本 rancher 的一个 bug。高版本已经修复。

| |
Kent Dong
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年09月20日 10:21 |
| 收件人 | alibaba/higress ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | [alibaba/higress] 非标准的ingress配置导致rancher/rancher-agent崩溃 (Issue #1330) |

因为不是标准的ingress配置，缺少了service相关的内容，导致以下错误，是否考虑自定义crd？这样影响会小一些。
E0920 02:14:37.957633 53 runtime.go:79] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 25651 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x3741200?, 0x6c4c5a0})
***@***.***/pkg/util/runtime/runtime.go:75 +0x99
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xfffffffe?})
***@***.***/pkg/util/runtime/runtime.go:49 +0x75
panic({0x3741200, 0x6c4c5a0})
/usr/lib64/go/1.19/src/runtime/panic.go:884 +0x212
github.com/rancher/rancher/pkg/controllers/managementagent/endpoints.convertIngressToServicePublicEndpointsMap({0x487d5c8?, 0xc016028900}, 0x0)
/go/src/github.com/rancher/rancher/pkg/controllers/managementagent/endpoints/endpoints.go:312 +0x9af

**Comment by johnlanni** [comment]
https://github.com/alibaba/higress/issues/362#issuecomment-1573385054

嗯 rancher 2.7 修复了

**Comment by ningpengtao-coder** [comment]
> [#362 (comment)](https://github.com/alibaba/higress/issues/362#issuecomment-1573385054)
> 
> 嗯 rancher 2.7 修复了

好的，我升级一下。
