### ISSUE TITLE
AI请求/响应转换测试验证步骤请教

### ISSUE THREAD

**Issue by chenbo90** [alibaba/higress#1333]
请问下AI请求/响应转换插件验证的步骤是什么样的。看官网文档介绍只有配置，然后我按照我的理解做了下面的测试，下面将测试步骤贴出来：
1: k8s集群部署httpbin服务
<img width="919" alt="image" src="https://github.com/user-attachments/assets/11e4c948-e93e-4eeb-8cff-b6bb0a04c742">
2:配置httpbin的路由
<img width="1133" alt="image" src="https://github.com/user-attachments/assets/f7dddefe-3b22-4096-9191-7cfc2df3c666">
3:curl 访问下httpbin的xml接口
<img width="517" alt="image" src="https://github.com/user-attachments/assets/1c3aba11-55a6-4fdb-846b-3db641850d59">
4:在该路由上添加AI请求/响应插件
<img width="715" alt="image" src="https://github.com/user-attachments/assets/ccb14ba9-5609-4e9d-8503-8257cab47275">
5:再次curl发起调用httpbin的xml接口，网关日志报错：
<img width="964" alt="image" src="https://github.com/user-attachments/assets/f9f6b1da-355e-4595-b6e7-896613412775">
6:以为是需要开启AI代理，于是开启了AI代理插件
<img width="651" alt="image" src="https://github.com/user-attachments/assets/2f7dc45a-f25c-4d51-bf92-8750b5c145e4">
没有效果，网关还是报那样的错误。

下面是我higress组件的镜像版本：
<img width="632" alt="image" src="https://github.com/user-attachments/assets/be94702c-da8c-4077-b1c5-67b81279f8a6">

请教下，这个测试步骤有问题么？该如何测试

**Comment by johnlanni** [comment]
cc @rinfx

**Comment by rinfx** [comment]
transformer插件目前仅支持通义千问，另外需要在higress配一条DNS类型的服务指向千问
