### ISSUE TITLE
ai-proxy 插件配合上游 oneapi 服务时报令牌错误

### ISSUE THREAD

**Issue by mrhaoji** [alibaba/higress#1339]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via [ASRC](https://security.alibaba.com/)(Alibaba Security Response Center) where the issue will be triaged appropriately.**

- [x] I have searched the [issues](https://github.com/alibaba/higress/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
上游大模型服务由 oneapi 提供，能够正常通过令牌请求服务。
将 oneapi 接入到 Higress 后，通过 ai-proxy AI 代理插件完成配置

### Ⅱ. Describe what happened

通过 Higress 网关请求服务时，返回上游 oneapi 抛出的错误
`{"error":{"message":"无效的令牌 (request id: 202409241845268770063525973145)","type":"one_api_error"}}`
然后在 ai-proxy AI 代理插件里面配置的令牌确定是正确的

### Ⅲ. Describe what you expected to happen
正常返回大模型生成内容

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. 创建服务来源，选择 DNS 域名类型，服务端口 443，域名填 oneapi 部署的域名
2. 新建路由配置，前缀匹配 /，目标服务绑定第一步创建的服务
3. 插件配置中找到 AI 代理，填入配置
provider:
  apiTokens:
  - "sk-xxxxxxxxx"
  modelMapping:
    '*': "gpt-3.5-turbo"
    gpt-4o: "gpt-4o"
  openaiCustomUrl: "api.gptniux.com/v1/chat/completions"
  type: "openai"

### Ⅴ. Anything else we need to know?
**如果在路由配置中加上注解 higress.io/backend-protocol: "HTTPS" 然后重启服务的话，就可以恢复正常；不重启的话还是一样的报错**

### Ⅵ. Environment:

- Higress version:  higress-registry.cn-hangzhou.cr.aliyuncs.com/higress/all-in-one:latest
- OS : Ubuntu 20.04.4 LTS (GNU/Linux 5.4.0-122-generic x86_64)
- Others: Docker version 24.0.5, build 24.0.5-0ubuntu1~20.04.1

**Comment by johnlanni** [comment]
后端能看到收到的token是什么吗？没带还是？

**Comment by CH3CHO** [comment]
是配置了后端服务使用 HTTPS 协议的注解，没有生效。重启 Higress 才生效的问题。

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年09月24日 20:53 |
| 收件人 | alibaba/higress ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | Re: [alibaba/higress] ai-proxy 插件配合上游 oneapi 服务时报令牌错误 (Issue #1339) |

后端能看到收到的token是什么吗？没带还是？

**Comment by CH3CHO** [comment]
用户使用 higress-aio 镜像启动。

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年09月24日 20:53 |
| 收件人 | alibaba/higress ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | Re: [alibaba/higress] ai-proxy 插件配合上游 oneapi 服务时报令牌错误 (Issue #1339) |

后端能看到收到的token是什么吗？没带还是？

**Comment by mrhaoji** [comment]
> 是配置了后端服务使用 HTTPS 协议的注解，没有生效。重启 Higress 才生效的问题。
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 发送日期 | 2024年09月24日 20:53 | | 收件人 | alibaba/higress ***@***.***> | | 抄送人 | Subscribed ***@***.***> | | 主题 | Re: [alibaba/higress] ai-proxy 插件配合上游 oneapi 服务时报令牌错误 (Issue #1339) | 后端能看到收到的token是什么吗？没带还是？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

已补充在 Ⅴ 部分

**Comment by CH3CHO** [comment]
我本地使用同样的 aio 镜像进行配置，这个问题没有重现。

**Comment by johnlanni** [comment]
@mrhaoji 你能复现吗，是否是当时其他因素影响的

**Comment by mrhaoji** [comment]
能稳定复现，路由配置加上 Ⅴ 里面提到的那个注解之后请求还是报错（表现为上游没收到 AI 代理里面配置的那个 apiTokens 密钥），但是重启容器，请求正常的。

**Comment by johnlanni** [comment]
@mrhaoji 麻烦提供一下你的本地ingress和wasmplugin配置，脱敏之后发一下吧

**Comment by CH3CHO** [comment]
与用户一同尝试重现问题失败。功能工作正常。本 issue 关闭。
