### ISSUE TITLE
AI内容安全插件命中自定义词库时上游服务未返回插件期望字段

### ISSUE THREAD

**Issue by mrhaoji** [alibaba/higress#1346]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via [ASRC](https://security.alibaba.com/)(Alibaba Security Response Center) where the issue will be triaged appropriately.**

- [x] I have searched the [issues](https://github.com/alibaba/higress/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
![CleanShot X 2024-09-25 22 30 41](https://github.com/user-attachments/assets/214e39d8-e613-4583-98f9-52ebbd3c7659)
上游阿里云内容安全服务命中自定义词库的时候，返回结构体里面没有 advice 字段
![CleanShot X 2024-09-25 22 35 12](https://github.com/user-attachments/assets/e8bfec8d-7f6f-4b6a-b752-d3746b502654)
而插件走内容安全的逻辑是这么判断的，导致命中自定义敏感词后仍然走了模型本身去返回结果

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅲ. Describe what you expected to happen
![CleanShot X 2024-09-25 22 28 41](https://github.com/user-attachments/assets/eb9f699f-e328-4b93-8154-44eb6eeab154)
改为利用上游内容安全服务的 RiskLevel 字段来判断是否走安全服务返回
https://help.aliyun.com/document_detail/2671445.html

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

as shown in I part

### Ⅴ. Anything else we need to know?
no.

### Ⅵ. Environment:

- Higress version:  latest
- OS : not important in this case
- Others: not important in this case

**Comment by CH3CHO** [comment]
请@rinfx 看一下。

**Comment by mrhaoji** [comment]
@rinfx  有点影响业务，着急用，看能不能辛苦让这种情况先直接抛用户配置的兜底回复

后面我再给 pr 个 RiskLevel 参数，对齐上游服务的 RiskLevel（high/medium/low/none）让用户可以自定义什么级别触发兜底，跟 Azure OpenAI 审核服务那个 ContentFiliter 功能类似

**Comment by rinfx** [comment]
好，我现在出个pr

**Comment by rinfx** [comment]
https://github.com/alibaba/higress/pull/1347
