### ISSUE TITLE
添加新插件时默认会全局开启，导致网关异常

### ISSUE THREAD

**Issue by w7team** [alibaba/higress#1350]
在k8s中部署的，添加新插件时默认会全局开启，导致网关异常。
数据库又在黑盒中，很难调试，如果console的地址是通过ingress创建的话，一旦出问题很难关闭插件。

**Comment by hanxiantao** [comment]
> 在k8s中部署的，添加新插件时默认会全局开启，导致网关异常。
> 数据库又在黑盒中，很难调试，如果console的地址是通过ingress创建的话，一旦出问题很难关闭插件。

应该不是默认全局开启的，可以控制路由级别或者域名级别生效

![image](https://github.com/user-attachments/assets/28027bbf-efd5-4974-97fb-c352015a5344)

可以看下这个文档：https://higress.io/docs/latest/plugins/intro/

**Comment by CH3CHO** [comment]
麻烦提供一下详细的配置步骤。配置内容可以脱敏后提交上来，便于我们重现。

**Comment by johnlanni** [comment]
添加新插件不会默认全局开启的
