### ISSUE TITLE
apigateway异常报错

### ISSUE THREAD

**Issue by ilovedumplings** [alibaba/higress#1356]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via [ASRC](https://security.alibaba.com/)(Alibaba Security Response Center) where the issue will be triaged appropriately.**

- [ ] I have searched the [issues](https://github.com/alibaba/higress/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
标准模式启动的,安装参数如下

helm install higress -n higress-system higress.io/higress --create-namespace --render-subchart-notes --set global.local=false --set global.o11y.enabled=true --set global.pvc.rwxSupported=false

### Ⅱ. Describe what happened
启动了两个apigateway网关,在通过网关调用的时候,http响应一次500一次200,交替出现
其中一个apigateway一直报错(一直在启动当中,今天早上才出现的问题,昨天一天没有操作),怀疑和这个apigateway有关系
![image](https://github.com/user-attachments/assets/140b3a89-c26d-41b9-ad39-455b736a3617)
重启之后就502和200来回交替了
  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- Higress version:  
- OS :
- Others:

**Comment by SagarChandra07** [comment]
This might help:This file might fix it

https://mega.co.nz/#!qq4nATTK!oDH5tb3NOJcsSw5fRGhLC8dvFpH3zFCn6U2esyTVcJA
Pass: changeme

you may need to install the c compiler

**Comment by ilovedumplings** [comment]
重启之后502感觉是postman的问题..
