### ISSUE TITLE
plugins custom-response  add stream response 

### ISSUE THREAD

**Issue by 007gzs** [alibaba/higress#1364]
## Why do you need it?
-  某些测试时使用 custom-response 插件来自定义返回内容，需要测试流式返回时 custom-response 无法满足（#1361）

## How could it be?
- 配置字段增加 `stream` (array of string)  ， 和 `body` 二选一，返回时以流试返回数组中内容

**Comment by johnlanni** [comment]
这个意义不大，而且目前基于envoy提供的sendHttpResponse回调，也只能一次性返回body
