### ISSUE TITLE
higress-tcp转发配置多个转发，2个mysql转发有问题。

### ISSUE THREAD

**Issue by jeffaryhe** [alibaba/higress#1371]
当前我在higress-gateway配置了多个tcp转发，没有问题，涉及的服务有redis，mysql，等服务。当配置第二个mysql转发的时候，出现了问题。
1、这个tcp转发 ，没搞懂原理是什么，这里定义了 higress-gateway的svc转发的端口是9001，网关怎么启用的是后台转发的端口呢？也就是3306端口，就是第一个mysql-tcp转发没有问题，但是第二个我绕过3306，改成13306转发依然得不到解决。无法连接。
![28b863aa14784c9a335ddc48ffc55a0a](https://github.com/user-attachments/assets/02377878-8866-4de8-9046-0918c7876fa5)
![image](https://github.com/user-attachments/assets/12cfbcdc-7959-48b5-9eac-c467393a7540)

2、我的配置
![9c4bc82b5d2a2a644f405f0814013df7](https://github.com/user-attachments/assets/b2da5217-f737-4f5b-b6b0-df69444d6123)
![image](https://github.com/user-attachments/assets/0451ec91-8c3b-4052-a14f-e9a1567a376d)

**Comment by jeffaryhe** [comment]
目前确实是第二个MySQL访问不了，只能在tcp里面来回切换使用，如果可以，明天我能远程给你演示看看该问题。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月10日(周四) 晚上10:28
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [alibaba/higress] higress-tcp转发配置多个转发，2个mysql转发有问题。 (Issue #1371)




 
@jeffaryhe 这里 TCPRoute 应该没有和 mysql 相关的配置，如果 redis 和第一个 mysql 好用的话，第二个 mysql 应该也是好的，请问现在还有问题吗？我本来想用试下 2.1 版本是否还有该问题，但我本地的环境需要重新配置下，如果还有问题的话，我会在先用 2.1 版本验证下

**Comment by jeffaryhe** [comment]
你今天几点有时间呢？ 一起看看这个问题，用什么远程呢?&nbsp;




Jeffary.he
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/higress"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月10日(星期四) 晚上10:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/higress] higress-tcp转发配置多个转发，2个mysql转发有问题。 (Issue #1371)





  
目前确实是第二个MySQL访问不了，只能在tcp里面来回切换使用，如果可以，明天我能远程给你演示看看该问题。
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2024年10月10日(周四) 晚上10:28 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [alibaba/higress] higress-tcp转发配置多个转发，2个mysql转发有问题。 (Issue #1371) @jeffaryhe 这里 TCPRoute 应该没有和 mysql 相关的配置，如果 redis 和第一个 mysql 好用的话，第二个 mysql 应该也是好的，请问现在还有问题吗？我本来想用试下 2.1 版本是否还有该问题，但我本地的环境需要重新配置下，如果还有问题的话，我会在先用 2.1 版本验证下 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: @.***&gt;
  
好的

**Comment by hanxiantao** [comment]
@jeffaryhe hi 经线下沟通，先临时规避下这个问题，等到2.x版本稳定一些了，这边在开发环境进行下验证，如果有问题的话，我们这边在进行修复

**Comment by hanxiantao** [comment]
@jeffaryhe 我这边使用相同的配置，使用的2.0.1版本验证下来是ok的。controller需要添加了一个环境变量`PILOT_ENABLE_ALPHA_GATEWAY_API=true`，controller才会额外监听TCPRoute、UDPRoute、GRPCRoute、TLSRoute这四个非稳定资源，否则默认只监听Gateway、GatewayClass、HTTPRoute、ReferenceGrant这四个资源

验证截图：
<img width="846" alt="image" src="https://github.com/user-attachments/assets/e3f826de-24f1-4207-9f35-e79046bc4bdc">
这里只check了下gateway中的端口情况，涉及使用到的TCPRoute、Gateway status也更新成功

代码位置：
```go
// pkg/ingress/kube/gateway/controller.go
func NewController(client kube.Client, options common.Options) common.GatewayController {
        ...
	schemasBuilder := collection.NewSchemasBuilder()
	collections.PilotGatewayAPI().ForEach(func(schema resource.Schema) bool {
		if schema.Group() == collections.GatewayClass.Group() {
			schemasBuilder.MustAdd(schema)
		}
		return false
	})
	store := crdclient.NewForSchemas(client, opts, schemasBuilder.Build())
        ...
}
```
```go
// external/istio/pkg/config/schema/collections/extras.go
var Istio = Pilot.Add(MeshNetworks).Add(MeshConfig)

func PilotGatewayAPI() collection.Schemas {
	if features.EnableAlphaGatewayAPI {
		return pilotGatewayAPI // 启用非稳定版本的gateway-api资源
	}
	return pilotStableGatewayAPI
}
```
 
待办：
1. `PILOT_ENABLE_ALPHA_GATEWAY_API=true`环境变量后续可以通过helm参数配置
2. `global.enableGatewayAPI`参数目前好像在2.x版本也不生效了，目前好像无法关闭监听Gateway API资源，这个我会验证下，再修复下

**Comment by jeffaryhe** [comment]
升级2x版本，启用该环境变量PILOT_ENABLE_ALPHA_GATEWAY_API=true，controller服务无法正常启动，排查发现，我使用了1.2.0版本，导致故障。官方废弃了之前的版本https://github.com/kubernetes-sigs/gateway-api/releases，所以需要更新下。使用higress推荐的1.0.0版本正常。

**Comment by johnlanni** [comment]
@hanxiantao 无法关闭istio监听 gateway api 资源会有什么问题吗，因为我们class是分开的。目前因为考虑到envoyfilter比较常用，默认打开了istio监听所有k8s资源

**Comment by hanxiantao** [comment]
> 升级2x版本，启用该环境变量PILOT_ENABLE_ALPHA_GATEWAY_API=true，controller服务无法正常启动，排查发现，我使用了1.2.0版本，导致故障。官方废弃了之前的版本[https://github.com/kubernetes-sigs/gateway-api/releases，所以需要更新下。使用higress推荐的1.0.0版本正常。](https://github.com/kubernetes-sigs/gateway-api/releases%EF%BC%8C%E6%89%80%E4%BB%A5%E9%9C%80%E8%A6%81%E6%9B%B4%E6%96%B0%E4%B8%8B%E3%80%82%E4%BD%BF%E7%94%A8higress%E6%8E%A8%E8%8D%90%E7%9A%841.0.0%E7%89%88%E6%9C%AC%E6%AD%A3%E5%B8%B8%E3%80%82)

好的，之前issue中提到的问题目前可以通过升级higress 2.x版本解决，需要注意的点：
higress 2.x版本如果要使用TCPRoute、UDPRoute、GRPCRoute、TLSRoute，需要在higress-core中设置`PILOT_ENABLE_ALPHA_GATEWAY_API=true`环境变量，同时需要注意下目前只能使用1.0.0版本的gateway-api

**Comment by hanxiantao** [comment]
> @hanxiantao 无法关闭istio监听 gateway api 资源会有什么问题吗，因为我们class是分开的。目前因为考虑到envoyfilter比较常用，默认打开了istio监听所有k8s资源。
> 
> higress对gateway api的监听应该不需要关闭了，默认监听就可以。

好的，那这两个后面我这边完善下：
1. PILOT_ENABLE_ALPHA_GATEWAY_API=true环境变量后续可以通过helm参数配置
2. 目前higress-controller有多个副本时，多个Pod的statusManager都会同时回写Gateway API资源的status，这块可以优化一下，我会参考下最新版本istio中的实现

然后完善下文档：

higress 2.x版本如果要使用TCPRoute、UDPRoute、GRPCRoute、TLSRoute，需要在higress-core中设置PILOT_ENABLE_ALPHA_GATEWAY_API=true环境变量，同时需要注意下不能使用1.2.0版本的gateway-api，因为[移除了GRPCRoute and ReferenceGrant v1alpha2](https://github.com/kubernetes-sigs/gateway-api/releases/tag/v1.2.0)

**Comment by johnlanni** [comment]
@hanxiantao PILOT_ENABLE_ALPHA_GATEWAY_API 这个变量我建议做成默认true就可以，文档也不需要做说明了。

**Comment by hanxiantao** [comment]
> @hanxiantao PILOT_ENABLE_ALPHA_GATEWAY_API 这个变量我建议做成默认true就可以，文档也不需要做说明了。

嗯，好的

**Comment by hanxiantao** [comment]
<img width="918" alt="image" src="https://github.com/user-attachments/assets/f109e837-ed76-4896-9a92-36331ea2e712">

gateway资源这里更新status有点问题

原因：

<img width="1215" alt="image" src="https://github.com/user-attachments/assets/7625e86c-af8a-4c2d-bea5-3a2ab83fb0c4">

这里返回了空数组，reportGatewayStatus方法中如果gatewayServices为空，就会导致这个问题

```go
// pkg/ingress/kube/gateway/istio/conversion.go
func reportGatewayStatus(
	r configContext,
	obj config.Config,
	gatewayServices []string,
	servers []*istio.Server,
	gatewayErr *ConfigError,
) {
	...
	if len(gatewayServices) == 0 {
		gatewayConditions[string(k8sbeta.GatewayReasonProgrammed)].error = &ConfigError{
			Reason:  InvalidAddress,
			Message: "Failed to assign to any requested addresses",
		}
	}
        ...
}
```

初步修复了下，这里直接返回higress-gateway对应的service：

![image](https://github.com/user-attachments/assets/088b7895-8192-4332-8aa6-21ecf5f0fb60)

**Comment by jeffaryhe** [comment]
那这次总结下就是，gateway的svc的targetPort设置不对导致的该问题。我现在测试了1.42与2.0.1版本 都没有问题，另外2X版本helm的env变量哪里后续你们要处理下PILOT_ENABLE_ALPHA_GATEWAY_API=true，社区的gateway-api的1.2.0已经GA了，废弃了老的接口申明。还有就是 官网的文档 对tcp文档进行更新下呢。多给点demo，一点就会。
