### ISSUE TITLE
rust插件支持发送外部请求

### ISSUE THREAD

**Issue by titrxw** [alibaba/higress#1376]
## Why do you need it?
 Is your feature request related to a problem? Please describe in details
如题

## How could it be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by johnlanni** [comment]
这块已经有一个初步的实现，不过sdk还在优化中 cc @007gzs

**Comment by 007gzs** [comment]
外部请求是指http_call么？

**Comment by titrxw** [comment]
@007gzs  是的， 还有就是http_call这个没法同步返回响应结果（body,status）？  只能走回调？

**Comment by titrxw** [comment]
self.http_dispatcher.dispatch(
               "httpbin",
               vec![
                   (":method", "GET"),
                   (":path", "/bytes/1"),
                   (":authority", "httpbin.org"),
               ],
               None,
               vec![],
               Duration::from_secs(1)
           )

panicked at /Users/rxwyun/Develop/rust/higress/plugins/wasm-rust/src/dispatcher.rs │ │
│ :36:87:                                                                                                                                                                                          │ │
│ called `Result::unwrap()` on an `Err` value: BadArgument

BadArgument一般是什么原因?

**Comment by jizhuozhi** [comment]
这里httpbin是需要envoy有注册过这个cluster，如果没有配置话这里是没办法正确分配的

**Comment by 007gzs** [comment]
参考 https://github.com/alibaba/higress/blob/main/plugins/wasm-rust/src/cluster_wrapper.rs

**Comment by titrxw** [comment]
经过网关的原始请求的数据包大小超过30K后， 插件里面如果设置cache_response_body为true， 会直接影响原始请求响应的下发。 这个是什么原因？

**Comment by 007gzs** [comment]
> 经过网关的原始请求的数据包大小超过30K后， 插件里面如果设置cache_response_body为true， 会直接影响原始请求响应的下发。 这个是什么原因？

@johnlanni 网关缓存大小有限制么

**Comment by hanxiantao** [comment]
> 经过网关的原始请求的数据包大小超过30K后， 插件里面如果设置cache_response_body为true， 会直接影响原始请求响应的下发。 这个是什么原因？

应该是这个配置 `downstream.connectionBufferLimits`。可以看下这个文档[全局配置说明
](https://higress.io/docs/latest/user/configmap/)

**Comment by titrxw** [comment]
我修改下试试

**Comment by titrxw** [comment]
可以了，感谢

**Comment by jizhuozhi** [comment]
> 可以了，感谢

可以了解下最终形态么，我们也看下怎么优化HTTP调用这块

**Comment by cuisongliu** [comment]
> 受限于envoy的IO模型，wasm是没办法写同步风格的外部调用的（GO也不行）。
> 
> 之前想过能不能通过JS Promise风格的API来简化外部调用，刚好昨天实现了一个原型， #1377 ，可以看下能不能满足需求[http-dispatch-example](https://github.com/alibaba/higress/blob/f55b02f2d9a3f1592119c8723e84cdc246d9ca1f/plugins/wasm-rust/example/http-dispatch-example/src/lib.rs)

我记得这个是因为envoy的wasm必须实现ABI协议才行，所以才有的那些sdk  之前做过尝试应该是不大行的 不知道higress能否脱离这个。

**Comment by johnlanni** [comment]
@cuisongliu 也是遵循这个ABI协议的，你是说基于wasi么，这个在envoy里不太现实。envoy本身有个eventloop，如果用wasi的异步IO，还需要在wasm里再起一个eventloop，两个eventloop之间目前无法联动。

**Comment by 007gzs** [comment]
最新版支持回调模式了，可以看下
https://github.com/alibaba/higress/blob/f8d62a8ac3d8ff56b9784f4e41a120ff514ca979/plugins/wasm-rust/extensions/demo-wasm/src/lib.rs#L97-L131
