### ISSUE TITLE
支持downstream.connectionBufferLimits等higress全局配置可以通过helm参数配置

### ISSUE THREAD

**Issue by w7team** [alibaba/higress#1386]
目前默认值比较小，想在安装时就配置好

**Comment by CH3CHO** [comment]
目前可以通过修改 ConfigMap 的方式进行配置，但 helm chart 里还没有提供修改这个参数的配置：

![image](https://github.com/user-attachments/assets/dc08646f-bc81-4b5e-88df-3ea9df143f0c)

**Comment by CH3CHO** [comment]
@johnlanni ，你看这里我们是否有必要在 values 里支持一下？

**Comment by w7team** [comment]
我们做插件时发现这一块的设置还挺重要的，helm能给个安装设置项就更好了，虽然我们先安装helm，再kubectl修改configmap也能解决，但感觉不够优雅

**Comment by johnlanni** [comment]
嗯 这块可以支持一下，在values里可以做higress相关的参数配置
