### ISSUE TITLE
容器构建higress时会报 run.sh找不到错误

### ISSUE THREAD

**Issue by bergen4** [alibaba/higress#1388]
执行命令：BUILD_WITH_CONTAINER=1 make build-gateway-local
报错信息：
![QQ_1728899488271](https://github.com/user-attachments/assets/c4eb7a25-7506-4070-b668-ad387d43323b)

打印这个external/istio目录下Makefile的RUN变量，值为tools/hack/run.sh。而不是赋值的./common/scripts/run.sh，原因未知
![QQ_1728899516465](https://github.com/user-attachments/assets/d3e8ccb5-ddb3-4f3c-bffc-efdabd829cbf)

**Comment by CH3CHO** [comment]
BUILD_WITH_CONTAINER=1 这个可以不用加，Makefile 里面实际是加了。不过这个问题我们看一下。

**Comment by CH3CHO** [comment]
> BUILD_WITH_CONTAINER=1 这个可以不用加，Makefile 里面实际是加了。不过这个问题我们看一下。

个人觉得原因是，build-gateway-local 这个 target 里面用的就是 BUILD_WITH_CONTAINER=1。在外面又加一层 BUILD_WITH_CONTAINER=1，就变成 docker-in-docker 了。这里可能会有一些问题。你可以先把外面的 BUILD_WITH_CONTAINER=1 去掉试试。如果有权限问题的话，可以考虑加 sudo。

**Comment by bergen4** [comment]
谢谢回答。去掉BUILD_WITH_CONTAINER=1后，没有这个报错了，但是遇到envoy和ztunnel下载很慢失败的问题，所以我把envoy和ztunnel下载好后放到宿主机，再挂载到容器中
![QQ_1728958368778](https://github.com/user-attachments/assets/476292b2-d19f-4e7f-be02-5c5478ff051f)

下载问题解决后，容器构建又遇到envoy找不到的问题，这是什么原因呢
![QQ_1728958468593](https://github.com/user-attachments/assets/786d67cc-b3f8-4131-9b16-f193a370bd2d)

**Comment by johnlanni** [comment]
这个是checksum不对，你copy进去的envoy有问题

**Comment by johnlanni** [comment]
网络问题需要自己解决一下，可以看下启动容器的时候是把 http_proxy/https_proxy 两个变量注入进去的，配置好对应的代理配置即可

**Comment by bergen4** [comment]
换了一台编译机起，网络问题看上去ok了，build-gate-loacal能构建成功。但是build-envoy时报错，https://storage.googleapis.com/quiche-envoy-integration/dd4080fec0b443296c0ed0036e1e776df8813aa7.tar.gz的checksum不对，这次构建没有修改构建流程，直接执行的make build-envoy
![QQ_1728964347635](https://github.com/user-attachments/assets/5cbe555b-b583-46dd-b72e-92a213b56e17)

**Comment by johnlanni** [comment]
> 换了一台编译机起，网络问题看上去ok了，build-gate-loacal能构建成功。但是build-envoy时报错，[https://storage.googleapis.com/quiche-envoy-integration/dd4080fec0b443296c0ed0036e1e776df8813aa7.tar.gz的checksum不对，这次构建没有修改构建流程，直接执行的make](https://storage.googleapis.com/quiche-envoy-integration/dd4080fec0b443296c0ed0036e1e776df8813aa7.tar.gz%E7%9A%84checksum%E4%B8%8D%E5%AF%B9%EF%BC%8C%E8%BF%99%E6%AC%A1%E6%9E%84%E5%BB%BA%E6%B2%A1%E6%9C%89%E4%BF%AE%E6%94%B9%E6%9E%84%E5%BB%BA%E6%B5%81%E7%A8%8B%EF%BC%8C%E7%9B%B4%E6%8E%A5%E6%89%A7%E8%A1%8C%E7%9A%84make) build-envoy ![QQ_1728964347635](https://private-user-images.githubusercontent.com/10844865/376451103-5cbe555b-b583-46dd-b72e-92a213b56e17.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5Nzk5ODMsIm5iZiI6MTcyODk3OTY4MywicGF0aCI6Ii8xMDg0NDg2NS8zNzY0NTExMDMtNWNiZTU1NWItYjU4My00NmRkLWI3MmUtOTJhMjEzYjU2ZTE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE1VDA4MDgwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjMTgzMDA2Y2ZlMjJiOWYwYzhkMzA0ZWU1YWEzMTdmZGExMmMwMjgyZWNlM2Y0ODlmZGIyYTU2YWMyMTExMjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xatYztwRKaxiO8Ah1MWjraa1YObdrFcblo9E9uEzSZs)

这个也是你的网络问题哈

**Comment by bergen4** [comment]
> > 换了一台编译机起，网络问题看上去ok了，build-gate-loacal能构建成功。但是build-envoy时报错，[https://storage.googleapis.com/quiche-envoy-integration/dd4080fec0b443296c0ed0036e1e776df8813aa7.tar.gz的checksum不对，这次构建没有修改构建流程，直接执行的make](https://storage.googleapis.com/quiche-envoy-integration/dd4080fec0b443296c0ed0036e1e776df8813aa7.tar.gz%E7%9A%84checksum%E4%B8%8D%E5%AF%B9%EF%BC%8C%E8%BF%99%E6%AC%A1%E6%9E%84%E5%BB%BA%E6%B2%A1%E6%9C%89%E4%BF%AE%E6%94%B9%E6%9E%84%E5%BB%BA%E6%B5%81%E7%A8%8B%EF%BC%8C%E7%9B%B4%E6%8E%A5%E6%89%A7%E8%A1%8C%E7%9A%84make) build-envoy ![QQ_1728964347635](https://private-user-images.githubusercontent.com/10844865/376451103-5cbe555b-b583-46dd-b72e-92a213b56e17.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5Nzk5ODMsIm5iZiI6MTcyODk3OTY4MywicGF0aCI6Ii8xMDg0NDg2NS8zNzY0NTExMDMtNWNiZTU1NWItYjU4My00NmRkLWI3MmUtOTJhMjEzYjU2ZTE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE1VDA4MDgwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjMTgzMDA2Y2ZlMjJiOWYwYzhkMzA0ZWU1YWEzMTdmZGExMmMwMjgyZWNlM2Y0ODlmZGIyYTU2YWMyMTExMjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xatYztwRKaxiO8Ah1MWjraa1YObdrFcblo9E9uEzSZs)
> 
> 这个也是你的网络问题哈

这个看上去是sha256sum不对？这个文件是能下载下来的，修改成正确的sha256就可以了

**Comment by johnlanni** [comment]
应该不是吧，看上去是请求googleapis.com网络出错

**Comment by johnlanni** [comment]
哦 是的，我看错了。

**Comment by bergen4** [comment]
后面的依赖下载还是很慢，275秒只下载了29%，最终下载失败，SSL超时
![QQ_1728982754668](https://github.com/user-attachments/assets/1bd60489-44b0-4d07-b40a-d9b76ca40dce)

但是我直接wget是很快的，42秒全部下完了
![QQ_1728982839637](https://github.com/user-attachments/assets/1c27c0d2-8799-4e35-b7e9-cb7cc14eb875)

感觉跟http代理没关系？

**Comment by bergen4** [comment]
> > > 换了一台编译机起，网络问题看上去ok了，build-gate-loacal能构建成功。但是build-envoy时报错，[https://storage.googleapis.com/quiche-envoy-integration/dd4080fec0b443296c0ed0036e1e776df8813aa7.tar.gz的checksum不对，这次构建没有修改构建流程，直接执行的make](https://storage.googleapis.com/quiche-envoy-integration/dd4080fec0b443296c0ed0036e1e776df8813aa7.tar.gz%E7%9A%84checksum%E4%B8%8D%E5%AF%B9%EF%BC%8C%E8%BF%99%E6%AC%A1%E6%9E%84%E5%BB%BA%E6%B2%A1%E6%9C%89%E4%BF%AE%E6%94%B9%E6%9E%84%E5%BB%BA%E6%B5%81%E7%A8%8B%EF%BC%8C%E7%9B%B4%E6%8E%A5%E6%89%A7%E8%A1%8C%E7%9A%84make) build-envoy ![QQ_1728964347635](https://private-user-images.githubusercontent.com/10844865/376451103-5cbe555b-b583-46dd-b72e-92a213b56e17.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5Nzk5ODMsIm5iZiI6MTcyODk3OTY4MywicGF0aCI6Ii8xMDg0NDg2NS8zNzY0NTExMDMtNWNiZTU1NWItYjU4My00NmRkLWI3MmUtOTJhMjEzYjU2ZTE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE1VDA4MDgwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjMTgzMDA2Y2ZlMjJiOWYwYzhkMzA0ZWU1YWEzMTdmZGExMmMwMjgyZWNlM2Y0ODlmZGIyYTU2YWMyMTExMjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xatYztwRKaxiO8Ah1MWjraa1YObdrFcblo9E9uEzSZs)
> > 
> > 
> > 这个也是你的网络问题哈
> 
> 这个看上去是sha256sum不对？这个文件是能下载下来的，修改成正确的sha256就可以了

build-envoy的时候也有checksum不对的问题，修改sha256sum的值后又报文件找不到，构建脚本是不是有问题。
![QQ_1729041730540](https://github.com/user-attachments/assets/87ec79ae-a2cf-45da-b6bb-72b26ec489ac)
![QQ_1729041820767](https://github.com/user-attachments/assets/c2950fc5-531f-464c-8a73-d7bcc99a6177)

**Comment by CH3CHO** [comment]
> 这个看上去是sha256sum不对？这个文件是能下载下来的，修改成正确的sha256就可以了

你确定文件内容是对的吗？

**Comment by bergen4** [comment]
我手动下载指定的版本下来checksum也是跟脚本中配置的checksum对不上的，需要修改才能构建通过

**Comment by CH3CHO** [comment]
> 我手动下载指定的版本下来checksum也是跟脚本中配置的checksum对不上的，需要修改才能构建通过

你把你遇到的下下来checksum不对的文件URL和脚本里的checksum贴一下，我这儿试试看

**Comment by bergen4** [comment]
> > > > 换了一台编译机起，网络问题看上去ok了，build-gate-loacal能构建成功。但是build-envoy时报错，[https://storage.googleapis.com/quiche-envoy-integration/dd4080fec0b443296c0ed0036e1e776df8813aa7.tar.gz的checksum不对，这次构建没有修改构建流程，直接执行的make](https://storage.googleapis.com/quiche-envoy-integration/dd4080fec0b443296c0ed0036e1e776df8813aa7.tar.gz%E7%9A%84checksum%E4%B8%8D%E5%AF%B9%EF%BC%8C%E8%BF%99%E6%AC%A1%E6%9E%84%E5%BB%BA%E6%B2%A1%E6%9C%89%E4%BF%AE%E6%94%B9%E6%9E%84%E5%BB%BA%E6%B5%81%E7%A8%8B%EF%BC%8C%E7%9B%B4%E6%8E%A5%E6%89%A7%E8%A1%8C%E7%9A%84make) build-envoy ![QQ_1728964347635](https://private-user-images.githubusercontent.com/10844865/376451103-5cbe555b-b583-46dd-b72e-92a213b56e17.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5Nzk5ODMsIm5iZiI6MTcyODk3OTY4MywicGF0aCI6Ii8xMDg0NDg2NS8zNzY0NTExMDMtNWNiZTU1NWItYjU4My00NmRkLWI3MmUtOTJhMjEzYjU2ZTE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE1VDA4MDgwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjMTgzMDA2Y2ZlMjJiOWYwYzhkMzA0ZWU1YWEzMTdmZGExMmMwMjgyZWNlM2Y0ODlmZGIyYTU2YWMyMTExMjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xatYztwRKaxiO8Ah1MWjraa1YObdrFcblo9E9uEzSZs)
> > > 
> > > 
> > > 这个也是你的网络问题哈
> > 
> > 
> > 这个看上去是sha256sum不对？这个文件是能下载下来的，修改成正确的sha256就可以了
> 
> build-envoy的时候也有checksum不对的问题，修改sha256sum的值后又报文件找不到，构建脚本是不是有问题。 ![QQ_1729041730540](https://private-user-images.githubusercontent.com/10844865/376851666-87ec79ae-a2cf-45da-b6bb-72b26ec489ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwNDIxODQsIm5iZiI6MTcyOTA0MTg4NCwicGF0aCI6Ii8xMDg0NDg2NS8zNzY4NTE2NjYtODdlYzc5YWUtYTJjZi00NWRhLWI2YmItNzJiMjZlYzQ4OWFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE2VDAxMjQ0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkMWM1NzEzZmIwYWM2ODQ4ZjNlM2YzOWM1MjY1NmNjYjgzMTU1MzQ2YTM4YzlmMTM2NzJlNDIzZGM1OTJiYjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.r1isuH1pJkUrbc0ewMUGGOMr7IYBcU9pXLJlR9nyjxY) ![QQ_1729041820767](https://private-user-images.githubusercontent.com/10844865/376851734-c2950fc5-531f-464c-8a73-d7bcc99a6177.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwNDIxODQsIm5iZiI6MTcyOTA0MTg4NCwicGF0aCI6Ii8xMDg0NDg2NS8zNzY4NTE3MzQtYzI5NTBmYzUtNTMxZi00NjRjLThhNzMtZDdiY2M5OWE2MTc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE2VDAxMjQ0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxZWNjOTQyZGU0MGQ1MzA0ZjNkMGUyMWUwMWNkZjM2MTZhNzVhZjNjNmNhZDdlOWUwMzE0MWVlMzUwZTNiOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.mRRYWECVGymoVotZxrO1bzA1GmUgvEFXkc2KoXbbOPg)

这个文件找不到的问题是文件的前缀配置错了
![QQ_1729042456696](https://github.com/user-attachments/assets/47e24006-3652-4505-8e5f-fa1f93616979)

**Comment by bergen4** [comment]
> > 我手动下载指定的版本下来checksum也是跟脚本中配置的checksum对不上的，需要修改才能构建通过
> 
> 你把你遇到的下下来checksum不对的文件URL和脚本里的checksum贴一下，我这儿试试看
https://github.com/intel/ipp-crypto/archive/ippcp_2021.6.tar.gz
![QQ_1729042819013](https://github.com/user-attachments/assets/24359733-2a39-434c-aad2-23444760eea6)

![QQ_1729042796863](https://github.com/user-attachments/assets/4fd525bc-36f5-4ff3-8ead-0c649e8aefc3)

**Comment by CH3CHO** [comment]
> 这个文件找不到的问题是文件的前缀配置错了 ![QQ_1729042456696](https://private-user-images.githubusercontent.com/10844865/376854988-47e24006-3652-4505-8e5f-fa1f93616979.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwNDI5MTksIm5iZiI6MTcyOTA0MjYxOSwicGF0aCI6Ii8xMDg0NDg2NS8zNzY4NTQ5ODgtNDdlMjQwMDYtMzY1Mi00NTA1LThlNWYtZmExZjkzNjE2OTc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE2VDAxMzY1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5ODRkOWNlZGFhMDY3NWQxZmUzYjE2NDdlNzE1NGRlNTI2OWQzMmRjOWRjOWI3YzNiNmU0OTIwMmNkNDBlZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.oQjVqQyORXDTxLHdrXGK8vGcH-WAiQ4kZ6f2mViUjaM)

感觉应该是 Intel 调整了 GitHub 的仓库，导致原来的这个地址发生了变化。

**Comment by CH3CHO** [comment]
> > 这个文件找不到的问题是文件的前缀配置错了 ![QQ_1729042456696](https://private-user-images.githubusercontent.com/10844865/376854988-47e24006-3652-4505-8e5f-fa1f93616979.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwNDI5MTksIm5iZiI6MTcyOTA0MjYxOSwicGF0aCI6Ii8xMDg0NDg2NS8zNzY4NTQ5ODgtNDdlMjQwMDYtMzY1Mi00NTA1LThlNWYtZmExZjkzNjE2OTc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE2VDAxMzY1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5ODRkOWNlZGFhMDY3NWQxZmUzYjE2NDdlNzE1NGRlNTI2OWQzMmRjOWRjOWI3YzNiNmU0OTIwMmNkNDBlZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.oQjVqQyORXDTxLHdrXGK8vGcH-WAiQ4kZ6f2mViUjaM)
> 
> 感觉应该是 Intel 调整了 GitHub 的仓库，导致原来的这个地址发生了变化。

看到 envoy 上游仓库的后续版本已经调整了这个 repo 的指向。我们也看一下。

**Comment by bergen4** [comment]
目前构建发现的几个问题
1、构建build-gateway-local 中com_googlesource_googleurl的checksum错误
2、构建build-envoy中com_github_intel_ipp_crypto_crypto_mb的checksum错误
3、com_github_intel_ipp_crypto_crypto_mb的strip_prefix错误

几个注意点
1、make不能带BUILD-WITH-CONTAINER=1参数
2、必须要科学上网才能构建成功

**Comment by CH3CHO** [comment]
> 目前构建发现的几个问题 1、构建build-gateway-local 中com_googlesource_googleurl的checksum错误 2、构建build-envoy中com_github_intel_ipp_crypto_crypto_mb的checksum错误 3、com_github_intel_ipp_crypto_crypto_mb的strip_prefix错误
> 
> 几个注意点 1、make不能带BUILD-WITH-CONTAINER=1参数 2、必须要科学上网才能构建成功

依赖版本的问题我们看一下。 @johnlanni

**Comment by CH3CHO** [comment]
https://github.com/higress-group/envoy/pull/2 将修复这个问题

**Comment by bergen4** [comment]
再请问一下，我把envoy fork出来在1.27分支或者新分支修改了上面说的问题，再重新clone higress仓库，并修改.gitmodules的envoy仓库url和分支，然后执行make build-envoy，但是clone出来的envoy子模块还是1.27的旧版本，这是什么原因呢
![QQ_1729078558375](https://github.com/user-attachments/assets/10171501-380c-4002-a9de-cfe48aa65357)
![QQ_1729078894804](https://github.com/user-attachments/assets/ec91327a-8512-4421-a226-71e2cc4badd1)

**Comment by bergen4** [comment]
> 再请问一下，我把envoy fork出来在1.27分支或者新分支修改了上面说的问题，再重新clone higress仓库，并修改.gitmodules的envoy仓库url和分支，然后执行make build-envoy，但是clone出来的envoy子模块还是1.27的旧版本，这是什么原因呢 ![QQ_1729078558375](https://private-user-images.githubusercontent.com/10844865/377034846-10171501-380c-4002-a9de-cfe48aa65357.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwNzkyMTQsIm5iZiI6MTcyOTA3ODkxNCwicGF0aCI6Ii8xMDg0NDg2NS8zNzcwMzQ4NDYtMTAxNzE1MDEtMzgwYy00MDAyLWE5ZGUtY2ZlNDhhYTY1MzU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE2VDExNDE1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwOWJkOTlkNTYwZTc1ZTExNGIxOWY2MWRmNjFmOTkxYzEwODM1NTA1MjJhMDI4Y2Q1YmRhNTMyZDNiMzdmZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xzos7_1-jIa7on9gp920twIh-LGzGZTOBd5gyo10VCE) ![QQ_1729078894804](https://private-user-images.githubusercontent.com/10844865/377035204-ec91327a-8512-4421-a226-71e2cc4badd1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwNzkyMTQsIm5iZiI6MTcyOTA3ODkxNCwicGF0aCI6Ii8xMDg0NDg2NS8zNzcwMzUyMDQtZWM5MTMyN2EtODUxMi00NDIxLWEyMjYtNzFlMmNjNGJhZGQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE2VDExNDE1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3YTMzNmMwYmE0NzM4ZDk5YzY4ZGEwMzEyNzI5MGQyOTQ1NmRmNjc4YjZiNDk3ZmNmNzg4YjBmMTE0ZDJkOTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-0Z7hvE348fLaSF5wFc7eVVM8AZMpUFiBH1OqDkMlSw)

仓库地址是对了，但是分支和版本还是指向1.27的b3541845c1，改变不了
![QQ_1729078958145](https://github.com/user-attachments/assets/0f4555c9-7841-4b7b-a82a-e293c2fa3776)

**Comment by CH3CHO** [comment]
因为这个 commit 信息其实记录在主仓库里的

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年10月16日 19:44 |
| 收件人 | alibaba/higress ***@***.***> |
| 抄送人 | Kent ***@***.***>,
Assign ***@***.***> |
| 主题 | Re: [alibaba/higress] 容器构建higress时会报 run.sh找不到错误 (Issue #1388) |

再请问一下，我把envoy fork出来在1.27分支或者新分支修改了上面说的问题，再重新clone higress仓库，并修改.gitmodules的envoy仓库url和分支，然后执行make build-envoy，但是clone出来的envoy子模块还是1.27的旧版本，这是什么原因呢

仓库地址是对了，但是分支和版本还是指向1.27的b3541845c1，改变不了
QQ_1729078958145.png (view on web)

**Comment by bergen4** [comment]
> 再请问一下，我把envoy fork出来在1.27分支或者新分支修改了上面说的问题，再重新clone higress仓库，并修改.gitmodules的envoy仓库url和分支，然后执行make build-envoy，但是clone出来的envoy子模块还是1.27的旧版本，这是什么原因呢 ![QQ_1729078558375](https://private-user-images.githubusercontent.com/10844865/377034846-10171501-380c-4002-a9de-cfe48aa65357.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwNzkyMTQsIm5iZiI6MTcyOTA3ODkxNCwicGF0aCI6Ii8xMDg0NDg2NS8zNzcwMzQ4NDYtMTAxNzE1MDEtMzgwYy00MDAyLWE5ZGUtY2ZlNDhhYTY1MzU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE2VDExNDE1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwOWJkOTlkNTYwZTc1ZTExNGIxOWY2MWRmNjFmOTkxYzEwODM1NTA1MjJhMDI4Y2Q1YmRhNTMyZDNiMzdmZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xzos7_1-jIa7on9gp920twIh-LGzGZTOBd5gyo10VCE) ![QQ_1729078894804](https://private-user-images.githubusercontent.com/10844865/377035204-ec91327a-8512-4421-a226-71e2cc4badd1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwNzkyMTQsIm5iZiI6MTcyOTA3ODkxNCwicGF0aCI6Ii8xMDg0NDg2NS8zNzcwMzUyMDQtZWM5MTMyN2EtODUxMi00NDIxLWEyMjYtNzFlMmNjNGJhZGQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE2VDExNDE1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3YTMzNmMwYmE0NzM4ZDk5YzY4ZGEwMzEyNzI5MGQyOTQ1NmRmNjc4YjZiNDk3ZmNmNzg4YjBmMTE0ZDJkOTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-0Z7hvE348fLaSF5wFc7eVVM8AZMpUFiBH1OqDkMlSw)

仓库地址是对了，但是分支和版本还是指向1.27的b3541845c1，改变不了
![QQ_1729079157815](https://github.com/user-attachments/assets/b4e0f71a-f95d-42e4-9683-bc2ea8ff40d6)

**Comment by bergen4** [comment]
> 因为这个 commit 信息其实记录在主仓库里的
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 发送日期 | 2024年10月16日 19:44 | | 收件人 | alibaba/higress ***@***.***> | | 抄送人 | Kent ***@***.***>, Assign ***@***.***> | | 主题 | Re: [alibaba/higress] 容器构建higress时会报 run.sh找不到错误 (Issue #1388) | 再请问一下，我把envoy fork出来在1.27分支或者新分支修改了上面说的问题，再重新clone higress仓库，并修改.gitmodules的envoy仓库url和分支，然后执行make build-envoy，但是clone出来的envoy子模块还是1.27的旧版本，这是什么原因呢 仓库地址是对了，但是分支和版本还是指向1.27的b3541845c1，改变不了 QQ_1729078958145.png (view on web) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were assigned.Message ID: ***@***.***>

在哪里呢，如何修改指向最新的envoy版本

**Comment by bergen4** [comment]
我需要对envoy做二次开发
