### ISSUE TITLE
wasm-rust支持tick事件吗

### ISSUE THREAD

**Issue by w7team** [alibaba/higress#1390]
目前插件里有个场景需要用到异步处理，咨询了一下，可以使用tick事件。但是目前只看到go的sdk支持，rust可以支持一下吗？

**Comment by johnlanni** [comment]
cc @007gzs

**Comment by 007gzs** [comment]
https://github.com/proxy-wasm/proxy-wasm-rust-sdk/blob/main/examples/hello_world/src/lib.rs

**Comment by CH3CHO** [comment]
> https://github.com/proxy-wasm/proxy-wasm-rust-sdk/blob/main/examples/hello_world/src/lib.rs

@w7team 请问这个 sample 可以满足需求吗？

**Comment by w7team** [comment]
目前rust第一版插件开发完成了，第二步支持异步处理的还在排期，等我们使用有问题了再来反馈

**Comment by CH3CHO** [comment]
> 目前rust第一版插件开发完成了，第二步支持异步处理的还在排期，等我们使用有问题了再来反馈

那这个 issue 可以先关闭吗？

**Comment by w7team** [comment]
> > 目前rust第一版插件开发完成了，第二步支持异步处理的还在排期，等我们使用有问题了再来反馈
> 
> 那这个 issue 可以先关闭吗？

可以
