### ISSUE TITLE
higress-console监控对接victoria-metrics没有数据

### ISSUE THREAD

**Issue by wgh9626** [alibaba/higress#1396]
环境：higress是2.0.0版本，vm版本是latest，vmagent添加了higress-gateway的job，配置了relabel，grafana也修改了ini。添加了https://grafana.com/grafana/dashboards/17998-higress-dashboard/ 这个dashboard。

问题：gateway变量是没有值的，导致很多项都没有数据。

![image](https://github.com/user-attachments/assets/6c23460a-3ed3-4c1c-b282-446162d9cd94)

gateway用的变量中没有higress这个标签。

![image](https://github.com/user-attachments/assets/92d7367f-d702-4311-9b92-c772d2a9ffb1)

再比如QPS中cluster_name我这里是这种格式的，也匹配不上 `outbound_([0-9]+)_(.*)_(.*)$`

![image](https://github.com/user-attachments/assets/00397690-c715-4c9f-b6c1-84e8647d864a)

还有Upstream Success Rate中 `envoy_cluster_upstream_rq`这个metrics response_code 只有2xx的

![image](https://github.com/user-attachments/assets/5d5bf887-4dc8-4328-bedf-6e9c9ac6ee9d)

是我版本问题，还是对接的方式不对应该用VMPodScrape，还是哪里的问题？

**Comment by wgh9626** [comment]
> 你直接请求 gateway 的 prometheus 接口看看原始数据呢？

也是没有的
![image](https://github.com/user-attachments/assets/23574f06-7424-43a8-9cfd-221c0dc3d407)

**Comment by CH3CHO** [comment]
> > 你直接请求 gateway 的 prometheus 接口看看原始数据呢？
> 
> 也是没有的 ![image](https://private-user-images.githubusercontent.com/47957489/376963586-23574f06-7424-43a8-9cfd-221c0dc3d407.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwNjgzNTcsIm5iZiI6MTcyOTA2ODA1NywicGF0aCI6Ii80Nzk1NzQ4OS8zNzY5NjM1ODYtMjM1NzRmMDYtNzQyNC00M2E4LTljZmQtMjIxYzBkYzNkNDA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE2VDA4NDA1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzMDlkNzg5M2MyMzMwODM3N2JmMzRjNGEwYjE0YWViMTg3OGI1ZTkxYTQzZDVkOWQ2ZmU3MTBhMzQwYjdmNzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.MZxxJUtj967jTYnHEZ7kxA91R1JaASEodSofIj8QHmM)

那这个就是 envoy 本身数据的问题了。请 @johnlanni 看一下。

**Comment by johnlanni** [comment]
这个dashboard好像不是最新的，看下这个呢：https://github.com/higress-group/higress-console/blob/c22a01810b362e7349bb2a8157e9f993783219a8/backend/console/src/main/resources/dashboard/main.json

**Comment by johnlanni** [comment]
prometheus 是没问题的，[demo](http://demo.higress.io/dashboard) 可以看到：
![image](https://github.com/user-attachments/assets/c463ea29-c130-4cb7-8df2-3bb8b7b89ad9)

**Comment by johnlanni** [comment]
![image](https://github.com/user-attachments/assets/44f596a0-56c8-47d0-bf29-709090cbefe9)
当前prometheus的配置是会把所有pod的label加进去的，你看看vm上是不是也可以这么配置

**Comment by wgh9626** [comment]
> ![image](https://private-user-images.githubusercontent.com/6763318/377284656-44f596a0-56c8-47d0-bf29-709090cbefe9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxNDYyMzQsIm5iZiI6MTcyOTE0NTkzNCwicGF0aCI6Ii82NzYzMzE4LzM3NzI4NDY1Ni00NGY1OTZhMC01NmM4LTQ3ZDAtYmYyOS03MDkwOTBjYmVmZTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTdUMDYxODU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2ZkZGUzMGU4ODYzZmJiN2EwZDhiN2Y5ZmJhZTExMzdmZjc3OWI0NmQyNWZhYTNmMjQ1YTMwMjMyYzAxZjQ4NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.11RMbGiQ528S-_IDP1XPCeQsJoudpNZ7xTD4oD5XJLw) 当前prometheus的配置是会把所有pod的label加进去的，你看看vm上是不是也可以这么配置

我重新加了一下pod监控，现在可以了谢谢。
