### ISSUE TITLE
MountVolume.SetUp failed for volume "higress-ca-root-cert" : configmap "higress-ca-root-cert" not found

### ISSUE THREAD

**Issue by C-L-STARK** [alibaba/higress#1401]
MountVolume.SetUp failed for volume "higress-ca-root-cert" : configmap "higress-ca-root-cert" not found

应该如何排查呢？

**Comment by CH3CHO** [comment]
看一下 controller pod 有没有正常启动

---- Replied Message ----
| From | ***@***.***> |
| Date | 10/17/2024 05:09 |
| To | alibaba/higress ***@***.***> |
| Cc | Subscribed ***@***.***> |
| Subject | [alibaba/higress] MountVolume.SetUp failed for volume "higress-ca-root-cert" : configmap "higress-ca-root-cert" not found (Issue #1401) |

MountVolume.SetUp failed for volume "higress-ca-root-cert" : configmap "higress-ca-root-cert" not found

应该如何排查呢？

**Comment by C-L-STARK** [comment]
谢谢回复，controller pod已经是启动状态；
Volume问题好像部署etcd也有问题，我先自己本地排查一下吧；多谢您。
