### ISSUE TITLE
2.0.0版本higress-gateway内存暴涨

### ISSUE THREAD

**Issue by bergen4** [alibaba/higress#1406]
把higress从1.3.6更新到最新的2.0.1,发现gateway启动不了OOM，查看内存是envoy消耗12G。
逐步降低gatewway版本，试用了2.0.0，1.4.2，发现内存是从2.0.0开始上涨的，1.4.2消耗内存只有700M
**2.0.0/2.0.1 版本**
![QQ_1729235083634](https://github.com/user-attachments/assets/304eb514-5e8f-4b4c-b987-b90326c21bc8)

**1.4.2版本**
![QQ_1729234757079](https://github.com/user-attachments/assets/c754c5fa-6e86-47fe-8ef9-e19ecb16d409)

**Comment by johnlanni** [comment]
@bergen4 是运行一段时间后上涨还是已启动就占用了这么多内存呢。另外你的配置有什么特殊的地方么，ingress数量有多少？

**Comment by johnlanni** [comment]
可以1.4.2和2.0.1分别进 higress-gateway 的容器执行一下 

1. curl localhost:15000/config_dump -o envoy_config
2. curl localhost:15000/stats/prometheus -o envoy_prom

把两个版本的 envoy_config 和 envoy_prom 分别发我看下

**Comment by bergen4** [comment]
[mem.tar.gz](https://github.com/user-attachments/files/17475714/mem.tar.gz)
两个版本的config和pro数据

**Comment by johnlanni** [comment]
有点奇怪，看配置就1w多路由，我这边测试2w多路由，higress-gateway的内存只有800多M
![image](https://github.com/user-attachments/assets/4c72d0f8-58f8-4267-9169-dcf484baa2d0)

**Comment by johnlanni** [comment]
进展：用户线下提供的 heap dump，从heap 看，实际tcmalloc只分配了不到700MB内存，目前怀疑是 tcp buffer 或者 lua filter 里的逻辑造成

**Comment by bergen4** [comment]
在测试环境单独测试filter的对内存的影响。

1、2.0.1版本
（1）卸载所有filter，启动10min后内存约占用700M
（2）每增加一个lua filter，增加内存2G左右
（3）增加非lua filter，对内存无影响

2、1.3.6版本
（1）卸载素有filter，启动10min后内存约占用270M
（2）每增加一个lua filter，内存增加内存约150M
（3）增加非lua filter，对内存无影响

基本可以得出新版本内存飙升的原因是lua filter导致的。另外，没有filter的情况下，新版本的内存占用也有上升了不少，不清楚上涨是不是线性增长(700/270=2.6）

**Comment by johnlanni** [comment]
@bergen4 不是线性增长，1.3.6的版本里envoy还是用的去除符号的版本，所以内存比较小，但出问题不容易定位。对性能是没有影响的。

**Comment by johnlanni** [comment]
> 每增加一个lua filter，内存增加2G
@bergen4 这个filter如果不做任何事情，逻辑都是bypass，也会导致内存增加2G吗

**Comment by bergen4** [comment]
> > 每增加一个lua filter，内存增加2G
> 
> @bergen4 这个filter如果不做任何事情，逻辑都是bypass，也会导致内存增加2G吗

类似这样替换header，很简单的逻辑
![QQ_1730184379823](https://github.com/user-attachments/assets/21908c8a-5e69-489e-8cac-b164a520171c)

**Comment by johnlanni** [comment]
@bergen4 改成bypass的逻辑试一下看看是否对内存有影响呢，比如函数里只打印一行日志

**Comment by johnlanni** [comment]
@bergen4 有空的话可以用纯envoy + config.yaml 的方式测一下，确认是lua filter的问题，可以给envoy社区提个issue

**Comment by bergen4** [comment]
谢谢
