### ISSUE TITLE
vm监控缺失

### ISSUE THREAD

**Issue by cuisongliu** [alibaba/higress#1418]
我使用的demo的grafana表盘 我看有个下拉框是gateway 在prometheus指标是正常的。
<img width="1843" alt="image" src="https://github.com/user-attachments/assets/b28f65bf-9454-4e87-b500-71f4f8d8c11f">

但是我切换vm 使用发现指标有缺失

<img width="1834" alt="image" src="https://github.com/user-attachments/assets/cdc22acf-3e6a-4aa5-a9ca-80a9f3c9e4ff">

**Comment by CH3CHO** [comment]
要看一下我们内置的 Prometheus 采集配置，有没有把 Pod 所有的 Label 都采了

**Comment by cuisongliu** [comment]
> 要看一下我们内置的 Prometheus 采集配置，有没有把 Pod 所有的 Label 都采了

在prometheus是没问题的 但是切换victoria-metrics-k8s-stack 就不能用了

**Comment by CH3CHO** [comment]
> > 要看一下我们内置的 Prometheus 采集配置，有没有把 Pod 所有的 Label 都采了
> 
> 在prometheus是没问题的 但是切换victoria-metrics-k8s-stack 就不能用了

所以我的意思是对比一下 VM 和 Prom 的采集配置，二者采集的数据一样吗？

**Comment by wgh9626** [comment]
vm监控higress-gateway pod的配置有问题

**Comment by cuisongliu** [comment]
> vm监控higress

求指导，是得relabel 么

**Comment by CH3CHO** [comment]
参考一下：https://github.com/higress-group/higress-console/blob/main/helm/templates/prometheus.yaml#L35

**Comment by cuisongliu** [comment]
> vm监控higress-gateway pod的配置有问题


求指导，是得relabel 么

**Comment by CH3CHO** [comment]
请问是解决了吗？ @cuisongliu
