### ISSUE TITLE
请问下higress的gateway是如何使用插件的镜像的??

### ISSUE THREAD

**Issue by ilovedumplings** [alibaba/higress#1425]
## Why do you need it?
看gateway日志,启用插件的时候,gateway回去拉取对应插件的镜像,请问这些镜像会用容器启动嘛?

## How could it be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by CH3CHO** [comment]
不会用容器启动。gateway 会解压镜像，拿到里面的 Wasm 文件，加载到内存里给他创建一个 VM 来运行。

**Comment by ilovedumplings** [comment]
> 不会用容器启动。gateway 会解压镜像，拿到里面的 Wasm 文件，加载到内存里给他创建一个 VM 来运行。

maintainer的含金量
