### ISSUE TITLE
关于响应转换的问题

### ISSUE THREAD

**Issue by ilovedumplings** [alibaba/higress#1433]
## Why do you need it?
![image](https://github.com/user-attachments/assets/e683a0c8-4355-4d23-8507-336eef6b8d66)

我想做一个功能,用于处理http code想要将非200的code封装成200,然后response中封装一下自定义的异常码,请问我们支持吗

## How could it be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by ilovedumplings** [comment]
@CH3CHO 老哥,请问这个支持不

**Comment by CH3CHO** [comment]
wasm插件应该可以做的

**Comment by ilovedumplings** [comment]
> wasm

请求响应转换那个插件码?

**Comment by CH3CHO** [comment]
> > wasm
> 
> 请求响应转换那个插件码?

这个我不太确定。但至少自己写代码是能做的。。。

**Comment by ilovedumplings** [comment]
> > > wasm
> > 
> > 
> > 请求响应转换那个插件码?
> 
> 这个我不太确定。但至少自己写代码是能做的。。。

自定义应答可以
