### ISSUE TITLE
Higress插件是否针对流式响应生效

### ISSUE THREAD

**Issue by ilovedumplings** [alibaba/higress#1437]
## Why do you need it?
现在用于生产的模型基本都是流式的返回,所以想问下,配额,token这些插件针对流式响应是否是生效的?测了一下似乎是没生效....

## How could it be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by johnlanni** [comment]
这个肯定是生效的，不过目前只支持 openai 协议

**Comment by jizhuozhi** [comment]
目前Go和Rust都是支持流式处理的，其中Rust已经对SSE协议的解析做了标准化（[event_stream.rs](https://github.com/alibaba/higress/tree/main/plugins/wasm-rust/example/sse-timing)），不过要实现你的目的的话可能需要定义清楚token的分词规则，对接不同大模型vendor的话很难得到相同的token解析，可能需要higress单独维护一个query  analyzer去做归一化

**Comment by ilovedumplings** [comment]
> token

我看openai的流式响应协议里面,似乎没有对token的属性,所以,在quota和token中,应该是不支持的openai的流式响应吧?

data: {"id":"cmpl-abc123xyz","object":"text_completion","created":1698765432,"model":"text-davinci-003","choices":[{"text":"机器学习是","index":0,"logprobs":null,"finish_reason":null}]}

data: {"id":"cmpl-abc123xyz","object":"text_completion","created":1698765433,"model":"text-davinci-003","choices":[{"text":"一种人工智能方法","index":0,"logprobs":null,"finish_reason":null}]}

data: {"id":"cmpl-abc123xyz","object":"text_completion","created":1698765434,"model":"text-davinci-003","choices":[{"text":"...","index":0,"logprobs":null,"finish_reason":"stop"}]}

data: [DONE]

**Comment by johnlanni** [comment]
支持的，有个参数加上就会有了

**Comment by ilovedumplings** [comment]
> query analyzer

stream=true是设置流式响应,但是响应结果里是没有token属性的,openai协议里好像就是这么搞得

**Comment by johnlanni** [comment]
stream_options 里有个 include_usage，通过 AI Proxy 代理，会自动设置上这个参数

**Comment by ilovedumplings** [comment]
> AI Proxy

let me try ...

**Comment by ilovedumplings** [comment]
> usage

我没太明白这个配置老哥...stream_options是哪里的参数?

**Comment by johnlanni** [comment]
@ilovedumplings 你可以看下 openai 的 api 文档，搜索一下这个 stream_options

**Comment by ilovedumplings** [comment]
> stream_options

好,我刚才找了个中文得没找到..我再找找看

**Comment by ilovedumplings** [comment]
> stream_options

看到了,感谢
