### ISSUE TITLE
AI 缓存插件对接 Cohere https://docs.cohere.com/reference/embed

### ISSUE THREAD

**Issue by CH3CHO** [alibaba/higress#1449]

**Comment by ayanami-desu** [comment]
你好，我想认领这个任务

**Comment by CH3CHO** [comment]
可以的

**Comment by ayanami-desu** [comment]
go版本go1.23.3 linux/amd64，tinygo版本0.34.0 linux/amd64 (using go version go1.23.3 and LLVM version 18.1.2)。编译时出现如下错误
![image](https://github.com/user-attachments/assets/32386f7a-763d-4d79-9768-ac72513088fa)
