### ISSUE TITLE
config可以调整成*PluginConfig类型？方便修改一些数据

### ISSUE THREAD

**Issue by titrxw** [alibaba/higress#1474]
https://github.com/alibaba/higress/blob/c1f2504e8781a2191d454b5486841900439d8922/plugins/wasm-go/pkg/wrapper/plugin_wrapper.go#L63

**Comment by CH3CHO** [comment]
根据Header修改Config？这是什么场景下的需求？

**Comment by CH3CHO** [comment]
> 就一个flag标记变量的作用，我放context试试

如果是请求粒度的，放context吧
