### ISSUE TITLE
当启动监控配置的时候,网关服务中的promtail这个pod一直起不来

### ISSUE THREAD

**Issue by ilovedumplings** [alibaba/higress#1478]
![99cdd0e0ce272be9dc5e10db9101cf8](https://github.com/user-attachments/assets/a6f8eb32-6c62-475a-b363-242d13876180)

报错缺失文件

**Comment by johnlanni** [comment]
@CH3CHO 已知问题，目前不会创建一个空的 access.log，必须要请求进来才会产生，这样 promtail 就 ready 不了

**Comment by CH3CHO** [comment]
> @CH3CHO 已知问题，目前不会创建一个空的 access.log，必须要请求进来才会产生，这样 promtail 就 ready 不了

原因找到了，后面我们修一下

**Comment by ilovedumplings** [comment]
> 你是在什么环境下安装的 Higress？

我是离线安装的,现在还遇到了一个问题,就是启动apigateway的时候,一直找不到 higress-ca-root-cert的cm,这个是出现我多次安装删除higress-system之后....,我把helm包下载下来,改了镜像的tag之后安装的

**Comment by ilovedumplings** [comment]
> > 你是在什么环境下安装的 Higress？
> 
> 我是离线安装的,现在还遇到了一个问题,就是启动apigateway的时候,一直找不到 higress-ca-root-cert的cm,这个是出现我多次安装删除higress-system之后....,我把helm包下载下来,改了镜像的tag之后安装的

之后我在线安装,同样找不到对应的cm

**Comment by CH3CHO** [comment]
> 我是离线安装的,现在还遇到了一个问题,就是启动apigateway的时候,一直找不到 higress-ca-root-cert的cm,这个是出现我多次安装删除higress-system之后....,我把helm包下载下来,改了镜像的tag之后安装的

这个问题之前也有人反馈过，但尚未找到稳定重现的办法。我们后续会持续关注。

**Comment by ilovedumplings** [comment]
> > 我是离线安装的,现在还遇到了一个问题,就是启动apigateway的时候,一直找不到 higress-ca-root-cert的cm,这个是出现我多次安装删除higress-system之后....,我把helm包下载下来,改了镜像的tag之后安装的
> 
> 这个问题之前也有人反馈过，但尚未找到稳定重现的办法。我们后续会持续关注。

多删除几次ns,应该就能复现...

**Comment by johnlanni** [comment]
@ilovedumplings 这个cm是 higress-controller 创建的，通过重启 higress-controller 有用吗？

**Comment by johnlanni** [comment]
> 多删除几次ns,应该就能复现...

删除 ns 就是重新安装，我安装过多次没有复现这个问题，而且这段逻辑也没有这种概率性问题。

唯一可能跟你安装环境相关的是，这里通过环境变量 POD_NAMESPACE 来获取当前安装的 ns，如果你的 K8s 不是标准发行版，没有这个环境变量，可能会有问题：


https://github.com/higress-group/istio/blob/istio-1.19/pilot/pkg/serviceregistry/kube/controller/namespacecontroller.go

**Comment by johnlanni** [comment]
2.0.3 这个问题已经解决了
