### ISSUE TITLE
使用基于Key集群限流插件报错

### ISSUE THREAD

**Issue by bianshuangwei** [alibaba/higress#1486]
Higress版本：2.0.1
部署方式：单机部署
部署服务器：centos7
基于Key集群限流插件配置详情：
redis:
  password: "capitek"
  service_name: "172.18.2.27"
  service_port: 6379
#  username: "capitek"
rule_items:
- limit_by_per_ip: "from-header-x-forwarded-for"
  limit_keys:
  - key: "172.21.0.90"
    query_per_day: 3
  - key: "172.20.22.0/24"
    query_per_day: 5
  - key: "0.0.0.0/0"
    query_per_day: 6
rule_name: "default_rule"
show_limit_quota_header: true

redis情况说明：单节点redis，可以正常使用。配置的redis的service name为redis的ip地址，还尝试在域名中配置了此ip的dns，调用短的host添加了ip和域名的映射，依然不可用，报错信息如下：
gateway-1  | 2024-11-07T07:57:44.114044Z        info    wasm    fetching image plugins/cluster-key-rate-limit from registry higress-registry.cn-hangzhou.cr.aliyuncs.com with tag latest
gateway-1  | 2024-11-07T07:57:46.849504Z        critical        envoy wasm external/envoy/source/extensions/common/wasm/context.cc:1396 wasm log: failed to init redis: error status returned by host: bad argument     thread=25
gateway-1  | 2024-11-07T07:57:46.849626Z        warning envoy wasm external/envoy/source/extensions/common/wasm/context.cc:1390 wasm log: [cluster-key-rate-limit] parse rule config failed: error status returned by host: bad argument        thread=25
gateway-1  | 2024-11-07T07:57:46.849637Z        error   envoy wasm external/envoy/source/extensions/common/wasm/wasm.cc:151     Wasm VM failed Failed to configure base Wasm plugin     thread=25
gateway-1  | 2024-11-07T07:57:46.851424Z        critical        envoy wasm external/envoy/source/extensions/common/wasm/wasm.cc:547     Plugin configured to fail closed failed to load thread=25
gateway-1  | 2024-11-07T07:57:46.851439Z        critical        envoy wasm external/envoy/source/extensions/common/wasm/wasm.cc:547     Plugin configured to fail closed failed to load thread=34
gateway-1  | 2024-11-07T07:57:46.851479Z        critical        envoy wasm external/envoy/source/extensions/common/wasm/wasm.cc:547     Plugin configured to fail closed failed to load thread=35
gateway-1  | 2024-11-07T07:57:46.851480Z        critical        envoy wasm external/envoy/source/extensions/common/wasm/wasm.cc:547     Plugin configured to fail closed failed to load thread=33
gateway-1  | 2024-11-07T07:57:46.851505Z        critical        envoy wasm external/envoy/source/extensions/common/wasm/wasm.cc:547     Plugin configured to fail closed failed to load thread=32

发生此问题后，有一个致命问题：开启此插件配置之前，路由调用成功，配置出现上述错误后，所有路由（不止配置插件的路由）调用都会失败，删除重新添加路由依然调用失败，重启higress（shutdown.sh后startup.sh）路由依然调用依然返回500错误，只有重新configure（清空重新配置启动）后重新配置路由才可调用。这个是个致命问题，一个插件的配置错误，导致整个higress的路由不可访问。

**Comment by johnlanni** [comment]
需要给wasmplugin的 failStrategy设置为 FAIL_OPEN，这样插件配置出错就会 fail over，新版本控制台下发已经做了调整，建议你先手动配置下，参考 istio 的文档说明：
https://istio.io/latest/docs/reference/config/proxy_extensions/wasm-plugin/#FailStrategy

**Comment by johnlanni** [comment]
parse rule config failed: error status returned by host: bad argument

这个报错就是服务发现不了，redis 的 service name 配的不对，可以看下这个插件的[文档](https://higress.io/docs/latest/plugins/traffic/cluster-key-rate-limit/)：
![image](https://github.com/user-attachments/assets/a7c44ec8-a7a1-40d6-a207-1318ece086a1)

**Comment by bianshuangwei** [comment]
> parse rule config failed: error status returned by host: bad argument
> 
> 这个报错就是服务发现不了，redis 的 service name 配的不对，可以看下这个插件的[文档](https://higress.io/docs/latest/plugins/traffic/cluster-key-rate-limit/)： ![image](https://private-user-images.githubusercontent.com/6763318/383876917-a7c44ec8-a7a1-40d6-a207-1318ece086a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5Njg2NzEsIm5iZiI6MTczMDk2ODM3MSwicGF0aCI6Ii82NzYzMzE4LzM4Mzg3NjkxNy1hN2M0NGVjOC1hN2ExLTQwZDYtYTIwNy0xMzE4ZWNlMDg2YTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDdUMDgzMjUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2YyZGMyNWY2ZWQ4MWVkZmNkODFmN2Y4ZjI0Mjc2ODBmZGE0ZjNlNDNkODgwZDFhZDRmNmRkMTgxYTAxZjViYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.bA2AYxSoSKt3Soen1LmqOFKl31ildfntOqDx3sceX-Q)

你好，我测试环境的服务器没有域名，只有ip。redis是直接部署在虚拟机上的，不是K8S或者docker部署的，redis主机的hostname是capitek100，在higress的域名配置里配置了域名prd100.cn，在服务器的/etc/hosts里做了ip和域名的映射。我将redis.service_name修改为：capitek100.prd100.cn  结果测试还是不行。路由对应的微服务直接部署在虚拟机上，非容器化部署。这种情况有办法配置redis的service name吗？

**Comment by johnlanni** [comment]
@bianshuangwei 你的服务时通过控制台加上的吗，控制台的服务列表里的服务名字就是这个service_name

**Comment by bianshuangwei** [comment]
> @bianshuangwei 你的服务是通过控制台加上的吗，控制台的服务列表里的服务名字就是这个service_name

服务是通过控制台加上去的，配置的是nacos2.0作为服务来源。redis的服务通过配置固定地址，将redis注册到服务列表里，redis的服务名称显示是：redis.static，在路由的策略“基于Key集群限流”中redis的service_name设置为redis.static。配置如下：

redis:
  password: "capitek"
  service_name: "redis.static"
  service_port: 6379

这样配置后还是报错：
gateway-1  | 2024-11-08T07:07:50.717368Z        critical        envoy wasm external/envoy/source/extensions/common/wasm/context.cc:1396 wasm log: failed to init redis: error status returned by host: bad argument     thread=23
gateway-1  | 2024-11-08T07:07:50.717403Z        warning envoy wasm external/envoy/source/extensions/common/wasm/context.cc:1390 wasm log: [cluster-key-rate-limit] parse rule config failed: error status returned by host: bad argument        thread=23

**Comment by johnlanni** [comment]
@bianshuangwei static service目前用的逻辑端口，service_port不用填，或者填80
