### ISSUE TITLE
基于Key限流 和 AI token 限流插件拓展

### ISSUE THREAD

**Issue by KingOfXi** [alibaba/higress#1498]
AI token限流  可以对每个apikey配置token  per  miniute 限流，不过可以在这基础上，对路由服务配置一个 总的tpm限流吗？
基于key限流 同理可以对每个key配置request  per miniute限流，需要在这基础上对路由服务配置一个总的rpm限流。

**Comment by johnlanni** [comment]
我理解就是不需要 limit_by_xxx，就是规则粒度的限流
