### ISSUE TITLE
--pass-authorization-header标志行为和oauth2proxy主干不一致

### ISSUE THREAD

**Issue by ningpengtao-coder** [alibaba/higress#1501]
目前oauth2proxy--pass-authorization-header标志传递的是AccessToken，按照原oauth2proxy项目的含义应该是传递IDToken。
https://github.com/higress-group/oauth2-proxy/blob/v1.0.0/oauthproxy.go#L415

**Comment by johnlanni** [comment]
cc @rinfx @Jing-ze

**Comment by Jing-ze** [comment]
应该修改为：

**Comment by johnlanni** [comment]
@Jing-ze 已经合并，可以再更新下插件的go mod依赖
