### ISSUE TITLE
Higress版本升级后插件不生效了

### ISSUE THREAD

**Issue by bianshuangwei** [alibaba/higress#1517]
[gateway.log](https://github.com/user-attachments/files/17797045/gateway.log)
过程：Higress单机部署，使用file存储配置文件，将higress由2.0.1版本升级到2.0.3，将原来升级前higress的配置文件拷贝到新版本的配置文件目录下，可以看到原来配置的服务、路由和插件配置
结果：调用某个路由，发现原来配置的Header设置，发现配置不生效（设置请求添加特定header）
尝试：尝试了其他插件，例如跨域、基于Key集群限流，HMAC认证，升级前这些插件都是可以生效的，升级后都失效了。
上周五下班前升级的，今天下午调用接口发现问题，higress升级后的完整日志如下：
[gateway.log](https://github.com/user-attachments/files/17797052/gateway.log)
header设置插件的配置内容为：请求中添加x-customs-user
基于Key集群限流的配置如下：
redis:
  password: "capitek"
  service_name: "redis.static"
rule_items:
- limit_by_per_ip: "from-header-x-forwarded-for"
  limit_keys:
  - key: "172.21.0.90"
    query_per_day: 3
  - key: "172.20.22.0/24"
    query_per_day: 5
  - key: "0.0.0.0/0"
    query_per_day: 6
rule_name: "default_rule"
show_limit_quota_header: true
HMAC的设置如下：
consumers:
- key: "xcakey1"
  name: "consumer1"
  secret: "xcasecret1"
- key: "xcakey2"
  name: "consumer2"
  secret: "xcasecret2"
global_auth: false

allow:
- consumer1
还尝试了几个组件，都不生效，具体配置就先不贴了。

**Comment by johnlanni** [comment]
gateway-1  | 2024-11-15T07:56:26.933175Z        error   envoy wasm external/envoy/source/extensions/common/wasm/context.cc:1393 wasm log higress-system.opa-1.0.0: [opa] client opa fail error status returned by host: bad argument    thread=59

opa 插件配置解析失败了，看上去应该是服务发现不了，你看看opa插件的service name配置是否有问题。

当 wasm 插件配置解析失败，会使得后续 ECDS 被拒绝，现象就是新的插件配置无法下发。

**Comment by bianshuangwei** [comment]
> gateway-1 | 2024-11-15T07:56:26.933175Z error envoy wasm external/envoy/source/extensions/common/wasm/context.cc:1393 wasm log higress-system.opa-1.0.0: [opa] client opa fail error status returned by host: bad argument thread=59
> 
> opa 插件配置解析失败了，看上去应该是服务发现不了，你看看opa插件的service name配置是否有问题。
> 
> 当 wasm 插件配置解析失败，会使得后续 ECDS 被拒绝，现象就是新的插件配置无法下发。

我刚检查了一下，OPA我已经disable了，全局和所有路由下都disable了，这种情况下我怎么解决这个问题呢？我当初尝试了一下OPA，那个测试的路由已经被我删掉了

**Comment by johnlanni** [comment]
看了下是新版本的 higress console 引入的问题，缺少了全局插件关闭的配置，导致目前下发了一个空的配置文件。我们会修复一下。可以尝试将 higress console 的镜像版本单独降级到之前的版本

**Comment by johnlanni** [comment]
可以先单独将 console 的镜像升级到 1.4.6，higress 这边的版本会稍晚一些再发布
