### ISSUE TITLE
Implement one-click building&deploying of wasm plugin oci image

### ISSUE THREAD

**Issue by johnlanni** [alibaba/higress#152]
## Why do you need it?

At present, there are many steps to build&deploy a wasm plugin.

https://github.com/alibaba/higress/blob/main/plugins/wasm-go/README.md

## How could it be?
- [x] Implement one-click build.
- [ ] Implement a CLI to build&deploy the wasm code by one-click.

**Comment by dspo** [comment]
可以给我

**Comment by johnlanni** [comment]
hgctl plugin alread support it.
