### ISSUE TITLE
基于key集群限流插件开启不生效

### ISSUE THREAD

**Issue by KingOfXi** [alibaba/higress#1523]
### Ⅰ. Issue Description
在higress-console（1.4.6） 控制台开启 基于key集群限流插件，higress-gateway（2.0.0）里可以看到有从仓库拉取插件镜像的日志，如下图所示。
![企业微信截图_17320052768721](https://github.com/user-attachments/assets/083978b6-3bc5-46b2-a74b-0dec899e6098)

执行kubectl get wasmplugins -n higress-system -o yaml 后附件如下
[wasm.txt](https://github.com/user-attachments/files/17812077/wasm.txt)
。
### Ⅱ. Describe what happened

往higress-gateway发请求，header里带上apikey:bbb ，但是在redis里没有看到有生成对应的key，请求能转发到下游且有返回，但是限流不会生效。
不过在其他的k8s集群（和上述的k8s集群版本相同）里，该插件功能可以奏效。

**Comment by CH3CHO** [comment]
图没出来

**Comment by KingOfXi** [comment]
higress-gateway没有其他日志了

**Comment by CH3CHO** [comment]
大概率是 redis 服务没下发下去。你 exec 到 gateway 容器里，curl http://localhost:15000/clusters 看看有没有名字里带 redis.static cluster。

**Comment by KingOfXi** [comment]
和CH3CHO讨论，发现 higress-gateway容器日志的route_name里的命名空间不是higress-system，由于没设置global.watchNamespace  （详情可见https://higress.io/docs/latest/ops/deploy-by-helm/ ），导致会监听所有命名空间下的ingress。其他命名空间里的ingress 和 console设置生成的ingress冲突，这会让console设置生成的ingress不生效。
