### ISSUE TITLE
外部redis服务读取不到

### ISSUE THREAD

**Issue by ilovedumplings** [alibaba/higress#1539]
我外部配置了一个redis.但是一致报错bad arguments ,我使用集群内部的redis是没问题的,请问一下我该如何排查,
我配置了外部redis的服务来源,
![1732433366186](https://github.com/user-attachments/assets/a53036fd-07ae-48f4-a342-1b82001f8958)
然后在路由中引入了redis，
![1732433398750](https://github.com/user-attachments/assets/7e568801-aafe-4b8f-b975-491983e078e6)
,在对应路由的插件中,使用的redis配置为
![1732433470926](https://github.com/user-attachments/assets/ba18de84-da15-4004-a64e-154442cfabdd)
但是代码报错
![image](https://github.com/user-attachments/assets/77533fe2-870a-4788-9aee-919b12b8cdc2)
下图为wasmPlugin配置插件
![image](https://github.com/user-attachments/assets/5d7d281d-726b-46e5-9e88-05c8be25f49f)
下图为apigatewayredis的配置
![image](https://github.com/user-attachments/assets/a1ef82a0-6eca-4e1c-aabb-67c2cdeeea0f)
@hanxiantao

**Comment by ilovedumplings** [comment]
我又额外加了个一个redis的域名解析的配置
![image](https://github.com/user-attachments/assets/d45b1903-7ffd-4a1e-99c9-a01da3e31ca9)
然后配置
![image](https://github.com/user-attachments/assets/dcefe49f-de8f-4011-8b61-e64186f9d404)
网关日志没有报错,但是加载的时候是有问题
![image](https://github.com/user-attachments/assets/9e58429e-2b10-44b5-8d87-03ded8d8573c)

**Comment by hanxiantao** [comment]
![image](https://github.com/user-attachments/assets/3c4f632d-a8c4-4fa4-aa32-10c0f1cb4fd1) 
已线下沟通解决，这里outbound的端口是80，插件配置的service_port改为80就可以了
