### ISSUE TITLE
请求内容带 + 加号时导致 AI 内容安全插件报错

### ISSUE THREAD

**Issue by mrhaoji** [alibaba/higress#1540]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via [ASRC](https://security.alibaba.com/)(Alibaba Security Response Center) where the issue will be triaged appropriately.**

- [x] I have searched the [issues](https://github.com/alibaba/higress/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
如果用户输入的内容是带 + 加号的，会出现往阿里内容安全服务那边走的时候，计算签名错误，导致“漏风”没有准确拦截。

### Ⅱ. Describe what happened
![CleanShot 2024-11-25 at 11 23 28@2x](https://github.com/user-attachments/assets/83c8946b-d340-47b5-a186-84fc42452402)

### Ⅲ. Describe what you expected to happen
正常处理特殊符号

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

直接用阿里内容安全官方的 SDK 示例代码测试“AA 事件”、“AA事件”、“AA+ 事件”均成功拦截

但是通过 Higress AI 内容安全插件“AA+ 事件”无法被拦截，从日志看出现下面截图的错误

### Ⅵ. Environment:

- Higress version:  
- OS :
- Others:

**Comment by CH3CHO** [comment]
请 @rinfx 看一下

**Comment by rinfx** [comment]
这个问题已经修复过了：#1394 #1473

**Comment by CH3CHO** [comment]
那我重新打个包

**Comment by CH3CHO** [comment]
镜像已更新，请验证

**Comment by mrhaoji** [comment]
已正常
