### ISSUE TITLE
ai-proxy minimax 渠道模型支持列表更新

### ISSUE THREAD

**Issue by pepesi** [alibaba/higress#1545]
ai-proxy minimax 渠道v2 和 pro支持模型列表是一致的，可以二选一支持
同时模型列表有更新，详情
https://platform.minimaxi.com/document/ChatCompletion%20v2
https://platform.minimaxi.com/document/ChatCompletion%20Pro

ai-proxy minimax provider 需要更新支持

**Comment by hanxiantao** [comment]
> ai-proxy minimax 渠道v2 和 pro支持模型列表是一致的，可以二选一支持 同时模型列表有更新，详情 https://platform.minimaxi.com/document/ChatCompletion%20v2 https://platform.minimaxi.com/document/ChatCompletion%20Pro
> 
> ai-proxy minimax provider 需要更新支持

minimax支持的模型更新后，目前无法从模型上区分，后续我准备在插件上新增一个配置字段，让用户自己选择是使用ChatCompletion Pro还是ChatCompletion v2

@pepesi 帮忙看下 如果没什么问题 我先按照这个方案更新下插件

**Comment by pepesi** [comment]
我自己目前改了一个，只是直接用了v2的，你这个更棒
