### ISSUE TITLE
frontend-gray 页面url参数中包含"."会被认为是文件url导致indexRouting规则失效

### ISSUE THREAD

**Issue by ahumyyu** [alibaba/higress#1548]
例如：
访问  /app1/xxx       路由到’/mfe/app1/{version}/index.html’
在访问  /app1/xxx?fileName=test.png 期望也路由到’/mfe/app1/{version}/index.html’
实际走到fileRouting路由策略里导致404

**Comment by johnlanni** [comment]
cc @heimanba

**Comment by heimanba** [comment]
已修复
