### ISSUE TITLE
在Nacos注销实例后，Higress仍然可以路由到应用实例

### ISSUE THREAD

**Issue by XavierGrool** [alibaba/higress#1566]
### Ⅰ. Issue Description
我使用了 Nacos 作为 Higress 的注册中心，并通过 Nacos 的 OpenAPI 的方式注册应用实例，实例的注册类型为持久化实例（ephemeral=false）

### Ⅱ. Describe what happened

  - 当 Nacos 的命名空间中只有一个 service 且该 service 内仅有一个实例时
    正确配置 McpBridge 和 Ingress 后，Higress 能正常路由到该实例
    但是当我通过 Nacos 的 OpenAPI 注销该实例后，Higress 仍然可以路由到该实例

  - 当 Nacos 的命名空间中只有一个 service 且该 service 内注册了两个实例（A 和 B）时
    正确配置 McpBridge 和 Ingress 后，Higress 能正常轮询两个实例
    下线/注销 其中一个实例（比如 A），Ingress 能立刻感知，并在后面只路由到 B
    但是如果此时把 B 也 下线/注销 掉，此时 Ingress 还是能路由到 B
    并在等待了相当长一段时间后（超过半个小时），Ingress 到 B 的路由还是通的

### Ⅲ. Describe what you expected to happen

我们预期的逻辑是：最后一个实例在 Nacos 注销后，Higress 应该返回 503，而非像现在这样仍然可以提供服务，否则也不能说它 注销/下线 了吧？

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. 在一个 k8s 集群中部署 Higress
2. 用三台虚拟机部署一个 Nacos 集群
3. 在另一个 k8s 集群中运行多个 Nginx 容器用于模拟多个应用实例
4. 调用 Nacos 的 OpenAPI 注册实例到 Nacos
5. 在 Higress 集群中配置 McpBridge 和 Ingress
6. 按照 "Ⅱ. Describe what happened" 中所述尝试 注销/下线 实例并观察 Higress 路由情况

### Ⅴ. Anything else we need to know?

以下是我目前的一些困惑：
1. 这是否属于一个 bug？还是一种特殊的机制？或者说是我们的使用方式不对？
2. Higress 和 Nacos 之间的底层交互逻辑是怎样的？Higress 应该不会每次有请求进来都去 Nacos 拉取一遍服务吧？应该会有类似缓存的机制？是 Higress 定期去 Nacos 中拉取服务列表，还是 Nacos 的服务列表有变动时通知 Higress？

### Ⅵ. Environment:

- Higress version:  2.0.2
- OS: Ubuntu 18.04
- Nacos：2.4.1

**Comment by XavierGrool** [comment]
> 请尝试重启一下controller服务，印象里删除服务来源，并不会真正的将服务删除，这个操作是为了避免误删


下线/注销 所有实例后，尝试通过以下命令重启 controller，之后再重新访问路由，发现确实可以按预期返回 503 了

```
kubectl rollout restart deployment <deployment_name>
```

但是如果是在生产环境，我们总不能为了下线一个应用实例而去重启 Higress 的 controller
如果我确定需要删除一个实例，而非误操作，有没有其它办法呢？

**Comment by CH3CHO** [comment]
这是一个已知问题，你可以关注一下这个 issue：https://github.com/alibaba/higress/issues/1546

**Comment by XavierGrool** [comment]
> 这是一个已知问题，你可以关注一下这个 issue：#1546

啊好的，非常感谢~
