### ISSUE TITLE
ai-quota插件代码的疑惑

### ISSUE THREAD

**Issue by ilovedumplings** [alibaba/higress#1567]
![image](https://github.com/user-attachments/assets/ca5cc0f7-fb23-46e6-8736-fa5efb2fe43a)

在onHttpRequestHeaders代码中,判断了adminMode为AdminModeQuery或(AdminModeRefresh,AdminModeDelta)的两种情况,请问为什么当adminModel为AdminModeQuery的时候直接执行了redis去查询,当adminModel为Refresh/Delta的时候却要context.BufferRequestBody(),然后让onHttpRequestBody去执行呢?
还有就是为什么要返回types.HeaderStopIteration,我看ai-quota配置里没有Header的过滤器了,是不是直接返回
`util.SendResponse(http.StatusOK, "ai-quota.queryquota", "application/json", string(body))
return types.ActionContinue `
就可以了?我对过滤器的执行枚举还不太了解,麻烦请教一下
@2456868764

**Comment by ilovedumplings** [comment]
@tanjunchen

**Comment by 2456868764** [comment]
1. AdminModeQuery 是 GET 模式，所以只根据头信息就可以 ，在 onHttpRequestHeaders  阶段就可以处理。
2. AdminModeRefresh,AdminModeDelta) 是 POST， 需要读取 Body， 要等到onHttpRequestBody 阶段处理， 这时候 执行
    ```
    context.BufferRequestBody()   //  表示缓存数据，会调用 onHttpRequestBody 方法
    return types.HeaderStopIteration // 当前 header 还不能继续交给下一个 filter 来处理，但是当前 filter 可以继续处理 body 数据
   ```
3. 非管理模式，会执行
    ```
     context.DontReadRequestBody()  //  表示不用读取 Body数据，跳过调用 onHttpRequestBody 方法
    return types.HeaderStopAllIterationAndWatermark // 停止所有迭代，表示当前 header 不能继续交给下一个 filter，并且当前 filter 也不能收到 body 数据
    ```
4. 你可以看一下 https://higress.io/docs/ebook/wasm16/ 电子书

**Comment by ilovedumplings** [comment]
> 主要 Envoy 是流式处理，正常 HeaderContinue 情况下，一个 Filter header 处理完成后，立刻要交个下个 Filter 处理，然后再处理 Body 数据（如何有的），处理完成后，再交给下个 Filter 处理。但是可以根据不同状态返回值有不同处理逻辑。
> 
> 1. HeaderStopIteration： 当前 Filter 处理头完成后，头不会交个下个 Filter 处理，当前 Filter 可以继续处理 Body 数据，等Body数据处理完成后， 头和 Body 数据一起交个 下个 Filter 处理。
> 2. HeaderStopAllIterationAndWatermark： 当前 Filter 暂停所有处理包括头和Body数据，只有执行到 ResumeHttpRequest 会继续执行，或者 SendHttpResponseWithDetail 直接返回。
> 
> ai-quota :
> 
> 1. AdminModeQuery 是 GET 模式，所以只根据头信息就可以 ，在 onHttpRequestHeaders  阶段就可以处理。
> 2. AdminModeRefresh,AdminModeDelta) 是 POST， 需要读取 Body， 要等到onHttpRequestBody 阶段处理， 这时候 执行
>    ```
>    context.BufferRequestBody()   //  表示缓存数据，会调用 onHttpRequestBody 方法
>    return types.HeaderStopIteration // 当前 header 还不能继续交给下一个 filter 来处理，但是当前 filter 可以继续处理 body 数据， 会调用 onHttpRequestBody 方法
>    ```
> 3. 非管理模式，会执行
>    ```
>     context.DontReadRequestBody()  //  表示不用读取 Body数据，跳过调用 onHttpRequestBody 方法
>    return types.HeaderStopAllIterationAndWatermark // 停止所有迭代，表示当前 header 不能继续交给下一个 filter，并且当前 filter 也不能收到 body 数据
>    ```
> 4. 你可以看一下 https://higress.io/docs/ebook/wasm16/ 电子书

感谢...我消化一下

**Comment by ilovedumplings** [comment]
> 主要 Envoy 是流式处理，正常 HeaderContinue 情况下，一个 Filter header 处理完成后，立刻要交个下个 Filter 处理，然后再处理 Body 数据（如何有的），处理完成后，再交给下个 Filter 处理。但是可以根据不同状态返回值有不同处理逻辑。
> 
> 1. HeaderStopIteration： 当前 Filter 处理头完成后，头不会交个下个 Filter 处理，当前 Filter 可以继续处理 Body 数据，等Body数据处理完成后， 头和 Body 数据一起交个 下个 Filter 处理。
> 2. HeaderStopAllIterationAndWatermark： 当前 Filter 暂停所有处理包括头和Body数据，只有执行到 ResumeHttpRequest 会继续执行，或者 SendHttpResponseWithDetail 直接返回。
> 
> ai-quota :
> 
> 1. AdminModeQuery 是 GET 模式，所以只根据头信息就可以 ，在 onHttpRequestHeaders  阶段就可以处理。
> 2. AdminModeRefresh,AdminModeDelta) 是 POST， 需要读取 Body， 要等到onHttpRequestBody 阶段处理， 这时候 执行
>    ```
>    context.BufferRequestBody()   //  表示缓存数据，会调用 onHttpRequestBody 方法
>    return types.HeaderStopIteration // 当前 header 还不能继续交给下一个 filter 来处理，但是当前 filter 可以继续处理 body 数据， 会调用 onHttpRequestBody 方法
>    ```
> 3. 非管理模式，会执行
>    ```
>     context.DontReadRequestBody()  //  表示不用读取 Body数据，跳过调用 onHttpRequestBody 方法
>    return types.HeaderStopAllIterationAndWatermark // 停止所有迭代，表示当前 header 不能继续交给下一个 filter，并且当前 filter 也不能收到 body 数据
>    ```
> 4. 你可以看一下 https://higress.io/docs/ebook/wasm16/ 电子书

![image](https://github.com/user-attachments/assets/03a2a8a2-aa43-4ca7-8f12-752d2f1ae4c8)

`
if adminMode == AdminModeRefresh || adminMode == AdminModeDelta {
	log.Infof("adminMode :%v", adminMode)
	ctx.BufferRequestBody()
	return types.HeaderStopIteration
}
我自己仿照写了一个类似的配额插件,当判断model为refresh和delta的时候,此时会暂时缓存数据,然后限制性当前插件的body数据,但是我这边直接堵塞住了......能不能麻烦老哥给看一看
`

**Comment by 2456868764** [comment]
> ![image](https://private-user-images.githubusercontent.com/19704134/392267741-ca5cc0f7-fb23-46e6-8736-fa5efb2fe43a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5Mjk0MjcsIm5iZiI6MTczNDkyOTEyNywicGF0aCI6Ii8xOTcwNDEzNC8zOTIyNjc3NDEtY2E1Y2MwZjctZmIyMy00NmU2LTg3MzYtZmE1ZWZiMmZlNDNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIzVDA0NDUyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxYzk5ZGVlM2U2OTZmN2UwMjZiYmNjMTJlMDg3MTkzNTA5MTJkY2U2YjdlMzk1ZjU3Yzc0NzhhNTYxMzU2ZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0ORJPUxc-wuDTEZykX5rQBrACpi5w25MSNuQf5mnt_k)
> 
> 在onHttpRequestHeaders代码中,判断了adminMode为AdminModeQuery或(AdminModeRefresh,AdminModeDelta)的两种情况,请问为什么当adminModel为AdminModeQuery的时候直接执行了redis去查询,当adminModel为Refresh/Delta的时候却要context.BufferRequestBody(),然后让onHttpRequestBody去执行呢? 还有就是为什么要返回types.HeaderStopIteration,我看ai-quota配置里没有Header的过滤器了,是不是直接返回 `util.SendResponse(http.StatusOK, "ai-quota.queryquota", "application/json", string(body)) return types.ActionContinue ` 就可以了?我对过滤器的执行枚举还不太了解,麻烦请教一下 @2456868764

编译时候加 TAG：  proxy_wasm_version_0_2_100
tinygo build -scheduler=none -target=wasi -gc=custom -tags='custommalloc nottinygc_finalizer proxy_wasm_version_0_2_100' -o ./build/plugin.wasm main.go
