### ISSUE TITLE
higress ai-history插件没有生效

### ISSUE THREAD

**Issue by ilovedumplings** [alibaba/higress#1574]
配置
![image](https://github.com/user-attachments/assets/f9ef9d7e-6fba-426d-8a96-30eeb68a6356)
模型请求
![image](https://github.com/user-attachments/assets/515d2ec3-57cb-49ac-93de-87fda7c66e36)
日志,级别未warning
![image](https://github.com/user-attachments/assets/39cfdd6e-9589-44b1-995c-c36fe096a352)
redis当中没有存储的数据

**Comment by ilovedumplings** [comment]
@yuemingming 能麻烦反馈一下吗?

**Comment by ilovedumplings** [comment]
![image](https://github.com/user-attachments/assets/cf685f63-8c04-4acd-b8c5-86f8df053dee)
日志gai改为debug界别之后

**Comment by ilovedumplings** [comment]
这个有问题啊.我测出来了,我需要自己在redis中set key value一个初始问答之后才能生效..没人用过么难道

**Comment by ilovedumplings** [comment]
![image](https://github.com/user-attachments/assets/3b0b8a49-406c-43ba-897a-10d7b7245532)

**Comment by johnlanni** [comment]
@yuemingming 看上去这段逻辑应该放到 redis callback 之外：

https://github.com/alibaba/higress/blob/be57960c22ab5aa83cbed27a8b7502f0bbea04f8/plugins/wasm-go/extensions/ai-history/main.go#L233-L239

现在当redis里取不到时，就不会记录上下文了。

**Comment by rinfx** [comment]
#1606 中已修复

**Comment by johnlanni** [comment]
可以再试一下，已经更新镜像
higress-registry.cn-hangzhou.cr.aliyuncs.com/plugins/ai-history:1.0.0
