### ISSUE TITLE
系统新增选择证书时支持设置TLS 版本功能

### ISSUE THREAD

**Issue by w7team** [alibaba/higress#1582]
选择证书时支持设置TLS 版本，目前默认支持TLS v1.0导致有些第三方平台对接接口时无法通过检测

**Comment by johnlanni** [comment]
https://github.com/alibaba/higress/issues/1027

**Comment by johnlanni** [comment]
duplicate issue

**Comment by w7team** [comment]
1027给的方案，试了一下，没成功。现在好像默认没有networking.istio.io/v1alpha3接口

**Comment by johnlanni** [comment]
https://github.com/alibaba/higress/releases/download/v2.0.4/crd.yaml

没有用最新的crd吧

**Comment by w7team** [comment]
> https://github.com/alibaba/higress/releases/download/v2.0.4/crd.yaml
> 
> 没有用最新的crd吧

安装完CRD后，可以正常创建EnvoyFilter了，但是又有一个新问题，执行后tls版本没改变，还是最小从tls1开始。你们能确认一下这个问题不？

**Comment by johnlanni** [comment]
![image](https://github.com/user-attachments/assets/2cec0ae1-8be3-4f59-a9da-0ad17110489a)

我测试了是没问题的，你可以自己执行下这个看看：
` k exec -it higress-gateway-xxxxxx -n higress-system -- curl localhost:15000/config_dump -s | grep tls_min`
higress-gateway-xxxxxx 换成你自己的 pod 名字

**Comment by w7team** [comment]
![image](https://github.com/user-attachments/assets/74164e31-735a-4f36-8c13-6c53c702e605)
![image](https://github.com/user-attachments/assets/86ec15e9-05e7-4084-8eec-365f78c60eb7)

我看我的配置里没有，创建EnvoyFilter后gateway也重启过了。
我用的2.0.3版本，之前没有安装istio的crd，刚刚执行了你上面提供的crd.yaml

是不是我少配置什么了？

**Comment by johnlanni** [comment]
确认一下你的configdump文件，里面有没有监听443端口，然后再确认下 higress gateway 的 pod 有没有 `app: higress-gateway` 这个 label

**Comment by w7team** [comment]
![image](https://github.com/user-attachments/assets/e79b1bcd-0d57-4879-b689-60a8ebdeaaa1)
![image](https://github.com/user-attachments/assets/59ef1460-3fc8-40ba-820b-76f51ccbd2fd)

都有，443也正常访问

**Comment by johnlanni** [comment]
看一下 higress-config 这个 cm 呢

**Comment by w7team** [comment]
![image](https://github.com/user-attachments/assets/66c369e7-8c9e-40e5-9a05-91f26fa55155)
config里就是默认的，只加了一个downstream

**Comment by johnlanni** [comment]
不是，是因为你没有开启 istio api 的监听，设置下这个 helm 参数:

`-set global.enableIstioAPI=true`

**Comment by w7team** [comment]
![image](https://github.com/user-attachments/assets/80e72105-0b03-424c-a12f-f90283bc2cda)
可以了，确实是旧版的问题，多谢多谢
