### ISSUE TITLE
openai is not supported in zhipu by ai-proxy plugin in v2.0.3

### ISSUE THREAD

**Issue by StarryVae** [alibaba/higress#1584]
### Ⅰ. Issue Description

Model mapping is not implemented in zhipu by ai-proxy of version v2.0.3 , so it can not supprt openai ? but, it seems to be supported in the new version v2.0.4 because model mapping is implemented  in a common function here?

https://github.com/alibaba/higress/blob/f32020068acb774955c24245ac334d4859929cef/plugins/wasm-go/extensions/ai-proxy/provider/provider.go#L577

### Ⅵ. Environment:

- Higress version:  v2.0.3
- OS :
- Others:

**Comment by johnlanni** [comment]
Is there an issue with the latest version of ai-proxy?

**Comment by StarryVae** [comment]
From the code it looks like this issue has been fixed in the latest version, but I haven't actually tested it.

**Comment by johnlanni** [comment]
Okay, if you still have issues after testing, let's take another look

**Comment by StarryVae** [comment]
By the way, is it reasonable to just return `StopIteration` at the header phase without determining if there is a body in some provider like `qwen`? If a request without body comes (although relatively rare), the filter chain in envoy will just block here waitting for body.

**Comment by johnlanni** [comment]
You're right, currently the provider has its own permissions to choose what status to return, and it seems that such flexibility is not needed; a unified judgment in main.go would suffice:

https://github.com/alibaba/higress/blob/be57960c22ab5aa83cbed27a8b7502f0bbea04f8/plugins/wasm-go/extensions/ai-proxy/main.go#L108-L114

cc @CH3CHO @cr7258

**Comment by StarryVae** [comment]
yeah, i also believe that it should be  a unified judgment in main.go, and can i try to submit a PR to fix this? thanks!

**Comment by johnlanni** [comment]
If you're interested in contributing a PR, that would be great.
