### ISSUE TITLE
oidc插件域名级第二个不生效

### ISSUE THREAD

**Issue by ningpengtao-coder** [alibaba/higress#1600]
环境
higress版本：2.0.1
higress oidc插件版本：1.0.0

问题：
域名级oidc插件开启多个，第二个oidc不生效，访问的是第一个oidc插件。

**Comment by johnlanni** [comment]
cc @rinfx

**Comment by rinfx** [comment]
#1601

**Comment by rinfx** [comment]
镜像已经更新了，可以重新pull一下：higress-registry.cn-hangzhou.cr.aliyuncs.com/plugins/oidc:1.0.0

**Comment by ningpengtao-coder** [comment]
@rinfx 试过了，没问题
