### ISSUE TITLE
能提供otel的trace么

### ISSUE THREAD

**Issue by zhaomingcheng01** [alibaba/higress#1607]
![image](https://github.com/user-attachments/assets/c927c792-f743-4534-a88b-84a91d89c2ea)

**Comment by johnlanni** [comment]
已经支持了的，我更新下文档

**Comment by johnlanni** [comment]
参考：
https://github.com/higress-group/higress-group.github.io/blob/main/src/content/docs/latest/zh-cn/user/configmap.md
