### ISSUE TITLE
model-route路由级别无法生效

### ISSUE THREAD

**Issue by ilovedumplings** [alibaba/higress#1618]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via [ASRC](https://security.alibaba.com/)(Alibaba Security Response Center) where the issue will be triaged appropriately.**

- [ ] I have searched the [issues](https://github.com/alibaba/higress/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
Model-route无法再路由级别生效，看model-route插件更新了，可以直接根据model进行路由，但是实际测试当中发现配置在路由上无法生效，只能配置到域名上才能生效。
![image](https://github.com/user-attachments/assets/61d63f95-1b90-4c8c-8423-80723e603a06)
此时是不生效的,http code 404 
![image](https://github.com/user-attachments/assets/191dfd4a-c398-4e61-964e-3b35c8f6a332)
此时是生效的,正常返回200
![image](https://github.com/user-attachments/assets/b4b6aca6-7760-407b-a5e3-2357634a78f8)
这是header的匹配,是需要改成精确匹配,也无法生效
@johnlanni 
### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- Higress version:  
- OS :
- Others:

**Comment by CH3CHO** [comment]
可以思考一下model-route的逻辑和路由匹配的逻辑。

1. 路由要求有对应header才能匹配
2. model-route是把请求里的model放到header里

所以在model-route还没执行的时候，路由是匹配不到的。所以你把model-route关联到路由是不可能能工作的。

**Comment by ilovedumplings** [comment]
> 可以思考一下model-route的逻辑和路由匹配的逻辑。
> 
> 1. 路由要求有对应header才能匹配
> 2. model-route是把请求里的model放到header里
> 
> 所以在model-route还没执行的时候，路由是匹配不到的。所以你把model-route关联到路由是不可能能工作的。

有道理的!!!

**Comment by CH3CHO** [comment]
model-route插件默认只会路径包含`/v1/chat/completions`后缀的请求生效，所以直接全局开问题也不大。

https://github.com/alibaba/higress/tree/main/plugins/wasm-cpp/extensions/model_router
