### ISSUE TITLE
AI-Cache插件针对流式请求不缓存的问题

### ISSUE THREAD

**Issue by ilovedumplings** [alibaba/higress#1624]
先请求了两边流式请求
![image](https://github.com/user-attachments/assets/9ac4b7aa-dd28-461d-a26f-274822139797)
然后请求了两边非流式
![image](https://github.com/user-attachments/assets/58bc0d3c-cc5c-48f2-8ecd-54a03e47439b)
第二遍的流式请求依旧消耗了token
第二遍的非流式请求就没有消耗token了

**Comment by ilovedumplings** [comment]
@CH3CHO

**Comment by ilovedumplings** [comment]
我的配置采取的是默认的ai-cache的配置 


![image](https://github.com/user-attachments/assets/444a29a9-d8c3-47fb-9f8a-da00c78db1fc)

**Comment by ilovedumplings** [comment]
![image](https://github.com/user-attachments/assets/488482fb-2507-4db5-8e1c-ec451f2a48b5)
看日志的话,第二次的key也是miss的

**Comment by johnlanni** [comment]
上周修复了一个流式场景下的bug，刚刚已经发布了新的ai-cache插件镜像，你可以再试试

**Comment by ilovedumplings** [comment]
![image](https://github.com/user-attachments/assets/08d81ade-d4fc-4862-aaaa-a445890bb8ec)
![image](https://github.com/user-attachments/assets/462a4e52-f82b-4dd4-9b89-e13e8de8c2ac)
![image](https://github.com/user-attachments/assets/90c87c4f-c62f-4947-b34d-97bddcce496e)
试了下还是没有走缓存

> 上周修复了一个流式场景下的bug，刚刚已经发布了新的ai-cache插件镜像。
> 
> 等这个流水线跑好：https://github.com/alibaba/higress/actions/runs/12489103113
> 
> 你可以再试试

**Comment by johnlanni** [comment]
@ilovedumplings 可以关闭下其他插件，只保留 ai cache 插件看看流式下是否生效吗，排除下是否其他插件逻辑的干扰

**Comment by ilovedumplings** [comment]
> @ilovedumplings 可以关闭下其他插件，只保留 ai cache 插件看看流式下是否生效吗，排除下是否其他插件逻辑的干扰
只留下了这些插件,日志级别改成了info,还是有问题
![image](https://github.com/user-attachments/assets/309e87ad-247c-4d9d-adf1-f21cfa1cfae7)
![image](https://github.com/user-attachments/assets/d8b892d9-f1e1-4547-98fd-ada49253857e)

**Comment by johnlanni** [comment]
@ilovedumplings 只留下 ai-cache 呢

**Comment by johnlanni** [comment]
我们自己测了是没问题的。。不知道你的环境什么原因

**Comment by ilovedumplings** [comment]
> ai-proxy

没有开ai-proxy,我看readme里面没有说明呢,是我漏掉了什么嘛?

**Comment by ilovedumplings** [comment]
> 我们自己测了是没问题的。。不知道你的环境什么原因。 你没有开 ai-proxy 插件吗？是直接代理到openai？

没有开ai-proxy,我看readme里面没有说明呢,是我漏掉了什么嘛?

**Comment by johnlanni** [comment]
@ilovedumplings 那你确定后端返回了 openai 协议格式的响应吗？

**Comment by ilovedumplings** [comment]
> @ilovedumplings 那你确定后端返回了 openai 协议格式的响应吗？我怀疑是后端的流式输出没有遵循openai的协议格式
这是我返回的数据，看着应该是openai协议格式的响应

data: {"id": "chatf5f7abfa-c2ad-11ef-8344-225e3cba1c5b", "model": "qwen2-72b-instruct-gptq-int4", "created": 1735123788, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"role": "assistant", "content": ""}, "finish_reason": null}]}

data: {"id": "chatf5f7abfa-c2ad-11ef-8344-225e3cba1c5b", "model": "qwen2-72b-instruct-gptq-int4", "created": 1735123788, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": ""}, "finish_reason": null}]}

data: {"id": "chatf5f7abfa-c2ad-11ef-8344-225e3cba1c5b", "model": "qwen2-72b-instruct-gptq-int4", "created": 1735123788, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": ""}, "finish_reason": null}]}

data: {"id": "chatf5f7abfa-c2ad-11ef-8344-225e3cba1c5b", "model": "qwen2-72b-instruct-gptq-int4", "created": 1735123788, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": ""}, "finish_reason": null}]}

data: {"id": "chatf5f7abfa-c2ad-11ef-8344-225e3cba1c5b", "model": "qwen2-72b-instruct-gptq-int4", "created": 1735123788, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": ""}, "finish_reason": null}]}

data: {"id": "chatf5f7abfa-c2ad-11ef-8344-225e3cba1c5b", "model": "qwen2-72b-instruct-gptq-int4", "created": 1735123788, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": ""}, "finish_reason": null}]}

data: {"id": "chatf5f7abfa-c2ad-11ef-8344-225e3cba1c5b", "model": "qwen2-72b-instruct-gptq-int4", "created": 1735123788, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": ""}, "finish_reason": null}]}

data: {"id": "chatf5f7abfa-c2ad-11ef-8344-225e3cba1c5b", "model": "qwen2-72b-instruct-gptq-int4", "created": 1735123788, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": ""}, "finish_reason": null}]}

data: {"id": "chatf5f7abfa-c2ad-11ef-8344-225e3cba1c5b", "model": "qwen2-72b-instruct-gptq-int4", "created": 1735123788, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": ""}, "finish_reason": null}]}

data: {"id": "chatf5f7abfa-c2ad-11ef-8344-225e3cba1c5b", "model": "qwen2-72b-instruct-gptq-int4", "created": 1735123788, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "你好，你好，你好，你好。"}, "finish_reason": null}]}

data: {"id": "chatf5f7abfa-c2ad-11ef-8344-225e3cba1c5b", "model": "qwen2-72b-instruct-gptq-int4", "created": 1735123788, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {}, "finish_reason": "stop"}]}

data: {"id": "chatf5f7abfa-c2ad-11ef-8344-225e3cba1c5b", "model": "qwen2-72b-instruct-gptq-int4", "created": 1735123788, "object": "chat.completion.chunk", "choices": [], "usage": {"prompt_tokens": 24, "completion_tokens": 9, "total_tokens": 33}}

data: [DONE]

**Comment by johnlanni** [comment]
![image](https://github.com/user-attachments/assets/86fad32a-f605-4437-930f-ab5945578a7c)
@ilovedumplings 蓝线部分的base64复制贴一下，我看看

**Comment by ilovedumplings** [comment]
重新做了一笔

**Comment by ilovedumplings** [comment]
> ![image](https://private-user-images.githubusercontent.com/6763318/398566557-86fad32a-f605-4437-930f-ab5945578a7c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxMjUzMTMsIm5iZiI6MTczNTEyNTAxMywicGF0aCI6Ii82NzYzMzE4LzM5ODU2NjU1Ny04NmZhZDMyYS1mNjA1LTQ0MzctOTMwZi1hYjU5NDU1NzhhN2MucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMjVUMTExMDEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWIwMGMyMDhiN2JhYzM1ZmUzYjIxODE4MzdhN2I2MzYwN2FkMmIxN2MzNzA4NTU4MTgyYmU0ZDlmMWQ2Zjc5ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.Cy9-RqTHX_B8FxOn0c4uCoY7pNFnyhR47dpd5irpNk8) @ilovedumplings 蓝线部分的base64复制贴一下，我看看

两个base64都解密了贴上了
![image](https://github.com/user-attachments/assets/51b787c6-f68e-41cd-afc6-13f91b966295)

![image](https://github.com/user-attachments/assets/ae906008-2a4b-41cd-a46b-49767e5e10ff)

**Comment by johnlanni** [comment]
![image](https://github.com/user-attachments/assets/c900e88c-0006-4c4f-9839-80821bf31c3f)
@ilovedumplings 是这里给的默认配置有问题，你直接去掉这几个配置项，用默认值就可以了

**Comment by ilovedumplings** [comment]
我把这里的默认配置删除以后也不太行..
![image](https://github.com/user-attachments/assets/1c0be344-5e6c-4701-b2d3-bfb19df884a1)
![image](https://github.com/user-attachments/assets/fc1c1473-1104-4a29-b713-ded0b9aa7612)
![image](https://github.com/user-attachments/assets/46476cd9-f4d2-4293-ad97-46e6defb46e2)

**Comment by ilovedumplings** [comment]
日志最后会打印 cached value for key 说你好说5遍 is empty  @johnlanni

**Comment by johnlanni** [comment]
@ilovedumplings 我复现不出，加一下我钉钉吧：chengtanzty

**Comment by johnlanni** [comment]
用这个镜像试一下，加了行debug日志：
higress-registry.cn-hangzhou.cr.aliyuncs.com/plugins/ai-cache:test

**Comment by johnlanni** [comment]
已经定位是后端用了xinference框架，SSE消息不是用\n\n分隔，而是用\r\n\r\n分隔，这个不符合SSE的规范，需要到xinference社区提一下这个问题

**Comment by johnlanni** [comment]
根据whatwg的定义，确实允许用CRLF分隔，虽然大部分是用的LF，这个PR做了兼容：https://github.com/alibaba/higress/pull/1626/files
