### ISSUE TITLE
Add e2e test for rewrite annotations

### ISSUE THREAD

**Issue by johnlanni** [alibaba/higress#167]
url rewrite: https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#rewrite
host rewrite: https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#custom-nginx-upstream-vhost

e2e framework: https://github.com/alibaba/higress/tree/main/test

**Comment by Xunzhuo** [comment]
Done in favor of: #182 #177
