### ISSUE TITLE
Add e2e test for url redirect annotations

### ISSUE THREAD

**Issue by johnlanni** [alibaba/higress#168]
annotation docs:
https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#permanent-redirect
https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#permanent-redirect-code
https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#temporal-redirect

e2e framework: https://github.com/alibaba/higress/tree/main/test

**Comment by whalecold** [comment]
I want to try it, could you assign it to me

**Comment by Xunzhuo** [comment]
Missing `nginx.ingress.kubernetes.io/app-root`

**Comment by whalecold** [comment]
@johnlanni the related e2e tests completed, we can close the issue.

**Comment by Xunzhuo** [comment]
Thanks @whalecold
