### ISSUE TITLE
Add e2e test for ssl redirect annotations

### ISSUE THREAD

**Issue by johnlanni** [alibaba/higress#169]
annotation doc: https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#server-side-https-enforcement-through-redirect

e2e framework: https://github.com/alibaba/higress/tree/main/test

**Comment by swf2020** [comment]
I can test, Please assign this issue to me, thanks

**Comment by Xunzhuo** [comment]
nginx.ingress.kubernetes.io/force-ssl-redirect
nginx.ingress.kubernetes.io/ssl-redirect

**Comment by johnlanni** [comment]
@swf2020 Hello, Is there any progress on this work?

**Comment by Fkbqf** [comment]
Please assign to me
