### ISSUE TITLE
Makefile for wasm-go for making building easier

### ISSUE THREAD

**Issue by dspo** [alibaba/higress#185]
## Why do you need it?

目前构建 wasm-go 插件, 要求开发者在本地搭建 Go 和 TinyGo 环境, 构建时需要先在本地构建出 wasm 文件, 然后拷贝到镜像中, 搭建环境和构建的过程都比较繁琐.
而且用户并不一定都是 Go 语言的开发者, 搭建环境和理解构建过程对这些用户不一定是一件很容易的事情.

## How could it be?

希望可以提供一个 Makefile, 使得用户可以无须在搭建环境上花费额外的注意力, 可以很简单地构建出 wasm 文件和相应的 docker image.

## Other related information

相关 issue #152

**Comment by dspo** [comment]
我为此提交了一个 PR #184

**Comment by Xunzhuo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Pomodoro Technique](https://trello.com/c/cYt1un7f/1-pomodoro-technique)

**Comment by Xunzhuo** [comment]
Part of: https://github.com/alibaba/higress/issues/152
