### ISSUE TITLE
Reduce repeated steps for building wasm-go plugins

### ISSUE THREAD

**Issue by dspo** [alibaba/higress#189]
## Why do you need it?
使用 make build 构建 wasm-go 插件时每次都要从头构建 builder (apt-get update, 安装 Go 和 Tinygo) 花费大量时间在重复工作上（尤其是重复的网络 IO 上）。

## How could it be?

可以重新设计构建流程，减少重复工作。

**Comment by Xunzhuo** [comment]
Part of: https://github.com/alibaba/higress/issues/152
