### ISSUE TITLE
e2e: add testcases for downstream encryption annotations

### ISSUE THREAD

**Issue by Xunzhuo** [alibaba/higress#198]
## Why do you need it?

annotations: 
+ `nginx.ingress.kubernetes.io/ssl-cipher`
+ `nginx.ingress.kubernetes.io/auth-tls-secret`

## How could it be?
Add testcases for encryption annotations.

## Other related information
+ https://github.com/alibaba/higress/tree/main/test
+ https://github.com/alibaba/higress/issues/190

**Comment by WeixinX** [comment]
please assign it to me :) ❤️
