### ISSUE TITLE
Test the GC optimization of Tinygo 0.27

### ISSUE THREAD

**Issue by johnlanni** [alibaba/higress#225]
## Why do you need it?

We've built many wasm go plugins through Tinygo 0.25 and we want to upgrade to Tinygo 0.27 which does some GC optimizations and it also provides a new gc option: `-gc=precise` seems to be more faster than `-gc=conservative`.

## How could it be?

1. Write a wasm plugin to frequently create & release multiple objects
2. Build different plugins with Tinygo 0.25 and 0.27 (with different gc options)
3. Deploy different plugins to Higress
4. Start the benchmark test and observe the cpu&memory metrics of Higress

## Other related information

https://github.com/tinygo-org/tinygo/releases

**Comment by Fkbqf** [comment]
Hi, I have an idea for this task, but don't know how to test the wasm plugin in higress, can you give some help tips

**Comment by johnlanni** [comment]
https://higress.io/zh-cn/docs/plugins/custom
https://higress.io/zh-cn/docs/user/wasm-go

@Fkbqf FYI

**Comment by Fkbqf** [comment]
please assign me

> https://higress.io/zh-cn/docs/plugins/custom https://higress.io/zh-cn/docs/user/wasm-go
> 
> @Fkbqf FYI
