### ISSUE TITLE
"What is Higress?" has Chinese text when reading in English

### ISSUE THREAD

**Issue by tomkerkhove** [alibaba/higress#242]
### Ⅰ. Issue Description

Read documentation on https://higress.io/en-us/ in English

### Ⅱ. Describe what happened

The image has Chinese text which makes it hard to understand:

![Image](https://img.alicdn.com/imgextra/i4/O1CN01goCCMC1HBLZend9Gl_!!6000000000719-2-tps-3201-1561.png)

### Ⅲ. Describe what you expected to happen

Use English text instead.

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. Go to https://higress.io/en-us/

**Comment by johnlanni** [comment]
cc @laojun

**Comment by CH3CHO** [comment]
Fixed in https://github.com/higress-group/higress-group.github.io/pull/100

**Comment by tomkerkhove** [comment]
Thank you!
