### ISSUE TITLE
提供 Higress Admin API 完整说明文档

### ISSUE THREAD

**Issue by johnlanni** [alibaba/higress#250]
## Why do you need it?
使 Higress 的能力可以被其他 PaaS 平台集成

**Comment by CH3CHO** [comment]
认证方面需要进一步完善，支持Token等对自动化平台更加友好的认证方式。

**Comment by wing731** [comment]
+1

**Comment by johnlanni** [comment]
我们不会提供Console的Admin API，这块的API后面可能会跟随版本发生变化，但底层的Ingress/Gateway API模型是不变的。可以基于Console的Java SDK进行集成，SDK封装了对Ingresss/Gateway API的操作：
https://github.com/higress-group/higress-console/tree/main/backend/sdk
