### ISSUE TITLE
Add OIDC support

### ISSUE THREAD

**Issue by tyeapple** [alibaba/higress#271]
## Why do you need it?
使用envoy做gateway时，面对sso场景，需要使用oauth2-proxy搭配支持。envoy自身仅提供了oauth2 filter，该filter在功能上，有所欠缺，希望higress可以提供OAuth2有关的支持。
个人理解，类似：https://docs.konghq.com/hub/kong-inc/oauth2/

## How could it be?
OAuth2-Proxy仅支持多对一的代理，这使得它的功能性有所缺失。请参考：https://github.com/oauth2-proxy/oauth2-proxy/issues/739

**Comment by johnlanni** [comment]
嗯 你需要的是 OAuth2 Proxy 所具备的 OIDC 的能力，目前 envoy 最新版本的 oauth2 filter 已经开业完成基本的 OIDC 能力，不过功能上对比 oauth2-proxy 还是差很多，可以尝试复用 oauth2 proxy 的一些逻辑来实现一个功能强大的 OIDC wasm 插件，如果有兴趣的同学可以认领这个任务。

kong 的 oauth2 插件是用于做 consumer 身份认证的，oidc 能力可以参考这个：https://docs.konghq.com/hub/kong-inc/openid-connect，跟 keycloak 交互的文档写的很详细，值得学习

**Comment by Charlie17Li** [comment]
@johnlanni Hi, I am very interested in this feature and I will submit my application before the deadline.

**Comment by johnlanni** [comment]
感谢关注，有兴趣在开源之夏认领这个项目的同学，可以加我微信: nomadao
