### ISSUE TITLE
Add support for Rust+Wasm plugin in Higress？

### ISSUE THREAD

**Issue by superstarchenxin** [alibaba/higress#284]
## Why do you need it?
   As a user of Higress, I would like to request support for the Rust+Wasm plugin in the tool. There are two main reasons why I believe this is important:
- Rust is faster than Go, which is the primary language used for Wasm plugins in Higress. By adding support for Rust+Wasm, users can take advantage of the performance benefits of Rust and improve the speed and efficiency of their binary analysis workflows.
- Rust+Wasm is very popular in the Istio community, and many users in this community would benefit from having a binary analysis tool that supports this language combination. By adding support for Rust+Wasm, Higress can better serve the needs of this community and attract more users who are looking for a tool that supports Rust+Wasm.

## How could it be?
I would like to request that Higress add support for the Rust+Wasm plugin in addition to the Go+Wasm plugin. This could be achieved by implementing the Rust+Wasm plugin within Higress or by providing a mechanism for users to create and use their own Rust+Wasm plugins within the tool.

## Other related information
Adding support for Rust+Wasm would make Higress more versatile and useful for a wider range of users. The Rust programming language is becoming increasingly popular, and its use in web development with Wasm is growing rapidly.

**Comment by johnlanni** [comment]
already support
