### ISSUE TITLE
Provide Helm chart README

### ISSUE THREAD

**Issue by tomkerkhove** [alibaba/higress#295]
## Why do you need it?
Provide Helm chart README to help understand what knobs are available.

## How could it be?
List configuration options and what they are doing

**Comment by CH3CHO** [comment]
Duplicated with #251, although the original one was written in Chinese.

**Comment by CH3CHO** [comment]
Here it is: https://higress.io/en-us/docs/ops/deploy-by-helm/#installation-parameters

**Comment by tomkerkhove** [comment]
That is nice, but will not be available on things such as Artifact Hub.

It is recommended to add a README with basic information and configuration info (either list or link to that doc).

I personally prefer parameters in the Readme so that it shows the supported configuration for a specific version

**Comment by CH3CHO** [comment]
Got it. I saw your another issue mentioned this, https://github.com/alibaba/higress/issues/293. However, I'm not sure who's managing Higress charts on Artifact Hub. @johnlanni, could you take a look?

**Comment by CH3CHO** [comment]
Here we go. @tomkerkhove

https://artifacthub.io/packages/helm/higress/higress
![image](https://user-images.githubusercontent.com/2909796/236725601-5a80512b-69c7-4149-88c9-195a18214787.png)

**Comment by tomkerkhove** [comment]
Wonderful, thank you! It looks like we can close https://github.com/alibaba/higress/issues/293 as well then?

**Comment by CH3CHO** [comment]
> Wonderful, thank you! It looks like we can close #293 as well then?

I agree. Could you close both of them?

**Comment by tomkerkhove** [comment]
With pleasure, much appreciated!
