### ISSUE TITLE
有搭建开发环境入门资料吗

### ISSUE THREAD

**Issue by hadoop835** [alibaba/higress#30]
有搭建开发环境入门资料吗

**Comment by johnlanni** [comment]
文档在更新中，这周会搞的差不多，可以先安装试用下：https://higress.io/zh-cn/docs/user/quickstart.html

**Comment by Xunzhuo** [comment]
看了一下项目很多依赖都是用的 submodule 去管理，git mod replace 去引用的。提供了一些 makefile targets 去构建环境。

可以 clone 下来试试 make build @hadoop835

**Comment by liweijian** [comment]
> 文档在更新中，这周会搞的差不多，可以先安装试用下：https://higress.io/zh-cn/docs/user/quickstart.html

可以在文档里面加上 WASM plugin的测试方法吗？

当前 WASM的入门配置似乎有点繁琐：
https://github.com/alibaba/higress/blob/main/plugins/wasm-go/README.md

**Comment by johnlanni** [comment]
@liweijian 嗯，这个例子包含了从wasm编译，镜像构建的流程，如果想直接测试可以用这个文档里的yaml：
https://github.com/alibaba/higress/tree/main/plugins

后面我增加下quickstart

**Comment by liweijian** [comment]
@johnlanni 我根据快速入门，运行

```
❯ curl localhost/foo
no healthy upstream%
❯ curl localhost/bar
no healthy upstream%
```

是某一步漏了吗？ macbook M1 pro的

**Comment by johnlanni** [comment]
@liweijian 可能是这个 foo 和 bar 的pod镜像没拉下来，你 kubectl get po 看看，后面我搞个国内仓库的镜像

**Comment by liweijian** [comment]
@johnlanni 

```sh
❯ kubectl get po
NAME      READY   STATUS             RESTARTS       AGE
bar-app   0/1     CrashLoopBackOff   13 (45s ago)   42m
foo-app   0/1     CrashLoopBackOff   13 (41s ago)   42m
```

对了，我们是IDEA研究院，WASM是我们的研究方向之一 https://idea.edu.cn/dii.html

后续我们想给higress开发一些wasm plugin配套的工具，你方便加一下我wx吗 `bGFtYmRhLWNhbGN1bHVz` (base64 decode ？
