### ISSUE TITLE
k3s 搭建的higress不能访问443端口

### ISSUE THREAD

**Issue by clywm520** [alibaba/higress#300]
k3s 版本1.21.7
安装命令
helm repo add higress.io https://higress.io/helm-charts
helm install higress -n higress-system higress.io/higress --create-namespace --render-subchart-notes --set higress-console.domain=console.higress.io

启动后443端口从流量入口访问. 80端口可以正常访问

**Comment by clywm520** [comment]
启动后，无法从443端口　入口访问。　加域名sni都无效

**Comment by CH3CHO** [comment]
不知道你没有试过调整 higress-console 的 Ingress。单纯按照上方命令安装的 Console 是没有启用 HTTPS 访问的。如果要启用的话，可以通过 `higress-console.tlsSecretName` 这个参数来在安装时指定 TLS 证书名字。

**Comment by clywm520** [comment]
现在问题是后端应用无法使用https. 流量通过gateway进入

**Comment by CH3CHO** [comment]
> 现在问题是后端应用无法使用https. 流量通过gateway进入

能提供一下相关应用的 Ingress 配置吗？

**Comment by johnlanni** [comment]
我在 k8s 上测了 nodeport 方式是没问题的，操作如下：
创建 nodeport service
![image](https://user-images.githubusercontent.com/6763318/234241620-e76ae6cd-7ad3-441e-871a-1b2b0528911d.png)
查看 node 的 ip
![image](https://user-images.githubusercontent.com/6763318/234241785-1d32b957-6610-41d8-a1c1-549e9d76ce13.png)
随便找一个 pod 进去，访问node上代理了 higress 443 的端口，可以访问通
![image](https://user-images.githubusercontent.com/6763318/234241843-698facdc-99d0-4018-957c-2adc870e0d78.png)

**Comment by johnlanni** [comment]
可以进 higress-gateway 的 pod，执行 `curl --resolve  xxxx:443:127.0.0.1  https://xxxx` ，其中xxxx换成你开启了https的域名，如果能访问通，则说明是 k3s 的 nodeport 机制有问题，如果访问不通，则说明是你的 ingress 配置有问题（比如tls字段没设置，或者对应的 secret 不存在等）
