### ISSUE TITLE
Implement "CORS" strategy using Wasm Plugin

### ISSUE THREAD

**Issue by CH3CHO** [alibaba/higress#336]
## Why do you need it?

Implement "CORS" strategy using Wasm plugin to gain a better extensibility.
 
![image](https://github.com/alibaba/higress/assets/2909796/4b10c919-c47d-48de-a8ae-71dfaecdd4a1)

## How could it be?

For the function part, you can refer to the current implementation: https://github.com/alibaba/higress/blob/main/pkg/ingress/kube/annotations/cors.go

## Other related information

N/A

**Comment by 2456868764** [comment]
Please assign it to me ~
