### ISSUE TITLE
"bazel build //extensions/key_rate_limit:key_rate_limit.wasm" reports an error

### ISSUE THREAD

**Issue by TC-wang** [alibaba/higress#338]
### Ⅰ. Issue Description
Trying to compile the key_rate_limit plugin in wasm-app reports an error

### Ⅱ. Describe what happened

Execute the following command: `bazel build //extensions/key_rate_limit:key_rate_limit.wasm`

```
ERROR: /go/src/higress/plugins/wasm-cpp/extensions/key_rate_limit/BUILD:18:15: //extensions/key_rate_limit:_wasm_key_rate_limit.wasm depends on @local_config_cc//:cc-compiler-k8 in repository @local_config_cc which failed to fetch. no such package '@local_config_cc//':
Auto-Configuration Error: Cannot find gcc or CC (clang); either correct your path or set the CC environment variable
```

 After manually setting CC env, but it didn't work
$ echo $CC
gcc

### Ⅲ. Describe what you expected to happen
build success, and get .wasm file

### Ⅵ. Environment:

- Higress version:  v1.0.0-rc.4
- OS :  Debian GNU/Linux 9
- Others:   bazel 5.4.0

**Comment by CH3CHO** [comment]
Higress uses clang to build Wasm plugins (see [here](https://github.com/alibaba/higress/blob/main/plugins/wasm-cpp/.bazelrc)). You need have clang installed first.

**Comment by TC-wang** [comment]
Thanks. I'll try.
