### ISSUE TITLE
E2E framework supports testing wasm plugins

### ISSUE THREAD

**Issue by johnlanni** [alibaba/higress#342]
## Why do you need it?
The wasm plugin needs to be compiled to generate an oci image before it can be referenced in the WasmPlugin resource.

## How could it be?
Refer to: https://github.com/alibaba/higress/tree/main/plugins/wasm-go

Use `PLUGIN_NAME=<pluginName> make build` to build the oci image, and then store the image in the kind cluster. We can then use it in the WasmPlugin resource via the e2e manifest file.

**Comment by Hinsteny** [comment]
Please assign this issue to me, tks
