### ISSUE TITLE
Improve the image and helm charts building workflow for Higress Core and Higress

### ISSUE THREAD

**Issue by CH3CHO** [alibaba/higress#346]
## Why do you need it?

Currently, GitHub Actions are only responsible for building the helm charts for the Higress suite (core + console), but not for Higress Core. Building docker image isn't covered, either. This causes quite a lot of manual work when releasing a new version of Higress.

## How could it be?

When a tag named like "v*.*.*" is pushed to this repo, a corresponding GitHub Action shall be triggered to build both docker image and helm chart for Higress Core. Image tags shall be deduced from the tag name. And helm chart shall use the newly built image tag by default.

Meanwhile, the helm chart for the Higress suite shall also be built with the latest version of Higress Core. The version of Higress Console can be left as it is, since its version is managed by [another repo])(https://github.com/higress-group/higress-console/).

## Other related information
[Image Building Workflow of Higress Console](https://github.com/higress-group/higress-console/blob/main/.github/workflows/deploy-to-k8s.yaml)

**Comment by johnlanni** [comment]
already done
