### ISSUE TITLE
higress是如何支持多个集群通讯

### ISSUE THREAD

**Issue by fengyeall111** [alibaba/higress#355]
## Why do you need it?
higress是如何支持多个集群通讯，没看到相关的介绍

## How could it be?
根据当前的官方文档，看起来像是每一个集群对外暴露一个公网ip，当前A集群的服务跨集群访问B集群的服务，通过B集群的higress实例的路由规则进行匹配，那么，在A集群里面不能B集群的服务的时候，不能直接类似于同一集群下直接grpc调用吗，如果多集群之间服务访问得比较多，那岂不是要配置非常多的路由规则。
##
有没有简单的操作方式呢

**Comment by johnlanni** [comment]
感谢关注 Higress，你看到的是 Higress 做阿里和蚂蚁互通网关的架构图是么，这个场景下，两个集群安全域是隔离的，B集群不会把所有服务都暴露出来，暴露服务都要走安全流程，服务暴露后，A集群的组件可以订阅到这个信息，然后将自身网关的IP mock pub到注册中心，A集群里的服务就可以通过注册中心发现服务，并实现通过网关做 mTLS 来对B集群中的服务进行安全调用。
如果多集群之间服务互通非常频繁，并且对安全的要求不高，其实更建议做底层网络的打通。

**Comment by fengyeall111** [comment]
> 感谢关注 Higress，你看到的是 Higress 做阿里和蚂蚁互通网关的架构图是么，这个场景下，两个集群安全域是隔离的，B集群不会把所有服务都暴露出来，暴露服务都要走安全流程，服务暴露后，A集群的组件可以订阅到这个信息，然后将自身网关的IP mock pub到注册中心，A集群里的服务就可以通过注册中心发现服务，并实现通过网关做 mTLS 来对B集群中的服务进行安全调用。 如果多集群之间服务互通非常频繁，并且对安全的要求不高，其实更建议做底层网络的打通。

那是怎么去管理这个注册中心呢，这个注册中心需要管理多个集群，如果注册中心有问题了，那么，集群之间就通讯不了啊

**Comment by johnlanni** [comment]
可以了解下 Nacos，客户端/服务端都有高可用机制，我们在内部的实践也是配合容灾缓存/推空保护等机制来做的

**Comment by fengyeall111** [comment]
> 可以了解下 Nacos，客户端/服务端都有高可用机制，我们在内部的实践也是配合容灾缓存/推空保护等机制来做的
已经弄清楚流程，感谢
