### ISSUE TITLE
Rancher not works right with Higress.

### ISSUE THREAD

**Issue by jaggerwang** [alibaba/higress#362]
### Ⅰ. Issue Description

After successfuly installed Higress into my ACK cluster and congifured an route following this doc https://higress.io/zh-cn/docs/user/quickstart, the cluster has some problems, such as Rancher agent crash again and again, the existed ingresses becames not working, the nodes cannot be seen in Aliyun web console. Is there anything I'm missing to do?

When run `kubectl get pods`, got some error.

```
shell@Alicloud:~$ kubectl get pods -n cattle-system
E0601 10:33:54.512853    1624 memcache.go:255] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request
E0601 10:33:56.738290    1624 memcache.go:255] couldn't get resource list for custom.metrics.k8s.io/v1beta1: the server is currently unable to handle the request
E0601 10:33:56.796198    1624 memcache.go:106] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request
E0601 10:33:56.877312    1624 memcache.go:106] couldn't get resource list for custom.metrics.k8s.io/v1beta1: the server is currently unable to handle the request
E0601 10:33:57.457092    1624 memcache.go:106] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request
E0601 10:33:57.500064    1624 memcache.go:106] couldn't get resource list for custom.metrics.k8s.io/v1beta1: the server is currently unable to handle the request
E0601 10:33:57.654873    1624 memcache.go:106] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request
E0601 10:33:57.706508    1624 memcache.go:106] couldn't get resource list for custom.metrics.k8s.io/v1beta1: the server is currently unable to handle the request
NAME                                    READY   STATUS    RESTARTS   AGE
cattle-cluster-agent-854869c948-lwzxc   0/1     Pending   0          7m6s
shell@Alicloud:~$ kubectl get pods -n basicai-backend
E0601 10:34:21.473206    1692 memcache.go:255] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request
E0601 10:34:24.876186    1692 memcache.go:255] couldn't get resource list for custom.metrics.k8s.io/v1beta1: the server is currently unable to handle the request
E0601 10:34:24.936207    1692 memcache.go:106] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request
E0601 10:34:25.201906    1692 memcache.go:106] couldn't get resource list for custom.metrics.k8s.io/v1beta1: the server is currently unable to handle the request
E0601 10:34:25.871095    1692 memcache.go:106] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request
E0601 10:34:25.950778    1692 memcache.go:106] couldn't get resource list for custom.metrics.k8s.io/v1beta1: the server is currently unable to handle the request
E0601 10:34:26.861167    1692 memcache.go:106] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request
E0601 10:34:26.912481    1692 memcache.go:106] couldn't get resource list for custom.metrics.k8s.io/v1beta1: the server is currently unable to handle the request
NAME                                                  READY   STATUS    RESTARTS   AGE
admin-648df54b-hzbnv                                  0/1     Pending   0          27m
admin-648df54b-sq648                                  0/1     Pending   0          27m
```

Cluster nodes disappeared.
![image](https://github.com/alibaba/higress/assets/1255011/72875441-4dbf-4b6d-9a78-47486d97c0bc)

Rancher agent crashed again and again.
![image](https://github.com/alibaba/higress/assets/1255011/b2509f4b-3404-41e7-90f2-cac64947a28d)

### Ⅱ. Describe what happened

After delete Higress and remove the added route in Aliyun web console and restart all nodes, the cluster returns to normal.

The route added by Higress.
![image](https://github.com/alibaba/higress/assets/1255011/a7b47a69-f942-417b-8d48-ff250d0f8ec4)

### Ⅵ. Environment:

- Higress version:  1.0
- Kubernetes version : Aliyun ACK 1.22.15-aliyun.1
- Others:

**Comment by johnlanni** [comment]
@jaggerwang Duplicate question, not related to higress, needs to troubleshoot rancher issues, has been moved to discussion: https://github.com/alibaba/higress/discussions/360

**Comment by jaggerwang** [comment]
@johnlanni 你们这关闭 Issue 也太随意了！怎么就跟 Higress 没关系，Rancher Agent 只是其中的一个表象，即便 Rancher Agent 正常，其它集群问题了，你们就选择忽视了？明显就是安装 Higress 之后集群网络出了问题，才导致 Rancher 失联、节点失联等一系列问题。昨天提了一个 Issue 也是被你们立即关闭了。Rancher Agent 我们都运行一年多了，一直都正常，怎么就正好在昨天安装 Higress 后就不能正常工作了？

**Comment by johnlanni** [comment]
> @johnlanni 你们这关闭 Issue 也太随意了！怎么就跟 Higress 没关系，Rancher Agent 只是其中的一个表象，即便 Rancher Agent 正常，其它集群问题了，你们就选择忽视了？明显就是安装 Higress 之后集群网络出了问题，才导致 Rancher 失联、节点失联等一系列问题。昨天提了一个 Issue 也是被你们立即关闭了。Rancher Agent 我们都运行一年多了，一直都正常，怎么就正好在昨天安装 Higress 后就不能正常工作了？

是转到 discussion 讨论了哈

**Comment by johnlanni** [comment]
disucssion里已经回复你了，需要定位你的 rancher agent crash 的具体原因，不然根据上面你提供的信息，无法判断任何问题呀

**Comment by jaggerwang** [comment]
如果都转到 Discussion 讨论，那大家还来这里花时间提 Issue 干嘛。昨天那个 Issue 转 Discussion 我还可以理解，因为那个 Issue 的描述可能会让你们以为是 Rancher Agent 的问题，但今天这个 Issue 已经说得够清楚了吧。

**Comment by johnlanni** [comment]
今天这个issue内容跟昨天的一样啊。。都得先定位 rancher 自身的问题才能排查，crash的时候得看 rancher agent 容器的 previous log，这个内容提供出来，我可以一起帮忙分析下

**Comment by jaggerwang** [comment]
反馈了，但应该没什么帮助，Rancher Agent 退出也是因为集群网络出现了问题，你们最好测试一下 ACK 里有安装其自带的 Nginx Ingress Controller 组件的情况下，再安装 Higress 是否会出现网络冲突。

**Comment by johnlanni** [comment]
已经在 discussion 里答复，是 rancher 的 bug，跟有没有安装 Nginx Ingress Controller 没有关系。
https://github.com/alibaba/higress/discussions/360

**Comment by johnlanni** [comment]
issue 我已经 open，不过这个问题要解决，需要 Rancher 那边修复，可以给 Rancher 提个issue，关联下此 issue

**Comment by jaggerwang** [comment]
@johnlanni 要不你们提一下吧，看不太懂你说的 [backend.service must have value](https://github.com/alibaba/higress/discussions/360) 是怎么回事。这个也算是 Higress 跟 Rancher 的不兼容问题吧，因为不安装 Higress 集群是没有问题的，或者 Higress 这边有没有办法绕过此问题。

**Comment by johnlanni** [comment]
ingress 的 backend 可以有多种类型，包括 backend.service，以及 backend.resource；Rancher 没有考虑到 backend.resource  的情况，直接去取 ingress 里 backend.service.name，导致访问空指针 panic 了。

可以的，我后面给rancher提一个

**Comment by johnlanni** [comment]
https://github.com/rancher/rancher/pull/41726
@jaggerwang 给rancher提了PR，不一定能很快合并进去，你可以尝试下基于这个修复自己构建一个 cluster agent

**Comment by johnlanni** [comment]
Already fixed in rancher 2.7
