### ISSUE TITLE
Need api to dynamic configure plugins, such as add or remove consumers of key-auth plugin.

### ISSUE THREAD

**Issue by jaggerwang** [alibaba/higress#368]
## Why do you need it?
Our platform opened some apis to users, and we decide to use api key to protect our apis.  Every user needs to apply an api key in our platform first, and call apis with this api key, so we need to dynamic configure consumers of key-auth plugin, but I not found any documents about this.

## How could it be?
Configure plugin through api or using Kubernetes CRD.

**Comment by CH3CHO** [comment]
The API design is not finalized yet. But for now, you can use http://higress-console-domain/swagger-ui/index.html to check out API document generated by Swagger.

**Comment by jaggerwang** [comment]
OK. Is there any plan or when to finalize the api design?

**Comment by CH3CHO** [comment]
> OK. Is there any plan or time deadline to finalize the api design? BTW. the [demo](http://demo.higress.io/) console is denied to access right now. As there have conflicts between Higrress and Rancher agent, so we cannot install Higress to our cluster to experience Higress.

The deadline hasn't been settled yet. The demo console will be fixed soon. I will let you know once it comes alive.

**Comment by johnlanni** [comment]
@jaggerwangThe demo console has been restored.

**Comment by jaggerwang** [comment]
![image](https://github.com/alibaba/higress/assets/1255011/33f22233-f458-413b-91d6-4660f5d91015)
There is almost no documentation about each api, can you guys give an example to configure a route with key-auth plugin.

**Comment by johnlanni** [comment]
@jaggerwang 可以进钉钉群，目前这块文档还未最终定稿，但有内部API开发文档，在钉钉群文档里

**Comment by johnlanni** [comment]
![image](https://github.com/alibaba/higress/assets/6763318/b04df289-cc25-48cc-bfd5-77d362a57118)

**Comment by johnlanni** [comment]
我们不会提供Console的Admin API，这块的API后面可能会跟随版本发生变化，但底层的Ingress/Gateway API模型是不变的。可以基于Console的Java SDK进行集成，SDK封装了对Ingresss/Gateway API的操作，这块可以补充下文档 @CH3CHO 
https://github.com/higress-group/higress-console/tree/main/backend/sdk

**Comment by CH3CHO** [comment]
> 我们不会提供Console的Admin API，这块的API后面可能会跟随版本发生变化，但底层的Ingress/Gateway API模型是不变的。可以基于Console的Java SDK进行集成，SDK封装了对Ingresss/Gateway API的操作，这块可以补充下文档 @CH3CHO https://github.com/higress-group/higress-console/tree/main/backend/sdk

后续在完善 SDK 的配置机制后会提供相关文档。
