### ISSUE TITLE
higress环境通过operator部署

### ISSUE THREAD

**Issue by wojesen** [alibaba/higress#370]
## Why do you need it?
目前higress通过helm部署，带来的问题：
1 需要运维人员手动部署
2 当环境出现问题时，需要人工介入
3 如果部署了多个higress环境，不太好直观的去查看集群里的higress环境

## How could it be?
建议通过operator机制实现higress的部署，运维/开发人员在管理环境的时候更多的时候只需要关注crd即可；对于环境的稳定性也有一定程度提升。

## Other related information
其他类似产品的案例：https://github.com/Kong/kong-operator

**Comment by Charlie17Li** [comment]
pls refer : https://github.com/higress-group/higress-operator

**Comment by johnlanni** [comment]
@wojesen operator模式运维已经支持了，试用下看，是否满足你的需求
