### ISSUE TITLE
在不需要完整istio的情况下，如何集成aeraki 到higress

### ISSUE THREAD

**Issue by someview** [alibaba/higress#372]
在不需要完整istio的情况下，如何集成aeraki或者 meta-protocol-envoy 到higress中呢，能够支持私有的协议流量的治理。
由于higress和aeraki的流程原理，依赖关系不了解，不知道如何如何下手，寻求帮助

**Comment by johnlanni** [comment]
我对aeraki没有很多了解，看看社区其他同学有了解的吗 cc @Xunzhuo
