### ISSUE TITLE
想实现多服务版本之间可以设置流量的权重。

### ISSUE THREAD

**Issue by nlg521** [alibaba/higress#381]
1）同一个服务如何支持多个版本？
2）不同服务版本之间如何设置权重？

**Comment by johnlanni** [comment]
https://github.com/alibaba/higress/blob/main/samples/nacos-discovery/multi-destination.yaml

参考下这个注解，可以就创建两个不同的 service ，通过label区分不同版本的服务。

**Comment by nlg521** [comment]
非常感谢
