### ISSUE TITLE
需要提供hostNetwork等运维模式的部署操作文档

### ISSUE THREAD

**Issue by nlg521** [alibaba/higress#382]
使用场景，在没有外部 lb 的情况下， 能否支持通过宿主机的端口来实现网关路由。

**Comment by johnlanni** [comment]
https://github.com/alibaba/higress/blob/main/helm/core/values.yaml#L368

这个helm参数可以控制:

```bash
helm upgrade higress -n higress-system higress.io/higress --reuse-values --set higress-core.gateway.hostNetwork=true
```

**Comment by johnlanni** [comment]
我们需要把一些常用的运维参数，例如网络模式调整，cpu内存replica等资源调整整理到这个文档，看看是否有社区同学认领这个任务：
https://higress.io/zh-cn/docs/user/configurations

**Comment by CH3CHO** [comment]
> 我们需要把一些常用的运维参数，例如网络模式调整，cpu内存replica等资源调整整理到这个文档，看看是否有社区同学认领这个任务： https://higress.io/zh-cn/docs/user/configurations

目前已经有一部分列在这里了：https://higress.io/zh-cn/docs/ops/deploy-by-helm#%E5%AE%89%E8%A3%85%E5%8F%82%E6%95%B0

**Comment by Fkbqf** [comment]
pls assign me～

**Comment by nlg521** [comment]
> https://github.com/alibaba/higress/blob/main/helm/core/values.yaml#L368
> 
> 这个helm参数可以控制:
> 
> ```shell
> helm upgrade higress -n higress-system higress.io/higress --reuse-values --set higress-core.gateway.hostNetwork=true
> ```

执行完成后，一致显示这类错误
2023-12-25T05:47:42.790872Z	warn	Envoy proxy is NOT ready: config received from XDS server, but was rejected: cds updates: 1 successful, 0 rejected; lds updates: 0 successful, 1 rejected
请问怎么处理下？

**Comment by johnlanni** [comment]
这个是lds被拒绝了，要看下失败的原因，你看下这个日志上方应该有详细的原因

**Comment by johnlanni** [comment]
有种可能是没有再host上监听80和443的权限，需要给容器设置特权权限

**Comment by nlg521** [comment]
80 ，443 被 nginx 占了，这个可以改成其它端口吗？

**Comment by johnlanni** [comment]
这个目前还没支持配置，我先建个issue跟踪下
