### ISSUE TITLE
本地部署时，报istio-ca-root-cert的相关告警

### ISSUE THREAD

**Issue by Jumping67** [alibaba/higress#384]
具体warning信息为：
   Unable to attach or mount volumes: unmounted volumes=[istio-ca-root-cert], unattached volumes=[kube-api-access-g9zd6 istio-token config istio-ca-root-cert istio-data podinfo proxy-socket]: timed out waiting for the condition
   MountVolume.SetUp failed for volume "istio-ca-root-cert" : configmap "higress-ca-root-cert" not found
   Unable to attach or mount volumes: unmounted volumes=[istio-ca-root-cert], unattched volumes=[podinfo proxy-socket kube-api-access-g9zd6 istio-token config istio-ca-root-cert istio-data]: timed out waiting for the condition

**Comment by johnlanni** [comment]
看下 higress-system 下是否有 pod 因为资源不足没启动，kubectl describe 看下

**Comment by johnlanni** [comment]
@qwehua-github higress-controller pod启动成功了吗

**Comment by pepesi** [comment]
千里之行，卡在第一步。
通过helm安装,版本1.4.1,参考文档
https://higress.io/zh-cn/docs/ops/deploy-by-helm/#%E5%AE%89%E8%A3%85-higress

<img width="709" alt="image" src="https://github.com/alibaba/higress/assets/12043478/0a98399d-1fcf-4f82-9e3c-33de031464a3">

**Comment by johnlanni** [comment]
@pepesi higress-controller没有ready？

**Comment by pepesi** [comment]
@johnlanni 没有，健康检测过不去，这个证书是它创建的吗

**Comment by johnlanni** [comment]
是的，log看下原因

**Comment by pepesi** [comment]
我的环境是一个kind 集群，k8s 1.25.x，似乎是我环境的问题
<img width="717" alt="image" src="https://github.com/alibaba/higress/assets/12043478/193ad559-7f34-4717-a3a2-bcbadcad0d87">
似乎是我kind集群的问题，探针过不去

**Comment by pepesi** [comment]
删除集群，重建了下，好了
@johnlanni thanks a lot
