### ISSUE TITLE
Higress requests for too many resources for start

### ISSUE THREAD

**Issue by wonderflow** [alibaba/higress#387]
## Why do you need it?
 Is your feature request related to a problem? Please describe in details

I'm trying higress in my demo cluster which don't have many resources. I see higress request for "2 CPU and 2 Gi memory" for start in helm chart, it costs too much that I can't start the pods.

Why higress need so many resources for start?

## How could it be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

I hope we can set the request to be lower, e.g. "0.5 cpu and 0.5 Gi mem".

**Comment by johnlanni** [comment]
The default resource configuration 2c2g*2 is to cover the resource requirements of QPS in most business scenarios. We are worried that configuring too small resource requirements (or only the request part) will cause some users who are not familiar with k8s to ignore resource restrictions, and then step on the pit (competing for resources with business pods, etc.). We will provide operator CRD in the future to facilitate users to do more clear resource operation and maintenance.
