### ISSUE TITLE
invalid bearer token, service account token has expired

### ISSUE THREAD

**Issue by liyongxian** [alibaba/higress#390]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via [ASRC](https://security.alibaba.com/)(Alibaba Security Response Center) where the issue will be triaged appropriately.**

- [ ] I have searched the [issues](https://github.com/alibaba/higress/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

![image](https://github.com/alibaba/higress/assets/18571576/8b4cb3c2-65fa-42a7-b820-336e6b4b58cb)

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. helm install higress,and console ui is ok, "服务列表" 能查询k8s的Service
2. 过一段时间后，发现"服务列表" 无法查询服务列表了。
3. controller logs：
  **error	Failed to authenticate /debug/registryz [Authenticator ClientCertAuthenticator: no client certificate is presented Authenticator KubeJWTAuthenticator: failed to validate the JWT from cluster "": the service account authentication returns an error: [invalid bearer token, service account token has expired]]**

### Ⅵ. Environment:

- Higress version:   1.0.1
- OS : Ubuntu 20.04.3 LTS
- Others:
![image](https://github.com/alibaba/higress/assets/18571576/af79451c-0bdf-41b8-be94-7e18f7884124)

**Comment by CH3CHO** [comment]
请问是安装到正式的 K8s 集群还是本地集群（如 Kind）呢？能否提供一下完整的安装命令？

**Comment by CH3CHO** [comment]
另外，现在还有这个问题吗？如果还有的话，那麻烦登录到Console的Pod里，把下面两个文件的内容发出来。这两个Token都是K8s内部认证用的，没有安全风险。

/var/run/secrets/access-token/token
/var/run/secrets/kubernetes.io/serviceaccount/token

**Comment by liyongxian** [comment]
你好，k8s集群。higress-core的values主要配置：
![image](https://github.com/alibaba/higress/assets/18571576/b0cd99c0-66e8-42d5-bdd1-e0a7272f7a2b)

**Comment by liyongxian** [comment]
**/var/run/secrets/access-token/token：**
eyJhbGciOiJSUzI1NiIsImtpZCI6InVEeU5POHk5eTNGQ0JsVDYyS3BhY2hEcEJrS05zQzBzQ2Z2b1hxMi1nTVEifQ.eyJhdWQiOlsiaXN0aW8tY2EiXSwiZXhwIjoxNjg3MzQxNjcwLCJpYXQiOjE2ODczMzgwNzAsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJoaWdyZXNzLXN5c3RlbSIsInBvZCI6eyJuYW1lIjoiaGlncmVzcy1jb25zb2xlLTg1ZmI1NTg0ZGYtd2ZxczgiLCJ1aWQiOiI4OGIyODYwMy0yNDZlLTQ0MGQtODI0My1iNDk0OWJhZWJmYWYifSwic2VydmljZWFjY291bnQiOnsibmFtZSI6ImhpZ3Jlc3MtY29uc29sZSIsInVpZCI6IjMzZWIzM2NjLTA3OWQtNGU0NC05OTMxLTVmMjRhMGUxZWJhMCJ9fSwibmJmIjoxNjg3MzM4MDcwLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6aGlncmVzcy1zeXN0ZW06aGlncmVzcy1jb25zb2xlIn0.Ltyjdb2rDVorRA6DW3JYjT2bwXtJuyWIrpQnJh4r4CnalbZHPrRHMC7eg-0XDChS8j71K-70BML83i2hKzXejaXl4pVqwpGx-UQIMnctcdNsRvlKibQEp1V3gAMUvm1ySWlsVmFuiyLxWL24j-i9mSJ9Z70SsMDy5FkkaoPG_SAEY8F88zSGL6dYlsNDw_U_SahZGbzgqwIwUmTiE-7OjNhVkdG3i7cyEOEAKUDCWDmlZYUd19PmHHDnM0sEF6H3X5gMXLz5m7-oFNMntjNjZSv7-1Mk_66UPmFf0murCeqK_NLWPqSoawQVAQ-Gv8KEsxYUr5vj4l5cuHWwyzxSMA
**/var/run/secrets/kubernetes.io/serviceaccount/token：**
eyJhbGciOiJSUzI1NiIsImtpZCI6InVEeU5POHk5eTNGQ0JsVDYyS3BhY2hEcEJrS05zQzBzQ2Z2b1hxMi1nTVEifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoxNzE4ODc0MDcwLCJpYXQiOjE2ODczMzgwNzAsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJoaWdyZXNzLXN5c3RlbSIsInBvZCI6eyJuYW1lIjoiaGlncmVzcy1jb25zb2xlLTg1ZmI1NTg0ZGYtd2ZxczgiLCJ1aWQiOiI4OGIyODYwMy0yNDZlLTQ0MGQtODI0My1iNDk0OWJhZWJmYWYifSwic2VydmljZWFjY291bnQiOnsibmFtZSI6ImhpZ3Jlc3MtY29uc29sZSIsInVpZCI6IjMzZWIzM2NjLTA3OWQtNGU0NC05OTMxLTVmMjRhMGUxZWJhMCJ9LCJ3YXJuYWZ0ZXIiOjE2ODczNDE2Nzd9LCJuYmYiOjE2ODczMzgwNzAsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpoaWdyZXNzLXN5c3RlbTpoaWdyZXNzLWNvbnNvbGUifQ.pq5hgWBQuyXaU0JhK4S8G8zwEXdwOxBuEior-tln3uaIjQ9hO0O2ZSjrcdRUis1-1BdxdyWAjL5DmRYXJtSqWmXe4QEb3buj_U28mFcCWh_8RzWmR-jKQkDBb2ByR5B_PrzKV7pgLAfmCemgaU-De2bi8LQGxYrjNITYeal6SpyB1lACzmR6lo6fZm3Ob7QOmFSbCtm4QmDOYP4h5nhGVifOvOLXkl0AsbTi1LcMpHZ7wrox58y-5gW6iQQgoovOF49PczU7H_HvCFiK-xntrfpN9yPpMFXYD5xIMd-mdOUiUb3qfYhUDH44PBQ3EXB2n5WHCS21jdjxWJmT4jq2_Q

Thanks.

**Comment by CH3CHO** [comment]
这两个token看上去都没有过期，现在还有auth不过的问题吗？

**Comment by liyongxian** [comment]
“服务列表”还是不显示。多谢。
![image](https://github.com/alibaba/higress/assets/18571576/dfb724a1-b998-4e74-b29f-7a940dd0d0c2)

**Comment by CH3CHO** [comment]
麻烦提供一下 console deployment 的完整 YAML。目前快速解决的话可以试试把 console pod 删了让他重建。理论上应该是好的。如果还不好的话，大概率就是 K8s 有问题了。

**Comment by liyongxian** [comment]
console的pod删了重建可以了，console deployment主要yaml：
![image](https://github.com/alibaba/higress/assets/18571576/18018d63-7f56-43d4-ab62-0cd7c3517361)

**Comment by CH3CHO** [comment]
好的，我先本地尝试重现一下这个问题。

**Comment by liyongxian** [comment]
![image](https://github.com/alibaba/higress/assets/18571576/e160d296-b466-48bf-baba-005c097abcc0)

**Comment by CH3CHO** [comment]
有一个小问题，你们看一下各台服务器的时间是不是不对。上面你贴的第一个Token，显示的是北京时间 2023/6/21 17:01:10 签发，这还是未来呢。。。你可以直接把 Token 内容贴到 https://jwt.io/ 里进行解码。

![image](https://github.com/alibaba/higress/assets/2909796/b1a4030a-7f95-4748-b4b3-0da1f260617c)

**Comment by CH3CHO** [comment]
> 有一个小问题，你们看一下各台服务器的时间是不是不对。上面你贴的第一个Token，显示的是北京时间 2023/6/21 17:01:10 签发，这还是未来呢。。。你可以直接把 Token 内容贴到 https://jwt.io/ 里进行解码。
> 
> ![image](https://user-images.githubusercontent.com/2909796/247472024-b1a4030a-7f95-4748-b4b3-0da1f260617c.png)

所以上面的 expired 可能不是说过期，而是还未生效。

**Comment by liyongxian** [comment]
k8s的master节点系统时间和worker节点的不一致，应该是这个原因。多谢！

**Comment by CH3CHO** [comment]
> k8s的master节点系统时间和worker节点的不一致，应该是这个原因。多谢！

好的~ 如果没有其他问题的话，这个 issue 麻烦帮忙 close，谢谢！
