### ISSUE TITLE
性能测试

### ISSUE THREAD

**Issue by liyongxian** [alibaba/higress#393]
## Why do you need it?
 Is your feature request related to a problem? Please describe in details
有higress 性能测试报告吗？对标 nginx ingress 和apisix，在qps和延迟方面，能提高多少。多谢。

## How could it be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by johnlanni** [comment]
https://mp.weixin.qq.com/s/33HWhqwebuEAEq_9T8n80A

可以看下这篇里的报告，不过也跟 nginx ingress 的版本有关系，最新的版本性能似乎有优化，可以具体压测看看
