### ISSUE TITLE
支持通过 helm 参数集成开源日志分析组件（Support the integration of open source log analysis components through helm parameters）

### ISSUE THREAD

**Issue by johnlanni** [alibaba/higress#43]
## Why do you need it?

提供开箱即用的网关日志收集和分析的能力

---

Provides out-of-the-box gateway log collection and analysis capabilities

## Other related information
higress doc: https://higress.io/zh-cn/docs/ops/log.html
envoy doc: https://www.envoyproxy.io/docs/envoy/latest/configuration/observability/access_log/overview

**Comment by erenming** [comment]
Hi, i'd like to resolve this issue, can you assign it to me?

**Comment by CraigMChen** [comment]
Hi, i'd like to resolve this issue, can you assign it to me?

**Comment by zirain** [comment]
it would be better to support OpenTelemetry logger
