### ISSUE TITLE
The fallback function is incorrectly limited to Envoy versions

### ISSUE THREAD

**Issue by PerforMance308** [alibaba/higress#431]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via [ASRC](https://security.alibaba.com/)(Alibaba Security Response Center) where the issue will be triaged appropriately.**

- [x] I have searched the [issues](https://github.com/alibaba/higress/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
The fallback function is incorrectly limited to Envoy versions.

### Ⅱ. Describe what happened
The fallback function is limited to Envoy of v1.20.6, while our Envoy version is v1.20, as a result, the fallback feature does not work

```
Just paste your stack trace here!
```

### Ⅲ. Describe what you expected to happen
https://github.com/alibaba/higress/blob/a392d0cf343e38b8b2089c4697ed8d356c29b4f9/istio/1.12/patches/istio/20221027-init.patch#L6208

Either remove the version check or change the version limitation to v1.20

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- Higress version:  
- OS :
- Others:

**Comment by PerforMance308** [comment]
I will take this issue and solve the problem

**Comment by SpecialYang** [comment]
If the initial version higress-data-plane support fallback, we can remove this version check directly.
