### ISSUE TITLE
TCP/UDP Proxy

### ISSUE THREAD

**Issue by liyongxian** [alibaba/higress#444]
## Why do you need it?
 Is your feature request related to a problem? Please describe in details
Using  higress supports 4 lays proxy for tcp/udp.
Thanks.

## How could it be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by johnlanni** [comment]
We will support this using the Gateway API.

**Comment by Windforce17** [comment]
How to config TCP/udp proxy  with standalone mode?

**Comment by CH3CHO** [comment]
> How to config TCP/udp proxy with standalone mode?

You can create corresponding resources in Nacos or your config folder, depending on your chosen configuration method.
