### ISSUE TITLE
在开启http2时，多个域名复用证书，会出现SNI和请求头Host不一致的情况

### ISSUE THREAD

**Issue by hyunrealshadow** [alibaba/higress#449]
### Discussed in https://github.com/alibaba/higress/discussions/448

<div type='discussions-op-text'>

<sup>Originally posted by **hyunrealshadow** July 24, 2023</sup>
我有一个泛域名证书，通过console更新到了控制台中，根据不同服务分配了不同的子域名
但是这些子域名中只会有一个能访问，其他都会返回404
目前用的是一个k3s单节点集群
请问以下配置哪里可能有问题？
![higress_1](https://github.com/alibaba/higress/assets/36305150/9d3bb1aa-800e-4f9f-9ef5-f12439484667)
![1690179397014](https://github.com/alibaba/higress/assets/36305150/41c0c851-2a27-4709-a15b-4dc1efa5ca33)
![image](https://github.com/alibaba/higress/assets/36305150/ab8fff4a-3188-4f80-915d-d9b994f5828f)
</div>

根据钉钉群聊，相关日志如下
```
{"authority":"weblate.hide.cn","bytes_received":"0","bytes_sent":"0","downstream_local_address":"10.42.0.33:443","downstream_remote_address":"10.42.0.30:11733","duration":"0","istio_policy_status":"-","method":"GET","path":"/","protocol":"HTTP/2","request_id":"d4f591ac-e782-4f8f-a155-c51cd6124116","requested_server_name":"bitwarden.hide.cn","response_code":"404","response_flags":"NR","route_name":"-","start_time":"2023-07-26T03:14:52.533Z","trace_id":"-","upstream_cluster":"-","upstream_host":"-","upstream_local_address":"-","upstream_service_time":"-","upstream_transport_failure_reason":"-","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36 Edg/115.0.1901.183","x_forwarded_for":"10.42.0.30"}
```

**Comment by johnlanni** [comment]
浏览器会对不同域名但相同证书的请求复用一条连接，这就导致请求SNI和Host头不一致了。
目前 Higress 会将一个域名转换为一个 Istio Gateway 资源和一个 Istio VirtualService 资源，并将二者关联起来。这样的模型比较简单易于管理。但在处理HTTPS请求时，不同域名是走到独立的[ listener filter chain ](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/listener/v3/listener_components.proto#envoy-v3-api-msg-config-listener-v3-filterchain)中，匹配完SNI只能拿到当前域名关联的RDS配置，没有同证书下其他域名的RDS，所以H2场景下就会有这个404问题。
更合理的方式是将相同证书下的多个域名转换为一个 Istio Gateway 资源，每个域名有一个 istio VirutalService 资源。这样就可以解决这个问题。

**Comment by 2456868764** [comment]
please assign it to me

**Comment by gengleilei** [comment]
还有一种配置方法，在创建域名时配置一个泛域名，这个泛域名与证书里面的泛域名保持一致，然后在路由配置中增加一个header匹配，匹配的key是 authority ，value 是精确域名

**Comment by haimaren** [comment]
我遇到了同样的问题,我在使用阿里云云网关的时候有http2-misdirect插件支持,请问higress多久能支持这块功能呢?

**Comment by johnlanni** [comment]
@haimaren 可以先参考上面评论中的方式解决。
现在开源最新版本，helm 设置下参数 --set global.enableSRDS=true，可以解决这个问题。1.3.4正式release后，会作为默认方式。商业版也会跟进。
