### ISSUE TITLE
自定义插件没有生效

### ISSUE THREAD

**Issue by Everything1sPossible** [alibaba/higress#455]
使用higress1.1.0版本，自定义插件没有生效，查了下higress-controller pod的容器日志，看到有个报错
<img width="1032" alt="image" src="https://github.com/alibaba/higress/assets/34228107/e1e304ab-5abb-4953-9454-82892f135602">
下面是我在控制台新增插件后自动生成的crd yaml
<img width="596" alt="image" src="https://github.com/alibaba/higress/assets/34228107/1de98042-a277-407b-b560-7ba061ab4aff">
Dockerfile也是最简单版本
<img width="578" alt="image" src="https://github.com/alibaba/higress/assets/34228107/455860de-00e1-422f-8635-85403527eaa5">
插件代码我就不贴了，是文档的最简单示例。

**Comment by johnlanni** [comment]
目前不允许路由下空配置，这块我优化下，可以先随便配点配置

**Comment by Everything1sPossible** [comment]
收到 谢谢

**Comment by Everything1sPossible** [comment]
又找到一个新问题，在非k8s环境下，自定义插件无法生效，且执行阶段属性回显丢失
<img width="992" alt="image" src="https://github.com/alibaba/higress/assets/34228107/a087c2e9-3eee-46c1-890d-2c8bffc6d5cb">
查了下nacos的配置，没有phase属性
<img width="1435" alt="image" src="https://github.com/alibaba/higress/assets/34228107/21acedb0-bbd2-4871-8535-5c324149fcc0">

**Comment by CH3CHO** [comment]
> 又找到一个新问题，在非k8s环境下，自定义插件无法生效，且执行阶段属性回显丢失 <img alt="image" width="992" src="https://user-images.githubusercontent.com/34228107/257142008-a087c2e9-3eee-46c1-890d-2c8bffc6d5cb.png"> 查了下nacos的配置，没有phase属性 <img alt="image" width="1435" src="https://user-images.githubusercontent.com/34228107/257142095-21acedb0-bbd2-4871-8535-5c324149fcc0.png">

这个问题我看一下。

**Comment by CH3CHO** [comment]
> 又找到一个新问题，在非k8s环境下，自定义插件无法生效，且执行阶段属性回显丢失 <img alt="image" width="992" src="https://user-images.githubusercontent.com/34228107/257142008-a087c2e9-3eee-46c1-890d-2c8bffc6d5cb.png"> 查了下nacos的配置，没有phase属性 <img alt="image" width="1435" src="https://user-images.githubusercontent.com/34228107/257142095-21acedb0-bbd2-4871-8535-5c324149fcc0.png">

你是不是配的默认阶段？默认阶段的话是没有的。

![image](https://github.com/alibaba/higress/assets/2909796/7372c306-79da-4a56-ad46-6f27464e5428)

**Comment by Everything1sPossible** [comment]
对的，我也试了下，别的阶段是有这个属性了，感觉这块你们是不是和k8s环境下保持一致，要不然会造成点误解。另外一个问题就是这个自定义插件我在k8s环境下是生效的，但是非k8s环境下没有生效。。

**Comment by CH3CHO** [comment]
> 对的，我也试了下，别的阶段是有这个属性了，感觉这块你们是不是和k8s环境下保持一致，要不然会造成点误解。另外一个问题就是这个自定义插件我在k8s环境下是生效的，但是非k8s环境下没有生效。。

"别的阶段是有这个属性了，感觉这块你们是不是和k8s环境下保持一致，要不然会造成点误解。" Istio 官方的 WasmPlugin CRD 里的 phase 字段也是可以不填的。这里的默认阶段就是和 Istio 的保持一致的。

非 K8s 环境没有生效我尝试在本地模拟一下看看。

**Comment by CH3CHO** [comment]
> 对的，我也试了下，别的阶段是有这个属性了，感觉这块你们是不是和k8s环境下保持一致，要不然会造成点误解。另外一个问题就是这个自定义插件我在k8s环境下是生效的，但是非k8s环境下没有生效。。

我本地用 Custom Response 的镜像建了一个自定义插件，测下来是可以正常生效的。

![image](https://github.com/alibaba/higress/assets/2909796/a2f5724f-d50d-4aeb-afac-fe0eefd11372)

![image](https://github.com/alibaba/higress/assets/2909796/23c42ec9-0e73-44d8-a72a-a26a1d89d624)

你那边本地不能生效的问题建议看一下 gateway 上的日志和生效的配置，确认是配置没推下来还是镜像拉不到，再或者是插件运行有问题。

**Comment by Everything1sPossible** [comment]
是同一个插件，镜像也是同一个，k8s环境下是正常的，非k8s环境下就无法生效。。请问非k8s环境gateway日志如何查看啊，只找到一个access_log日志文件。。

**Comment by CH3CHO** [comment]
> 是同一个插件，镜像也是同一个，k8s环境下是正常的，非k8s环境下就无法生效。。请问非k8s环境gateway日志如何查看啊，只找到一个access_log日志文件。。

`./bin/logs.sh gateway` 试试。另外，你们的插件是什么功能，我这边可以用你们的插件本地测一下吗？

**Comment by Everything1sPossible** [comment]
非k8s环境安装最新版本，自定义插件可以生效了，辛苦老哥 @CH3CHO
