### ISSUE TITLE
CI 流程增加 linters 校验，如 goimports/gosec/gofmt/... (Add linters check for CI)

### ISSUE THREAD

**Issue by SpecialYang** [alibaba/higress#48]
We should add code format tool and check the code style before merging pr.

**Comment by xcbeyond** [comment]
assign to me

**Comment by johnlanni** [comment]
Already implemented in #126, thanks to @Xunzhuo

**Comment by Xunzhuo** [comment]
Part of https://github.com/alibaba/higress/issues/48
