### ISSUE TITLE
什么时候支持dubbo3.x？

### ISSUE THREAD

**Issue by 283288675** [alibaba/higress#481]
## Why do you need it?
 Is your feature request related to a problem? Please describe in details
什么时候支持dubbo3.x？

## How could it be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by sjtuzbk** [comment]
1. Dubbo3.x也是支持的，前提是使用dubbo协议，triple协议不支持协议转换
2. 最新的Dubbo3.3.0版本已经支持了将Dubbo服务以Restful接口暴露，这时候直接用网关对接注册中心将请求转发到Dubbo服务上即可，无需做协议转换
