### ISSUE TITLE
WasmPlugin: Do some transform to Request and Response

### ISSUE THREAD

**Issue by Hinsteny** [alibaba/higress#490]
## Why do you need it?
 Is your feature request related to a problem? Please describe in details
Some time, we need do simple transform before they reach the upstream server or before returning the response to the client. 

## How could it be?
Request protocols need support: grpc, grpcs, http, https, tcp, udp, ws, etc
Simple transform like remove、rename、replace、add、append.

## Other related information
We can refer to, 
https://docs.konghq.com/hub/kong-inc/request-transformer/
https://docs.konghq.com/hub/kong-inc/response-transformer/

**Comment by WeixinX** [comment]
@Hinsteny @johnlanni 

想请问下这里的"需要支持的协议"是什么含义？我理解的这些转换操作只会发生在 http(s) 中？

I would like to ask what is the meaning of "Request protocols need support"? I understand that these transform operations only happen in http(s)?

✋ Thanks ~

**Comment by johnlanni** [comment]
@Hinsteny 是的，只要先支持 http 就可以

**Comment by johnlanni** [comment]
https://github.com/envoyproxy/envoy/blob/72bf41fb0ecc039f196be02f534bfc2c9c69f348/source/extensions/common/wasm/context.cc#L762-L763

@WeixinX 是的，这里有个TODO，我来完善下，dedup这个可以先暂缓一下
https://github.com/envoyproxy/envoy/blob/main/source/extensions/common/wasm/context.cc#L751-L752

**Comment by WeixinX** [comment]
@johnlanni 实际实现的时候 dedupe 是可以完成的，估计同名头部是 [][2]string{{"x-foo", "a"}, {"x-foo", "b"}}，所以都能拿到不影响实现 🎉：

Transformer 配置：
```yaml
type: request
dots_in_keys: false
rules:
  - operate: dedupe
    headers:
      - kv: x-hi:RETAIN_FIRST
      - kv: x-foo:RETAIN_LAST
      - kv: x-bar:RETAIN_UNIQUE
    querys:
      - kv: k1:RETAIN_UNIQUE
      - kv: k2:RETAIN_FIRST
      - kv: k3:RETAIN_LAST
```

发送请求：

```bash
$ curl -v -H 'x-hi: 1' -H 'x-hi: 2' -H 'x-hi: 3' \
> -H 'x-foo: a' -H 'x-foo: b' -H 'x-foo: c' \
> -H 'x-bar: q' -H 'x-bar: w' -H 'x-bar: e' \
> 127.0.0.1:10000/get?k1=1\&k1=2\&k1=3\&k2=a\&k2=b\&k2=c\&k3=q\&k3=w\&k3=e

# 请求
> GET /get?k1=1&k1=2&k1=3&k2=a&k2=b&k2=c&k3=q&k3=w&k3=e HTTP/1.1
> Host: 127.0.0.1:10000
> User-Agent: curl/7.68.0
> Accept: */*
> x-hi: 1
> x-hi: 2
> x-hi: 3
> x-foo: a
> x-foo: b
> x-foo: c
> x-bar: q
> x-bar: w
> x-bar: e

# 响应
< HTTP/1.1 200 OK
< server: envoy
...
<
{
  "args": {
    "k1": [
      "1",
      "2",
      "3"
    ],
    "k2": "a",
    "k3": "e"
  },
  "headers": {
    ...
    "X-Bar": "q,w,e",
    "X-Foo": "c",
    "X-Hi": "1"
  },
  ...
  "url": "https://127.0.0.1:10000/get?k1=1&k1=2&k1=3&k2=a&k3=e"
}
```

**Comment by johnlanni** [comment]
哦 是使用的 getHeaderMapPairs 对吧，直接取出全部 header
