### ISSUE TITLE
ingress通过注解实现的header匹配机制支持对pseudo header进行匹配

### ISSUE THREAD

**Issue by 18612864207** [alibaba/higress#503]
域名的模糊匹配只支持*.xx.com的格式，是否能支持test*.xx.com的格式呢

我的使用场景是，test01.xx.com、test02.xx.com...test100.xx.com后端指向的同样的服务，如果我这套系统下有50个path，那我需要给每个域名都配置50个path，总共就是100*50=5000个路由，如果后期其中一个path有调整，那我也需要对每个域名都做调整，是一个极其困难的事，所以是否可以增加，test*.xx.com或者*test.xx.com之类的格式呢，我现在测试是不可以的

**Comment by johnlanni** [comment]
标准的域名通配符只能出现在最前或最后；但你这个需求也能基于目前功能实现，方法是配置一个 *com，然后在路由里基于 header 做正则匹配，header 的key是 ":authority"

**Comment by 18612864207** [comment]
key填":authority"会报错，填"authority"没问题，看来不支持带":"这个特殊符号

**Comment by johnlanni** [comment]
是控制台报错吗，直接改ingress呢

**Comment by 18612864207** [comment]
是web控制台报错，不过我有另一个头X-Forwarded-Host，也是可以用的，就改成这个了

**Comment by CH3CHO** [comment]
@johnlanni 我们需要在控制台上允许用户配置带冒号的 Header 名称吗？需要的话我改一下。

**Comment by johnlanni** [comment]
@CH3CHO 需要支持的

**Comment by CH3CHO** [comment]
> 允许用户配置带冒号的 Header 名称吗

好的，这个我看一下怎么搞

**Comment by CH3CHO** [comment]
@johnlanni Console 本身并没有这个限制，但因为 header 匹配是基于 label 来做的。而 label name 不允许包含冒号。

![image](https://github.com/alibaba/higress/assets/2909796/2da25861-7d8f-461b-8599-13650e09bc16)

**Comment by johnlanni** [comment]
@CH3CHO 了解了，这块的配置方式需要优化下

**Comment by johnlanni** [comment]
可以实现一个 higress.io/prefix-match-pseudo-header-xxxx 的注解
对于截取的xxx部分，加上:前缀

**Comment by CH3CHO** [comment]
Controller 我也一并搞了吧

**Comment by CH3CHO** [comment]
- https://github.com/alibaba/higress/pull/803
- https://github.com/higress-group/higress-console/pull/287

**Comment by johnlanni** [comment]
@CH3CHO 收到👌，等这个控制面功能好了之后一起合并吧
