### ISSUE TITLE
GO WASM 插件 ReplaceHttpRequestBody 后出现的Content-Length不正确

### ISSUE THREAD

**Issue by xsdhy** [alibaba/higress#507]
## Why do you need it?
 Is your feature request related to a problem? Please describe in details

期望在「HTTP 请求 Body 处理阶段」wrapper.ProcessRequestBodyBy，调用获取、修改HttpRequestHeader的相关方法

## How could it be?
「HTTP 请求 Body 处理阶段」提供了一些列处理body的方法，比如说“ReplaceHttpRequestBody”，但是当替换前后的body size不一样时，不会则会出错，不会请求背后的后端服务。

所以期望在替换body后，手动修改Content-Length

**Comment by xsdhy** [comment]
解决了，Please note that you must remove the "content-length" header during OnHttpRequestHeaders.

**Comment by johnlanni** [comment]
@xsdhy 是的，移除掉后，如果设置了body，是会重新计算生成新的 content-length 的
