### ISSUE TITLE
Support for the new WASM plugin image specification

### ISSUE THREAD

**Issue by WeixinX** [alibaba/higress#509]
## Why do you need it?

hgctl plugin 命令基本完成 (#453)，正在进行相应的测试，而 gateway 目前无法解析已提出的 [Wasm 插件镜像规范](https://higress.io/zh-cn/docs/user/wasm-image-spec/)，因此遇到了如下问题：

![image](https://github.com/alibaba/higress/assets/49450531/37605835-d5a4-4c56-a4a1-b02e90efbb8c)

该镜像制品符合 [Wasm 插件镜像规范](https://higress.io/zh-cn/docs/user/wasm-image-spec/)：

![image](https://github.com/alibaba/higress/assets/49450531/f65830cb-244d-4ec0-9193-a99d27f72deb)

## How could it be?

详见官方文档 [Wasm 插件镜像规范](https://higress.io/zh-cn/docs/user/wasm-image-spec/)

**Comment by CH3CHO** [comment]
I'll look into it.

---- Replied Message ----
| From | ***@***.***> |
| Date | 09/06/2023 22:21 |
| To | alibaba/higress ***@***.***> |
| Cc | Subscribed ***@***.***> |
| Subject | [alibaba/higress] Support for the new WASM plugin image specification (Issue #509) |

Why do you need it?

hgctl plugin 命令基本完成 (#453)，正在进行相应的测试，而 gateway 目前无法解析已提出的 Wasm 插件镜像规范，因此遇到了如下问题：

该镜像制品符合 Wasm 插件镜像规范：

How could it be?

详见官方文档 Wasm 插件镜像规范

**Comment by CH3CHO** [comment]
实测可以正常解析并生效插件功能。请提供一下本地插件配置。

![8ba644ac56c90b886ebcc9ed86ff9c1](https://github.com/alibaba/higress/assets/2909796/c2af1257-9642-437b-b58d-891880438c13)

**Comment by WeixinX** [comment]
重新测试发现是可以解析的，属于是误伤了 😵‍💫
