### ISSUE TITLE
Higress Console 创建路由时域名允许非必填

### ISSUE THREAD

**Issue by lexburner** [alibaba/higress#513]
![image](https://github.com/alibaba/higress/assets/11485990/ec0eba34-590c-4d76-8070-002d904bd792)
![image](https://github.com/alibaba/higress/assets/11485990/95cabdaf-8626-4148-9ad6-009a06410838)

higress 控制台创建路由时域名参数是必填的，但是 Ingress 规则中其实可以不填，用户可以仅根据 path 来进行路由，无需 host，控制台需要修改下以跟 Ingress 规则对应

我会修复这一问题

**Comment by Melod-YI** [comment]
是的，这个问题在近期做本地测试的时候遇到很多麻烦。

windows、docker运行。

我没有一个属于我的域名，能想到的方式只能是改hosts文件来解决。比较麻烦。
