### ISSUE TITLE
Whether the Go version of 'parseAuthRuleConfig' method is supported

### ISSUE THREAD

**Issue by WeixinX** [alibaba/higress#514]
## Why do you need it?

若开发例如 [basic-auth](https://higress.io/zh-cn/docs/plugins/basic-auth), [key-auth](https://higress.io/zh-cn/docs/plugins/key-auth), [jwt-auth](https://higress.io/zh-cn/docs/plugins/jwt-auth) 这类拥有 `global_auth` 参数的 Golang WASM 插件，是否需要拥有像 wasm-cpp/common/route_rule_matcher.h 中的 [getMatchAuthConfig](https://github.com/alibaba/higress/blob/main/plugins/wasm-cpp/common/route_rule_matcher.h#L188), [parseAuthRuleConfig](https://github.com/alibaba/higress/blob/main/plugins/wasm-cpp/common/route_rule_matcher.h#L290)... 对这种情况的处理能力？

请问这部分工作是否已经有同学在进行了，如果没有可以分配给我让我尝试一下 ~

**Comment by johnlanni** [comment]
目前 cpp sdk 里 parseAuthRuleConfig 这个设计不是特别好，后面会重构一下，在处理 match rule 的配置时，能够拿到 global 的配置

**Comment by WeixinX** [comment]
@johnlanni 好呀我看看 ~

我有个小疑问不太理解这句话是意思 ↓

<img width="849" alt="image" src="https://github.com/alibaba/higress/assets/49450531/dfa3f093-5e4a-4d97-ade8-d70dae795d22">

“若不配置” 指的是不配置 `global_auth` ?

**Comment by WeixinX** [comment]
@johnlanni 我有个想法是在解析配置的时候（ParseRuleConfig），在 WASM 插件代码里用全局变量存储全局配置（consumers, global_auth, ...），当请求来时 GetMatchConfig 把 allow 数组传递给 WASM 插件，这样插件就可以既有全局配置又有请求对应域名/路由的 allow 数组来做相应处理了，不知道是否可行？🤔
