### ISSUE TITLE
waf拦截后没有详细的拦截日志

### ISSUE THREAD

**Issue by 18612864207** [alibaba/higress#525]
我的配置是这样的：
<img width="322" alt="image" src="https://github.com/alibaba/higress/assets/57471611/d91f7adf-de57-4eae-b305-858b2eadbcdf">
我随便模拟了一个请求/?whoami，返回403
而日志里只显示了短短一条信息
<img width="925" alt="image" src="https://github.com/alibaba/higress/assets/57471611/c60bde0d-0904-4ef2-bbc3-45c19e4ddbc7">
我另外的一个环境用的modsecurity-nginx，记录的拦截日志就非常详细
<img width="1043" alt="image" src="https://github.com/alibaba/higress/assets/57471611/40c9ca4d-9735-42c3-89dd-f1788182dc34">
详细的日志非常有必要，不然某个请求被拦截了，完全无法得知为何拦截，没法针对性的调整请求。我不确定是不是我配置不正确。

**Comment by johnlanni** [comment]
@rinfx 看下这个插件的modsecurity的日志为什么没有打印

**Comment by rinfx** [comment]
已经在此PR对日志进行改进：https://github.com/alibaba/higress/pull/537

**Comment by johnlanni** [comment]
@18612864207 做了镜像覆盖，重启higress gateway即可，不希望重启也可以修改对应wasmplugin资源里的oci镜像tag为1.0.2

**Comment by lhh821** [comment]
> @18612864207 做了镜像覆盖，重启higress gateway即可，不希望重启也可以修改对应wasmplugin资源里的oci镜像tag为1.0.2
@johnlanni 
![1695355322438](https://github.com/alibaba/higress/assets/42127122/b62c99b7-b3f8-4a96-9150-409a19ad10b7)
我这边修改tag为1.0.2之后获取不到这个镜像是什么情况?

**Comment by johnlanni** [comment]
@rinfx 看下这个镜像传了吗
