### ISSUE TITLE
使用nacos服务，但无法使用nacos的权重功能

### ISSUE THREAD

**Issue by QtSunShine** [alibaba/higress#529]
在引用nacos服务的时候，经过测试，支持nacos的上线下线功能，但流量始终是轮询。

调整nacos权重后，流量依然是轮询发送，每个节点均匀分配，权重设置并未生效，希望能对此做个适配。

**Comment by johnlanni** [comment]
https://github.com/alibaba/higress/blob/dc3e496aa0e8421253ee91dc3147843a5c265c19/registry/nacos/v2/watcher.go#L462

We can add weight here. Anyone want to implement this?

**Comment by Erica177** [comment]
i can try to fix it
