### ISSUE TITLE
The nacos watcher opened a namingClient, but did not close it

### ISSUE THREAD

**Issue by Erica177** [alibaba/higress#530]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via [ASRC](https://security.alibaba.com/)(Alibaba Security Response Center) where the issue will be triaged appropriately.**

- [x] I have searched the [issues](https://github.com/alibaba/higress/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
The nacos watcher opened a namingClient, but did not close it when the watcher stopped, resulting in a connection leak

### Ⅱ. Describe what happened

When I added a nacos registry through mcpBridge, I started a namingClient. When I deleted this registry and re added another nacos registry, the connection to the previous namingClient was not closed

### Ⅲ. Describe what you expected to happen

When a nacos registry is deleted, the corresponding namingclient should be closed

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- Higress version:  
- OS :
- Others:

**Comment by johnlanni** [comment]
@Erica177 Could you create a PR to fix this issue？

**Comment by Erica177** [comment]
i can fix it
