### ISSUE TITLE
支持通过 helm 参数集成 skywalking，提供 metrics 大盘模版（Support integration of skywalking through helm parameters, and provide metrics template）

### ISSUE THREAD

**Issue by johnlanni** [alibaba/higress#56]
## Why do you need it?

用于实现 Skywalking 指标观测，从而实现基于 Skywalking 的 Higress 监控大盘

---

It is used to realize the Skywalking indicator observation, so as to realize the Higress observability kanban based on Skywalking

## Other related information
skywalking doc:  https://skywalking.apache.org/docs/main/v8.9.1/en/setup/envoy/metrics_service_setting/

**Comment by cobb-tx** [comment]
@johnlanni Hi, i'd like to resolve this issue, can you assign it to me?

**Comment by johnlanni** [comment]
> @johnlanni Hi, i'd like to resolve this issue, can you assign it to me?

If by the time you finish #81,  this issue is still unclaimed, I'll assign it to you
