### ISSUE TITLE
Higress不支持对connect-timeout/read-timeout此类超时设置的ingress annotation吗？

### ISSUE THREAD

**Issue by millinchen** [alibaba/higress#569]
Higress不支持对connect-timeout/read-timeout此类超时设置的ingress annotation吗？
这种超时设置对公共平台很关键，能有效防止部分上游服务的响应耗时升高对公共平台的全局影响

**Comment by millinchen** [comment]
@johnlanni 请评估支持connect-timeout/read-timeout此类超时设置的ingress annotation

**Comment by johnlanni** [comment]
可以看下最新的文档 已经支持higress.io/timeout注解，和nginx不同的是这个是请求整体超时时间，而非单次io的超时，会更实用一些
