### ISSUE TITLE
hgctl 安装时动态生成 console admin 账号密码

### ISSUE THREAD

**Issue by 2456868764** [alibaba/higress#577]
## Why do you need it?
目前hgctl 在安装时console admin 默认密码是 admin， 为了增加安全性，安装过程中动态生成复杂的admin的密码

## How could it be?
1、动态生成admin密码
2、安装完成后输出admin 密码或者密码获取方式和其他提示信息

**Comment by CH3CHO** [comment]
可以联合这个 issue 一起看一下：https://github.com/higress-group/higress-console/issues/232
