### ISSUE TITLE
怎么样让客户端真实源地址打印到Higress的日志中

### ISSUE THREAD

**Issue by szhengli** [alibaba/higress#579]
怎么样让 客户端真实源地址出现在  higress 网关上？

**Comment by johnlanni** [comment]
@szhengli 看钉钉群里的你的问题，我没理解错的话，是想打印到日志里吧
1. 网关会添加这个请求头 x-envoy-external-address，内容是对端地址
2. kubectl edit configmap -n higress-system higress-config 可以修改日志配置：
![image](https://github.com/alibaba/higress/assets/6763318/e497efc0-b9d6-4144-b130-656e34e41783)
3. 添加一个配置字段即可，例如 "client_ip": "%REQ(X-ENVOY-EXTERNAL-ADDRESS)%"

**Comment by szhengli** [comment]
> @szhengli 看钉钉群里的你的问题，我没理解错的话，是想打印到日志里吧
> 
> 1. 网关会添加这个请求头 x-envoy-external-address，内容是对端地址
> 2. kubectl edit configmap -n higress-system higress-config 可以修改日志配置：
>    ![image](https://user-images.githubusercontent.com/6763318/274826377-e497efc0-b9d6-4144-b130-656e34e41783.png)
> 3. 添加一个配置字段即可，例如 "client_ip": "%REQ(X-ENVOY-EXTERNAL-ADDRESS)%"


不是的。 因为现在higress gateway，显示的"x_forwarded_for":"10.42.26.0" 这个地址不是真实的客户端地址。导致 waf 上 规则
“"SecRule REMOTE_ADDR \"@ipMatch 192.168.9.172\" \"id:101,phase:1,t:lowercase,log,deny\""”  无法匹配到客户端地址，而失效

**Comment by johnlanni** [comment]
这里看到的 x-forwarded-for  就是真实的对端地址的

**Comment by johnlanni** [comment]
网关会把看到的真实地址 append 到 XFF header里，如果原请求没有携带 XFF，这里就只会有1个IP，就是对端IP

**Comment by szhengli** [comment]
> 网关会把看到的真实地址 append 到 XFF header里，如果原请求没有携带 XFF，这里就只会有1个IP，就是对端IP

![image](https://github.com/alibaba/higress/assets/16127498/0b4bdd07-d4f2-411c-b64e-074e2f5468d0)

这个地址不是客户端的真实地址

**Comment by johnlanni** [comment]
那就是客户端不是直连的higress，这个地址网关就是通过socket拿到的，其他的IP，网关也看不到了，除非你前面的代理能通过XFF携带过来

**Comment by szhengli** [comment]
> 那就是客户端不是直连的higress，这个地址网关就是通过socket拿到的，其他的IP，网关也看不到了，除非你前面的代理能通过XFF携带过来

另外在wasf，中用 10.42.26.0这地址去拦截这个请求，会被拦截到到。所以这个地址就是gateway看到的请求的地址，但其不是客户端的真实地址。

**Comment by johnlanni** [comment]
跟这个配置没关系，这个是IP透传在请求头里的配置，你的问题是你认为这个不是真实客户端IP，但在higress上看到的tcp对端IP就是这个IP。

**Comment by szhengli** [comment]
> 跟这个配置没关系，这个是IP透传在请求头里的配置，你的问题是你认为这个不是真实客户端IP，但在higress上看到的tcp对端IP就是这个IP。
![image](https://github.com/alibaba/higress/assets/16127498/92cf73c7-ff60-456b-ac96-2752d2824dd2)
![image](https://github.com/alibaba/higress/assets/16127498/44fb05ed-4715-44da-92f9-d3ac79d16f2c)

gateway, 请求进入入的那个节点的 容器接口地址当成了源地址，而不是客户的真实地址

**Comment by johnlanni** [comment]
请求是从这个容器出来到的网关，那网关看到的ip就是这个容器的IP呀

**Comment by johnlanni** [comment]
@szhengli 是不是用的nodeport方式暴露的网关？

**Comment by szhengli** [comment]
> @szhengli 是不是用的nodeport方式暴露的网关？

我用的是 Metallb, + rancher k8s, loadbalancer方式暴露网关

**Comment by johnlanni** [comment]
https://www.qikqiak.com/post/get-client-realip/

可以看下这个问题 比较类似

**Comment by johnlanni** [comment]
metalb的实现应该也是基于kubeproxy的，externaltrafficpolicy要设置为local，才不会跨节点转发，才能带上真实的源ip。但限制就是当前节点上必须得有网关实例。单这样架构其实不太合理。可以给metalb提个issue问问。

之前也有用户遇到过类似问题，是通过k8s集群外的lb来解决的，比如阿里云CLB。但这就要求你部署在云厂商的环境里了。

**Comment by szhengli** [comment]
> metalb的实现应该也是基于kubeproxy的，externaltrafficpolicy要设置为local，才不会跨节点转发，才能带上真实的源ip。但限制就是当前节点上必须得有网关实例。单这样架构其实不太合理。可以给metalb提个issue问问。
> 
> 之前也有用户遇到过类似问题，是通过k8s集群外的lb来解决的，比如阿里云CLB。但这就要求你部署在云厂商的环境里了。

exactly as what you said.   now the real source IP can be captured on the higress gateway, but somehow, the wrong IP remains to be shown sporadically. 
![image](https://github.com/alibaba/higress/assets/16127498/2781699d-3ec8-4022-8f4d-b9690c979e23)

**Comment by szhengli** [comment]
I will be closing the issue, many thanks.

**Comment by wwek** [comment]
我和你同样的问题
我是k3s部署的，默认自带的lb
vm是 eip

**Comment by johnlanni** [comment]
@wwek 但是改成local后，要求源端的节点上必须部署了higress，你是用了daemonset方式部署来解决这个问题吗

**Comment by wwek** [comment]
> @wwek 但是改成local后，要求源端的节点上必须部署了higress，你是用了daemonset方式部署来解决这个问题吗

是的呢，目前我环境是k3s单机， higress选的lb方式暴露，会起daemonset
<img width="1141" alt="image" src="https://github.com/alibaba/higress/assets/1239403/fb1fc1c7-1025-419c-8fdd-ec048c68bf74">
<img width="1053" alt="image" src="https://github.com/alibaba/higress/assets/1239403/8068f2a2-f2c1-4ec2-b5d7-6e2cf83eed92">

**Comment by johnlanni** [comment]
![image](https://github.com/alibaba/higress/assets/6763318/bb369a95-d961-4d41-9a04-981bab4f5ba2)
通过toleration和affinity配置也可以控制调度到特定节点上，不需要daemonset

**Comment by johnlanni** [comment]
https://github.com/alibaba/higress/blob/73cf32aadd7959a698a2f16cf8539c2c51979798/helm/core/values.yaml#L398

现在调整这个 helm 参数，可以支持 daemonset 部署
