### ISSUE TITLE
the page fails to load  after enabling WAF on higress console

### ISSUE THREAD

**Issue by szhengli** [alibaba/higress#581]
![image](https://github.com/alibaba/higress/assets/16127498/6815ff16-df7f-4ab1-9c21-85319579958e)
after enabling the WAF, as above , the page fails to load. here is the error from gateway log.
![1697186076874_1BA3BEA6-C1E0-460b-BA3D-F2A95CB06CAB](https://github.com/alibaba/higress/assets/16127498/c31bf597-83aa-4b3f-9c53-a96e2097cfa9)
![image](https://github.com/alibaba/higress/assets/16127498/5c268390-4f49-43fb-b465-93132378c676)

**Comment by johnlanni** [comment]
@szhengli 能看到访问日志返回了什么状态码吗

**Comment by szhengli** [comment]
> @szhengli 能看到访问日志返回了什么状态码吗

![image](https://github.com/alibaba/higress/assets/16127498/a623807d-c471-4f91-9c3c-31fb3bcb7044)
![image](https://github.com/alibaba/higress/assets/16127498/0901bded-9df4-4093-8e5b-127bd2e2d418)

**Comment by johnlanni** [comment]
@szhengli 是不是发错日志了，看这条日志是正常的，如你在群里说的现象是后端响应比较大的时候会hang住对么

**Comment by johnlanni** [comment]
close stale issue
