### ISSUE TITLE
Wasm plugin optimization plan for request/response Transformer

### ISSUE THREAD

**Issue by WeixinX** [alibaba/higress#587]
## Why do you need it?

当前 Transformer 有以下可以优化的点：
1. Transformer 插件仅支持单向转换，即一个 Transformer 只处理请求或者只处理响应。考虑一个插件支持双向转换；
2. map 操作仅支持同种类型的映射。考虑支持跨 header, query param, body 的映射；
3. 转换操作的执行顺序固定（remove -> rename -> replace -> add -> append -> map -> dedupe）。考虑按照用户配置顺序执行；
4. key, value 可能没办法很好的说明字段含义，例如 remove 的 value 不需填写，rename 的 value 表示 newKey，map 的 value 表示 toKey，dudupe 的 value 表示 strategy。考虑添加/更换更合适的字段。

## How could it be?

**1. 支持双向转换：**

```go
type TransformerConfig struct {
	typ string `yaml:"type"`
	rules []TransformRule `yaml:"rules"`

      - trans Transformer `yaml:"-"`
      + reqTrans Transformer `yaml:"-"`
      + respTrans Transformer `yaml:"-"`
}
```
<br>

**2. map 操作跨 header, query param, body：**

- 为 map 操作添加额外字段 `source` 指定映射来源类型, 可选值为 header, query, body
- 修改 kvHandler 和 jsonHandler 相应逻辑
<br>

**3. 根据配置的顺序执行转换：**

这可能会对 Transformer 结构、Handler 处理逻辑、kvtGroup 结构等进行很大程度的修改
在先前的设计中 Handler 不复用 rules 字段，而是根据 rules 字段构造 kvtGroup 的目的是避免重复构造 Regexp；在优化中我们需要将 kvtGroup 设计成 rules 一样的切片结构，与 rules 不同的在于 Regexp 依然会被预先构造，因此在 Handler 中可以遍历 kvtGroup 而不是使用硬编码的转换顺序
<br>

**4. 设计更合理的 Param 结构：**

需要根据不同的 operate，设计不同的 Param。例如：
- remove 的 Param 可以只有 key 字段；
- rename 的则有 oldKey 和 newKey；
- map 有 fromKey 和 toKey；
- dedupe 有 key 和 strategy；
- ...

## Other related information
Transformer Plugin: https://github.com/alibaba/higress/tree/main/plugins/wasm-go/extensions/transformer

**Comment by 2456868764** [comment]
现实中的需求却往往需要多个插件通力合作，或者需要在插件配置中做一些简单的条件计算, 后续优化可以考虑方向是 为这个插件提供表达式(EL)功能，其中涉及功能如下：
1.复杂数据构造
2.请求数据访问
3. 辅助函数调用
4. 条件表达式计算
这样，一些简单差异化需求不需求额外开发新的插件。

**Comment by WeixinX** [comment]
@2456868764 Cool! 可以麻烦为这些功能点提供一些简单示例吗？

**Comment by 2456868764** [comment]
比如在添加头根据querystring里不同值添加不同头值

```
- operate: add
  headers:
  - key: UserID
    value: IsNull(data.query.user_id)? "0": data.query.user_id
```
这里包含请求数据访问，可以来源请求头，body， querystring等, 同时有支持辅助函数（主要是字符串，数组处理为多），还有常规表达式操作包括等于，不等于，大于，小于等。

这里使用场景：API 新老版本兼容，老系统兼容处理，还有特殊业务场景处理等。

**Comment by 2456868764** [comment]
或者把这个表达式（EL)能力抽象出来，作为wasm go 插件库，可以提个其他插件使用。

**Comment by Uncle-Justice** [comment]
> 3. 将 kvtGroup 设计成 rules 一样的切片结构

是比如这样吗？将`kvtGroup` 换成`[] kvtOperation` 

```go
type KvtOpType int
const (
	Remove KvtOpType  = iota
	Replace
        Append
        Map
        Dedupe
)
type kvtOperation struct{
  kvtOpType KvtOpType
  removedKeys []string
  [] kvt
  [] kvtReg
}
```
然后在Handler中遍历`[] kvtOperation` 的时候根据`kvtOpType` 来决定使用`kvtOperation` 中的`[] kvt` 或者`[] kvtReg` ？

> 4. 需要根据不同的 operate，设计不同的 Param

那有没有必要直接将`kvt` 直接也改成具体的操作呢？这样的话其实`kvtOperation` 看上去也会更直观，比如：
```go
type mapKvt struct{
  fromKey string
  toKey string
}
type kvtOperation struct{
  kvtOpType KvtOpType
  [] removeKvt
  [] replaceKvt
  [] appendKvt
  [] mapKvt
  ...
}
```

我对这个插件未来在开发上的拓展性没啥经验，如果未来在这个插件上要做很多新的kvt类型的话，这样做肯定导致代码的复用性降低了一些

**Comment by WeixinX** [comment]
@Uncle-Justice 或者可以考虑将 kvt 结构抽象为 interface，具体的操作（你指的 kvtOperation）去实现相应的接口？

**Comment by Uncle-Justice** [comment]
> 或者可以考虑将 kvt 结构抽象为 interface，具体的操作（你指的 kvtOperation）去实现相应的接口

```go
type Kvt interface{
  kvExecute(host, path string, kvs map[string][]string)
  jsonExecute(host, path string, oriData []byte)
}

type MapKvt struct {
	fromKey   string
	toKey string
	typ   string
}
 ​
 func (mapKvt MapKvt) kvExecute(host, path string, kvs map[string][]string) {
	if vs, ok := kvs[fromKey]; ok {
		kvs[toKey] = vs
	}
 }

// kvtGroup = [] Kvt
func (h kvHandler) handle(host, path string, kvs map[string][]string) error {
        for _, kvt := range h.kvtGroup{
           kvt.kvExecute(host, path, kvs) 
       }
	return nil
}
```
如果大致是这样的话我ok，以及这种写法，interface{}转换成为具体类型，比较频繁的话可能会吃性能，不知道这里影响大不大

**Comment by WeixinX** [comment]
@Uncle-Justice 如果考虑接口的性能开销的话，那我个人认为可以忽略扩展性（但在目前看来插件还并不复杂），但具体可以看看 @johnlanni 的建议~

**Comment by johnlanni** [comment]
> @Uncle-Justice 如果考虑接口的性能开销的话，那我个人认为可以忽略扩展性（但在目前看来插件还并不复杂），但具体可以看看 @johnlanni 的建议~

嗯，建议避免用interface{}转换，反射性能比较差，而且tinygo目前支持也不完善

**Comment by WeixinX** [comment]
> ``` go
> func (h jsonHandler) handle(host, path string, oriData []byte) (data []byte, mapSource interface{}, err error) {
> ```

@Uncle-Justice 想再多问下这个 `mapSource` 被返回是为什么呢？

**Comment by Uncle-Justice** [comment]
@WeixinX 抱歉，笔误，已修改

**Comment by Uncle-Justice** [comment]
@WeixinX 因为`双向转换`这个新增可能涉及到比较多的位置的改动，所以我想向你再确认一下。

如果要支持双向转换的话，目前我想到的办法就是在原yaml的配置中字段也要改动，这样才能区分开哪些是request的转换要求，哪些是response的转换要求，比如：

```go
type TransformerConfig struct {
	typ string `yaml:"type"`

       - rules []TransformRule `yaml:"rules"`

       + reqRules []TransformRule `yaml:"reqRules"`
       + respRules []TransformRule `yaml:"respRules"`

       - trans Transformer `yaml:"-"`
       + reqTrans Transformer `yaml:"-"`
       + respTrans Transformer `yaml:"-"`
}
```

对应的yaml举例：
```yaml
 - ingress:
        - higress-conformance-infra/wasmplugin-transform-bothway
      configDisable: false
      config:
          type: bothway
          reqRules :
            - operate: remove
              headers:
                - key: X-remove
          respRules :
            - operate: remove
              headers:
                - key: X-remove
```

这样的改动主要会导致之前和transformer的有关的所有涉及到`rules`字段的都需要分拆成`reqRules `, `respRules`，我不太确定这样做是否会产生其他影响

**Comment by WeixinX** [comment]
@Uncle-Justice `typ` 字段我觉得也可以去掉。虽然是两个 rule 字段，但它们复用同样的结构 `TransformRule`，在解析配置时将会转换为对应的 `Transformer`。

**Comment by Uncle-Justice** [comment]
@WeixinX 好的，那改动为：

```go
type TransformerConfig struct {
	// @Title 转换器类型
	// @Description 指定转换器类型，可选值为 request, response。
	// typ string `yaml:"type"`

	// @Title 转换规则
	// @Description 指定转换操作类型以及请求/响应头、请求查询参数、请求/响应体参数的转换规则
	reqRules []TransformRule `yaml:"reqRules"`
	respRules []TransformRule `yaml:"respRules"`
	
	// this field is not exposed to the user and is used to store the request and response transformer instance
	reqTrans Transformer `yaml:"-"`
	respTrans Transformer `yaml:"-"`
}

```

我会注意`reqRules `和`respRules`字段转换为`Transformer`结构体时的代码复用

**Comment by Uncle-Justice** [comment]
@WeixinX 关于支持跨类型map的转换操作，目前我遇到一些问题

> 为 map 操作添加额外字段 source 指定映射来源类型, 可选值为 header, query, body

之前因为只有同类型之间做map操作，因此之前的代码逻辑是在`onHttpRequestHeaders`中通过调用`config.reqTrans.TransformHeaders(host, path, hs)`和`config.reqTrans.TransformQuerys(host, path, qs)`来完成headers和query内的map转换，body的转换则放在了`onHttpRequestBody`



但是如果要做跨类型map，比如配置为
```yaml
- operate: map
  source: body
  headers:
  - key: X-add-append
    value: X-map
```

我在`onHttpRequestHeaders`函数内貌似是无法取到body数据作为映射来源的。因为这个函数被调用时[body还没有送到这一层](https://github.com/tetratelabs/proxy-wasm-go-sdk/blob/0ca93918b54f297349b32b15748e40740120e8aa/proxywasm/types/context.go#L134)


我感觉目前顶多能做到的有：

1. 对header做map操作的时候，映射来源可选为headers或querys
2. 对querys做map操作的时候，映射来源可选为headers或querys
3. 对body做map操作的时候，映射来源可选为headers，querys或body

**Comment by johnlanni** [comment]
@Uncle-Justice 是的，可以先这样限制，在配置解析时发现有问题就提示用户。
想要在header阶段读取body，需要等这个issue完成：#582

**Comment by Uncle-Justice** [comment]
@WeixinX @johnlanni 关于支持跨类型map的转换操作，当映射来源是body时，有一些情况不是很好做转换。

目前代码已经对body的两种数据类型分别做了处理：
1. 如果body是`map[string][]string`类型，使用kvhandler去做[转换](https://github.com/alibaba/higress/blob/5fbfbe0e4a1bf5fa6979179b82f435dcc5680630/plugins/wasm-go/extensions/transformer/main.go#L484)
2. 如果body是`map[string]interface{}`，即body是一个很复杂的json体的时候，将`body["body"]`作为`[]byte`形式使用jsonhandler去做[转换](https://github.com/alibaba/higress/blob/5fbfbe0e4a1bf5fa6979179b82f435dcc5680630/plugins/wasm-go/extensions/transformer/main.go#L488)（这里我也不太确定为什么要传入`body["body"]`，是因为echoserver的response body里面带了request header+body吗？如果是这样那为什么处理`body["body"]`为`[]byte`类型而非`map[string][]string`？还是单纯觉得body有可能是一个复杂的多级嵌套json数组？）

而headers和query都是`map[string][]string`类型，当对他们进行map操作时，对于上述的第一种类型，body能够比较容易作为映射来源，根据`fromKey`查询body得到`fromValue`（必为[]string类型），得到`toKey:fromValue`。但是对于上述的第二种类型，根据`fromKey`查询body得到`fromValue`的类型为json，不确定能否直接转成`[]string`形式，或者根本就是一个复杂的多级json数组，无法转为`[]string`形式

目前我想到的解决方式有2种：

1. 当body为`map[string]interface{}`类型时，暂不支持其作为映射来源对header或query进行map操作
2. 当body为`map[string]interface{}`类型时，根据`fromKey`查询body得到的`fromValue`，将其所含元素强制展开为string，进而转换为`[]string`类型的`fromValue`

**Comment by WeixinX** [comment]
@Uncle-Justice 

> 这里我也不太确定为什么要传入body["body"]

实际上这个 body["body"] 没有你想的那么复杂，只是因为在解析 body 的时候把它存到了 [map[string]interface{}{"body": body}](https://github.com/alibaba/higress/blob/5fbfbe0e4a1bf5fa6979179b82f435dcc5680630/plugins/wasm-go/extensions/transformer/utils.go#L103)

> 但是对于上述的第二种类型，根据fromKey查询body得到fromValue的类型为json，不确定能否直接转成[]string形式，或者根本就是一个复杂的多级json数组，无法转为[]string形式

对于第二种类型，使用 [sjson](https://github.com/tidwall/sjson)/[gjson](https://github.com/tidwall/gjson) 可以解析 body []byte，然后再根据 fromKey 查询即可

**Comment by Uncle-Justice** [comment]
@WeixinX 

> 对于第二种类型，使用 [sjson](https://github.com/tidwall/sjson)/[gjson](https://github.com/tidwall/gjson) 可以解析 body []byte，然后再根据 fromKey 查询即可

你说的对，body []byte肯定是使用sjson做查询得到fromValue，我的疑问点主要是，比如当我对headers做映射操作，映射来源是body []byte时，我需要将得到的`toKey:fromValue`追加进headers中，大致结构应该是这样：

```go
	for _, item := range h.map_ {
		fromKey, toKey := item.key, item.value
		fromValue := gjson.GetBytes(body, fromKey)
		if !fromValue.Exists() {
			continue
		}
                headers[toKey] = fromValue
	}
```
如果body本身是一个多级嵌套json数组，查询得到的fromValue的形式就不固定，可能是一个多级嵌套数组或者是一个单值，追加进header中时，又必须转为[]string形式，不过其实只要想转怎么都可以转成[]string类型，感觉问题也不大，主要是要确定好预期的效果。

并且以上这种情况，需要等https://github.com/alibaba/higress/issues/582 完成后才会出现，所以可以到时候再去细究
