### ISSUE TITLE
Implement the Golang version of the existing CPP Wasm plugin: bot-detect

### ISSUE THREAD

**Issue by CH3CHO** [alibaba/higress#590]

**Comment by CH3CHO** [comment]
@OnlyPiglet, please add a comment here and follow up this issue.

**Comment by OnlyPiglet** [comment]
ok, I wil follow this issue

**Comment by WeixinX** [comment]
@OnlyPiglet hello~ is there any progress on this issue recently?

**Comment by OnlyPiglet** [comment]
> @OnlyPiglet hello~ is there any progress on this issue recently?

sorry for this , I am busy for other things recently, I will finish this on this weekend asap

**Comment by OnlyPiglet** [comment]
> @OnlyPiglet hello~ is there any progress on this issue recently?

sorry for this , I am busy for other things recently, I will finish this on this weekend asap
