### ISSUE TITLE
Implement the Golang version of the existing CPP Wasm plugin: custom-response

### ISSUE THREAD

**Issue by WeixinX** [alibaba/higress#592]

**Comment by cr7258** [comment]
I want to implement custom-response plugin in Go. However, it seems to overlap with the [transformer plugin](https://github.com/alibaba/higress/tree/main/plugins/wasm-go/extensions/transformer). 
Besides custom HTTP response status code ([status_code](https://higress.io/en-us/docs/plugins/custom-response/#configuration-fields)) and enabling on specific status (enable_on_status), the transformer plugin offers all features of the custom-response plugin plus added functionality.

Should we deprecate custom-response plugin and instead incorporate the **status_code** and **enable_on_status** functionalities in the transformer plugin?

**Comment by WeixinX** [comment]
@cr7258 

I think custom-response and transformer are fundamentally different. 

The former is used to mock responses, while the latter is used to modify response information, depending on whether the request reaches the backend service or not.

**Comment by cr7258** [comment]
@WeixinX Thanks for your explanation. I'll try to implement the custom-response plugin. Please assign the issue to me, thanks.

**Comment by johnlanni** [comment]
@cr7258 Hello 👋 Se7en, please join this Dingtalk group, welcome to participate in the discussion:
​ ![image](https://github.com/alibaba/higress/assets/6763318/c594b032-54e5-475b-9638-504f99b19ff1)

**Comment by cr7258** [comment]
@johnlanni Thanks, joined.
