### ISSUE TITLE
Implement the Golang version of the existing CPP Wasm plugin: key-auth

### ISSUE THREAD

**Issue by WeixinX** [alibaba/higress#594]

**Comment by zesiar0** [comment]
please assign to me, I think I can implement it.

**Comment by dongjiang1989** [comment]
@WeixinX  review https://github.com/alibaba/higress/pull/586

**Comment by zesiar0** [comment]
emmm, so I don't need to finish this issue?

**Comment by WeixinX** [comment]
@zesiar0 Yes, this issue has been assigned to @dongjiang1989. Please select another issue whose status is "todo" in #589. Thanks ❤️.
