### ISSUE TITLE
hmac_auth wasm plugin: x-ca-signature-headers头问题

### ISSUE THREAD

**Issue by liushp** [alibaba/higress#602]
问题：
当client请求中不携带x-ca-signature-headers头时，生成的signToken会有一个孤零零的冒号。
例如：
X-Ca-Error-Message: Server StringToSign:`GET#application/text; charset=utf-8####:#/hello?query1=value1&query2=value2`
。
修复代码如下：
![image](https://github.com/alibaba/higress/assets/13849531/6c8abca4-4f06-45ff-814e-83bb81fb33bd)

**Comment by johnlanni** [comment]
嗯 不是这里 我修复下
