### ISSUE TITLE
Domain name matching rules in the plugin do not take effect as expected

### ISSUE THREAD

**Issue by TC-wang** [alibaba/higress#616]
### Ⅰ. Issue Description

After binding the basic-auth plugin to the domain name "a.test.com", it takes effect.

The results are as follows: 

```
➜  / curl -i localhost/put -H "host:a.test.com" -X PUT
HTTP/1.1 401 Unauthorized
www-authenticate: Basic realm=MSE Gateway
date: Wed, 01 Nov 2023 03:23:02 GMT
server: istio-envoy
content-length:
```

But when the port is added to the domain name, it does not take effect.

For example: 

```
➜  / curl -i localhost/put -H "host:a.test.com:80" -X PUT
HTTP/1.1 200 OK
server: istio-envoy
date: Wed, 01 Nov 2023 03:24:42 GMT
content-type: application/json
content-length: 631
access-control-allow-origin: *
access-control-allow-credentials: true
req-cost-time: 2
req-arrive-time: 1698809082031
resp-start-time: 1698809082033
x-envoy-upstream-service-time: 1
{.......}
```

### Ⅲ. Describe what you expected to happen
Even if the port is added to the domain name, the domain-level  will still take effect.

### Ⅳ. How to reproduce it (as minimally and precisely as possible)
1. Create domain name "a.test.com"
2. Configure basic-auth plugin
3. Create route /put
4. Use curl to access

### Ⅵ. Environment:

- Higress version:  1.2.0

**Comment by johnlanni** [comment]
Thanks for the suggestion, I'll fix it.

**Comment by johnlanni** [comment]
@TC-wang  Try it again, maybe need restart the gateway pod, because the wasm image's pull policy is `IfNotPresent` by default.

**Comment by TC-wang** [comment]
ok，thanks
