### ISSUE TITLE
Http转dubbo配置多个Ingress route导致请求失败或超时

### ISSUE THREAD

**Issue by davidzj** [alibaba/higress#624]
### Ⅰ. Issue Description
Http转dubbo，存在以下问题：
1、同一个Http2RPC，配置第一个Ingress Route可以正常访问，配置第二个Ingress Route（Dubbo接口另外一个方法），第一个Ingress Route可以正常访问，但是第二个Ingress Route持续等待中无返回
2、两个不同的Http2RPC，配置第一个Http2RPC的第一个Ingress Route可以正常访问，然后再配置第二个Http2RPC的第一个Ingress Route，两个Ingress Route访问全部报错500
删除只保留一个Ingress Route，最后这个Ingress Route是可以访问的，同时确认用不同域名该问题仍然存在。

### Ⅱ. Describe what happened
使用Nacos 2，配置一个McpBridge：
<img width="699" alt="image" src="https://github.com/alibaba/higress/assets/1204059/2a508c9a-a788-4396-bbb2-953f61b07b6e">

二个Dubbo服务接口，其中接口1一个方法，接口3个方法，对应配置两个Http2RPC：
<img width="782" alt="image" src="https://github.com/alibaba/higress/assets/1204059/c5d6e340-1625-4e9a-9565-e6fab450407b">
<img width="805" alt="image" src="https://github.com/alibaba/higress/assets/1204059/f856d4fa-971b-44ea-881a-db7d520fc7f7">

配置Http2RPC 1的Ingress Route 1，可以正常访问：
<img width="1512" alt="image" src="https://github.com/alibaba/higress/assets/1204059/73e147fc-64d3-4d14-afb5-cc8d6160fd79">
<img width="1612" alt="image" src="https://github.com/alibaba/higress/assets/1204059/d4fe9a35-ae92-4b8d-a4e3-23a04d58234e">

再配置Http2RPC 2的Ingress Route 1，两个全部报错500:
<img width="1504" alt="image" src="https://github.com/alibaba/higress/assets/1204059/39309a3e-d522-48b6-a016-9814680d9523">
<img width="1589" alt="image" src="https://github.com/alibaba/higress/assets/1204059/e468e5c4-cd56-4597-838e-a933f3597be6">
<img width="1598" alt="image" src="https://github.com/alibaba/higress/assets/1204059/d54890fb-e8bc-4eb3-8d31-f9fd1444b7c8">

删除Http2RPC 1的Ingress Route 1，Http2RPC 2的Ingress Route 1访问恢复正常：
<img width="1510" alt="image" src="https://github.com/alibaba/higress/assets/1204059/d42be120-64e7-48ac-8a65-3e573fe81182">
<img width="1613" alt="image" src="https://github.com/alibaba/higress/assets/1204059/ea2f217e-d66b-459d-9c50-856f17437ea3">

再配置Http2RPC 2的Ingress Route 2，该Route访问持续等待无返回：
<img width="1499" alt="image" src="https://github.com/alibaba/higress/assets/1204059/5ea2bdab-c62a-4b0a-82ff-4fe334f8f720">
<img width="1618" alt="image" src="https://github.com/alibaba/higress/assets/1204059/6f58f4ca-b7a5-40e7-bff1-d753b5b8f233">
<img width="1613" alt="image" src="https://github.com/alibaba/higress/assets/1204059/ddc08e14-a69e-4525-b0f5-a60dce15fd37">

删除Http2RPC 2的Ingress Route 1，Http2RPC 2的Ingress Route 2访问恢复正常：
<img width="1496" alt="image" src="https://github.com/alibaba/higress/assets/1204059/62ccc270-27e4-404c-8e1b-0423518b4452">
<img width="1591" alt="image" src="https://github.com/alibaba/higress/assets/1204059/c877406d-a091-4e26-96b2-a2896aa86d06">

### Ⅵ. Environment:

- Higress version:  1.3.0 by helm
- OS : 
- Others:  ACK Pro版 kubernetes 1.26.3-aliyun.1

**Comment by johnlanni** [comment]
cc @Hinsteny 看上去是 Http2Rpc 的 bug

**Comment by johnlanni** [comment]
@Hinsteny 请问这个修复有进展吗

**Comment by junechouiscoming** [comment]
你好，我想问下方法入参是实体类的时候，paramType要写全类名然后curl的时候传参用json吗？

**Comment by johnlanni** [comment]
> 你好，我想问下方法入参是实体类的时候，paramType要写全类名然后curl的时候传参用json吗？

@sjtuzbk paramType要写全类名，但传参数可以不是body，可以从请求参数或header解析吧？

**Comment by junechouiscoming** [comment]
> > 你好，我想问下方法入参是实体类的时候，paramType要写全类名然后curl的时候传参用json吗？
> 
> @sjtuzbk paramType要写全类名，但传参数可以不是body，可以从请求参数或header解析吧？

<img width="728" alt="image" src="https://github.com/alibaba/higress/assets/28861676/f3418eab-6815-4f9c-aa23-54c4580ce64d">
<img width="720" alt="image" src="https://github.com/alibaba/higress/assets/28861676/0dd5e472-56dc-4e53-ab08-dacbabfa4a97">

这是哪里配置有问题吗？sayHi的那个接口调用是没问题的，sayHello这个就不行

**Comment by Hinsteny** [comment]
just fix this issue, please refer https://github.com/alibaba/higress/blob/main/test/e2e/conformance/tests/httproute-http2rpc.go

**Comment by johnlanni** [comment]
fixed
