### ISSUE TITLE
hgctl not working with k8s 1.27.3

### ISSUE THREAD

**Issue by karl-chanel** [alibaba/higress#627]

**Comment by johnlanni** [comment]
Sorry about that. We will fix it as soon as possible.
Now you can use helm to install hgctl to avoid this problem.

**Comment by johnlanni** [comment]
@karl-chanel hi~, please retry it with the latest hgctl:
```bash
  curl -Ls https://raw.githubusercontent.com/alibaba/higress/main/tools/hack/get-hgctl.sh | VERSION=latest bash
```
