### ISSUE TITLE
hgctl dashboard 和 completion 命令优化

### ISSUE THREAD

**Issue by 2456868764** [alibaba/higress#630]
## Why do you need it?
 优化 dashboard 和 completion 命令

## How could it be?
- [ ]  dashboard 现在默认只监听 127.0.0.1， 可以指定参数 -l 监听指定的 host
- [ ]  dashboard  现在只支持 k8s 环境下higress ， 需要支持 docker 环境安装的 higress
- [ ]  completion 命令在 zsh 不能很好工作，需要修复支持

**Comment by karl-chanel** [comment]
also , is hgctl completion working correctly ?
![Uploading 屏幕截图 2023-11-09 223941.png…]()

**Comment by 2456868764** [comment]
The completion command can not work well now,  and will be fixed later.

**Comment by sjcsjc123** [comment]
Could i try it?

**Comment by sjcsjc123** [comment]
May i ask which aspect does not support docker environment installation for higress？

**Comment by sjcsjc123** [comment]
> also , is hgctl completion working correctly ? ![屏幕截图 2023-11-09 223941](https://private-user-images.githubusercontent.com/78248702/281767805-255088c4-83d0-4b00-9f58-7a6848dcb1e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3NjYwNzAsIm5iZiI6MTcwMTc2NTc3MCwicGF0aCI6Ii83ODI0ODcwMi8yODE3Njc4MDUtMjU1MDg4YzQtODNkMC00YjAwLTlmNTgtN2E2ODQ4ZGNiMWU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDA4NDI1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0NzAwNzY1M2FiMjQ0MDNlMjU2NjkyZGY5YjEzMDkzYjM4ODdmMTcxMzlhYzNiYzQ4NWUwYzY3MTMyNzE4YzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VE-oKCcvdw_YJLyEuv2rvCPYy-u0WOSaTnwxNmFvyFY) here is the config ,not working for me

You can add these two lines after the zshrc file, which may solve your problem. 

```
autoload -U compinit; compinit
source <(hgctl completion zsh); compdef _hgctl hgctl
```

**Comment by 2456868764** [comment]
it would be like to helm completion command implement. Please refer https://github.com/helm/helm/blob/main/cmd/helm/completion.go  which is auto outputed "compdef _hgctl hgctl" instead of added by manually @sjcsjc123

**Comment by sjcsjc123** [comment]
> it would be like to helm completion command implement. Please refer https://github.com/helm/helm/blob/main/cmd/helm/completion.go which is auto outputed "compdef _hgctl hgctl" instead of adding by manually @sjcsjc123

I don't think this code has much effect. The environment was not automatically configured in this code. What I understand is that Helm only modified the description information, and the rest is consistent with Cobra's built-in completion function. Following the prompts provided by Cobra, the completion function can be completed.

```golang
// Cobra doesn't source zsh completion file, explicitly doing it here
fmt.Fprintf(out, "compdef _helm helm")
```
- In Helm's code, this `out` is just `os.Stdout`.

As shown in the figure, I did not write any completion related code to automatically complete any session under bash. As for zsh, I did not achieve it successfully, and I also tested it with Helm. It works under bash, and it does not work on zsh either. I suspect it's related to personal configuration environment.

![image](https://github.com/alibaba/higress/assets/88550136/cabe26d0-95b0-4f20-b1d6-0dd818383f2d)

**Comment by 2456868764** [comment]
> > it would be like to helm completion command implement. Please refer https://github.com/helm/helm/blob/main/cmd/helm/completion.go which is auto outputed "compdef _hgctl hgctl" instead of adding by manually @sjcsjc123
> 
> I don't think this code has much effect. The environment was not automatically configured in this code. What I understand is that Helm only modified the description information, and the rest is consistent with Cobra's built-in completion function. Following the prompts provided by Cobra, the completion function can be completed.
> 
> ```go
> // Cobra doesn't source zsh completion file, explicitly doing it here
> fmt.Fprintf(out, "compdef _helm helm")
> ```
> 
> * In Helm's code, this `out` is just `os.Stdout`.
> 
> As shown in the figure, I did not write any completion related code to automatically complete any session under bash. As for zsh, I did not achieve it successfully, and I also tested it with Helm. It works under bash, and it does not work on zsh either. I suspect it's related to personal configuration environment.
> 
> ![image](https://private-user-images.githubusercontent.com/88550136/289236863-cabe26d0-95b0-4f20-b1d6-0dd818383f2d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxMDQ3NjIsIm5iZiI6MTcwMjEwNDQ2MiwicGF0aCI6Ii84ODU1MDEzNi8yODkyMzY4NjMtY2FiZTI2ZDAtOTViMC00ZjIwLWIxZDYtMGRkODE4MzgzZjJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA5VDA2NDc0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlODQwODdiZjI5MTRmYjAyYWRmNGE4NWZmNDdiMWEzZWI2MTBkMzgxNjA1MDEyYjI3NTRkZGQzYjFlNjQ4ZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8cXAgqpwuyB8Pn0ru8NEJ61fKjY-HdmRTAk79q64CxI)

I tested "helm completion zsh ", and found that it worked well in zsh. 

<img width="1087" alt="截屏2023-12-09 14 45 07" src="https://github.com/alibaba/higress/assets/108045855/11a15d21-4687-46de-b025-7ac822d0a896">

 When i commented last statement "#compdef _helm helm"  in completion.sh file, and sourced it again in new zsh session window, then it didn't work well.

**Comment by sjcsjc123** [comment]
> > > it would be like to helm completion command implement. Please refer https://github.com/helm/helm/blob/main/cmd/helm/completion.go which is auto outputed "compdef _hgctl hgctl" instead of adding by manually @sjcsjc123
> > 
> > 
> > I don't think this code has much effect. The environment was not automatically configured in this code. What I understand is that Helm only modified the description information, and the rest is consistent with Cobra's built-in completion function. Following the prompts provided by Cobra, the completion function can be completed.
> > ```go
> > // Cobra doesn't source zsh completion file, explicitly doing it here
> > fmt.Fprintf(out, "compdef _helm helm")
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * In Helm's code, this `out` is just `os.Stdout`.
> > 
> > As shown in the figure, I did not write any completion related code to automatically complete any session under bash. As for zsh, I did not achieve it successfully, and I also tested it with Helm. It works under bash, and it does not work on zsh either. I suspect it's related to personal configuration environment.
> > <img alt="image" width="54.10511016845703" height="21.008522033691406" src="https://private-user-images.githubusercontent.com/88550136/289236863-cabe26d0-95b0-4f20-b1d6-0dd818383f2d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxMDQ3NjIsIm5iZiI6MTcwMjEwNDQ2MiwicGF0aCI6Ii84ODU1MDEzNi8yODkyMzY4NjMtY2FiZTI2ZDAtOTViMC00ZjIwLWIxZDYtMGRkODE4MzgzZjJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA5VDA2NDc0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlODQwODdiZjI5MTRmYjAyYWRmNGE4NWZmNDdiMWEzZWI2MTBkMzgxNjA1MDEyYjI3NTRkZGQzYjFlNjQ4ZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8cXAgqpwuyB8Pn0ru8NEJ61fKjY-HdmRTAk79q64CxI">
> 
> I tested "helm completion zsh ", and found that it worked well in zsh.
> 
> <img alt="截屏2023-12-09 14 45 07" width="1087" src="https://private-user-images.githubusercontent.com/108045855/289245342-11a15d21-4687-46de-b025-7ac822d0a896.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxMDUyMTYsIm5iZiI6MTcwMjEwNDkxNiwicGF0aCI6Ii8xMDgwNDU4NTUvMjg5MjQ1MzQyLTExYTE1ZDIxLTQ2ODctNDZkZS1iMDI1LTdhYzgyMmQwYTg5Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwOVQwNjU1MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZTE5NDJhYzRiOTI0NTAxNGVjZTY5MjA2Y2RiMDVlMDk0Mzk2YzVkZjJjOTFkMTQ5ZTZjMDVjNGQzM2I1MzkwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HaourDAMTE4gljZ08YLj1Cjo5y3WZ7erztVOYfn0Q24">
> When i commented last statement "compdef _helm helm" in completion.sh file, and sourced it again in new zsh session window, then it didn't work well.


I've roughly identified the issue. In the case of Cobra's built-in completion, the generated Zsh script lacks the line `compdef _hgctl hgctl` at the end. Thank you.

**Comment by sjcsjc123** [comment]
Currently, there are three proposed approaches for adapting the `hgctl dashboard console` to Docker:

1. Check whether there is a `profile` file in the `$HOME` directory. If found, it implies a potential local installation, and then use the corresponding CLI to check for the existence of the service. (Drawback: It could be cumbersome as multiple `profile` files might coexist in the HOME directory.)

2. Add a flag to the CLI, with a default behavior of accessing Kubernetes. When the flag is used, switch to accessing Docker instead.

3. While attempting to access Kubernetes, if an issue arises, switch directly to Docker. If both Kubernetes and Docker encounters errors, return an error to the user.

Which approach do you think is better?

**Comment by 2456868764** [comment]
> Currently, there are three proposed approaches for adapting the `hgctl dashboard console` to Docker:
> 
> 1. Check whether there is a `profile` file in the `$HOME` directory. If found, it implies a potential local installation, and then use the corresponding CLI to check for the existence of the service. (Drawback: It could be cumbersome as multiple `profile` files might coexist in the HOME directory.)
> 2. Add a flag to the CLI, with a default behavior of accessing Kubernetes. When the flag is used, switch to accessing Docker instead.
> 3. While attempting to access Kubernetes, if an issue arises, switch directly to Docker. If both Kubernetes and Docker encounters errors, return an error to the user.
> 
> Which approach do you think is better?

I suggest that the default behavior is the same as the third approach, and then add an optional flag to the CLI, if this flag is enabled, switch directly to check the docker installed
