### ISSUE TITLE
Feature Request: Add `x-real-ip` header for nginx compacity

### ISSUE THREAD

**Issue by zzjin** [alibaba/higress#631]
## Why do you need it?
When migrate from ingress-nginx gateway, users often use `x-real-ip` to get client real ip, and after upgraded to higress, users also want to use the same header as get the same client ip.

## How could it be?
Add some doc/demo of how to add `x-real-ip` for all ingress crds.

## Other related information
* http://nginx.org/en/docs/http/ngx_http_realip_module.html
* https://github.com/istio/istio/issues/7607

**Comment by johnlanni** [comment]
We can optimize it as a part of #625.

**Comment by sjcsjc123** [comment]
这个是否有人做呢？我看 #625  已经被指派了。

**Comment by johnlanni** [comment]
@sjcsjc123 跟625有联动，需要现做整体配置设计，我跟 625 的认领同学沟通下

**Comment by johnlanni** [comment]
done

@sjcsjc123 可以帮忙更新下文档：https://higress.io/zh-cn/docs/user/configmap
