### ISSUE TITLE
Jwt中从payload取出字段的值设置到这个请求头中，转发给后端  这个参数没有示例配置。一直失败

### ISSUE THREAD

**Issue by WCCRegistered** [alibaba/higress#635]
## Why do you need it?
 Is your feature request related to a problem? Please describe in details

## How could it be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by johnlanni** [comment]
https://higress.io/zh-cn/docs/plugins/jwt-auth

看下文档，注意是个数组：
![Uploading image.png…]()

**Comment by johnlanni** [comment]
@WCCRegistered 问题已经解决
