### ISSUE TITLE
配置路由时，为什么会有disabled.higress.io注解?

### ISSUE THREAD

**Issue by yaoyasong** [alibaba/higress#644]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via [ASRC](https://security.alibaba.com/)(Alibaba Security Response Center) where the issue will be triaged appropriately.**

- [ ] I have searched the [issues](https://github.com/alibaba/higress/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
配置路由时，采用正则匹配，保存是自动添加了2个注解：
disabled.higress.io/upstream-vhost ： 
disabled.higress.io/rewrite-path: /

去掉了反而无法正确路由。
帮助文档中也没有找到这2个注解的说明

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- Higress version:  v1.3.0
- OS :
- Others:

**Comment by johnlanni** [comment]
@yaoyasong 这个是为了辅助控制台实现关闭策略时，依然保持配置的内容实现的
