### ISSUE TITLE
hmac的x-ca-timestamp计算逻辑不对

### ISSUE THREAD

**Issue by liushp** [alibaba/higress#650]
![image](https://github.com/alibaba/higress/assets/13849531/a5a4e1a9-e50a-4487-a23d-0f4bfa68051c)

**Comment by liushp** [comment]
逻辑就是：
1. 先把x-ca-timestamp从秒/毫秒转成纳秒。
2. 然后再和current_time（单位ns）比较

**Comment by johnlanni** [comment]
谢谢🙏可以直接提一个pr吗
