### ISSUE TITLE
Support building multi-arch images after upgrading to istio 1.19.x

### ISSUE THREAD

**Issue by CH3CHO** [alibaba/higress#666]
## Why do you need it?

Now, we are upgrading the version of istio Higress relies on from 1.12.x to 1.19.x. When we are using istio 1.12.x, we have done a lot of patching on the upstream to support multi-arch image building. After upgrading to istio 1.19.x, we need to find a better way to archieve the same goal, building multi-arch docker images (amd64 + arm64) for controller, pilot and proxy with one command.

## How could it be?

The upgrading work is now under-going in branch [feat/istio-1.19.0](https://github.com/alibaba/higress/tree/feat/istio-1.19.0).

The codebase already supports building docker images of the current arch (amd64 tested only, arm64 not tested yet), mainly utilizing the image building scripts provided by istio and envoy theirselves. We need to find a way to support multi-arch image building on top of it.

Local arch image building commands:
- controller: make docker-build
- pilot: make build-pilot-local
- proxy: make build-gateway-local

For pilot and proxy, you may need to use `sudo` to get it done.

## Other related information

@johnlanni , could you explain how the current multi-arch image building process works with istio 1.12.x?

**Comment by johnlanni** [comment]
I did some hack when use 1.12.x: https://github.com/alibaba/higress/blob/main/istio/1.12/patches/istio/20230815-multi-arch.patch
cc @rinfx
