### ISSUE TITLE
Hgctl has no prebuilt binary for windows

### ISSUE THREAD

**Issue by johnlanni** [alibaba/higress#668]
## Why do you need it?

When we execute this command on windows:

`curl -Ls https://raw.githubusercontent.com/alibaba/higress/main/tools/hack/get-hgctl.sh | VERSION=latest bash`

This error occurs:

![image](https://github.com/alibaba/higress/assets/6763318/9c2a1e47-2d31-4336-9fe9-19c0bd36cdee)

## Other related information

1. action：https://github.com/alibaba/higress/blob/main/.github/workflows/latest-release.yaml
2. makefile target：
https://github.com/alibaba/higress/blob/a554ee1cebdb60bb166d3abcbc287bd68e940d23/Makefile.core.mk#L90-L94
3. install script：
https://github.com/alibaba/higress/blob/main/tools/get-higress.sh

**Comment by johnlanni** [comment]
@Ink-33 Please add a comment here and I can assign this issue to you.

**Comment by Ink-33** [comment]
please assign me, thanks
