### ISSUE TITLE
完全兼容 Ingress 注解 nginx.ingress.kubernetes.io/canary-by-header-pattern

### ISSUE THREAD

**Issue by WangJieWJ** [alibaba/higress#671]
## Why do you need it?
 Is your feature request related to a problem? Please describe in details

之前使用 ingress-nginx 现在切换 Higress ，切换之后灰度发布失效了。
场景为：有两个后端服务S1、S2。
S2 Ingress 添加下面注解
    nginx.ingress.kubernetes.io/canary: "true"     
    nginx.ingress.kubernetes.io/canary-by-header: "Referer"
    nginx.ingress.kubernetes.io/canary-by-header-pattern: test.XXX.com 
请求的 Referer 为 http://test.XXX.com/YYY、https://test.XXX.com/ZZZ 都会路由到 S2 服务，
其他都会路由到 S1 服务。 

## How could it be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

ingress-nginx的正则是部分匹配，目前higress需要全部匹配，想要 Higress 兼容部分匹配的场景

**Comment by Uncle-Justice** [comment]
@johnlanni 
根据目前的信息，给定pattern为`test.XXX.com`，是要能够正则匹配`https://test.XXX.com/*`，`http://test.XXX.com/*`，`test.XXX.com/*`吗？

这样的改动会对其他已经使用higress的项目带来不一致的影响吗？

以及目前还有其他需要考虑的部分匹配的情况吗？

**Comment by johnlanni** [comment]
@Uncle-Justice 这里没有完全兼容 nginx ingress，属于 bug，需要修复。已经使用的用户可能有影响，我们需要在 release note 里说明一下
