### ISSUE TITLE
官网 quickstart 文档翻译 (Official website quickstart document translation)

### ISSUE THREAD

**Issue by johnlanni** [alibaba/higress#68]
https://higress.io/zh-cn/docs/user/quickstart.html

**Comment by johnlanni** [comment]
@CH3CHO 
英文：https://github.com/higress-group/higress-group.github.io/blob/master/docs/en-us/user/quickstart.md
中文：https://github.com/higress-group/higress-group.github.io/blob/master/docs/zh-cn/user/quickstart.md

**Comment by CH3CHO** [comment]
申请认领此任务

**Comment by johnlanni** [comment]
@CH3CHO 十分感谢🙏

**Comment by CH3CHO** [comment]
不过这个文档里本地环境验证的最后一步，直接get的话会返回一个时间戳。感觉应该是K8s他们调整了那套e2e-test的YAML，功能发生了变化。我做这个issue的时候一并修正了哦。

**Comment by johnlanni** [comment]
> 不过这个文档里本地环境验证的最后一步，直接get的话会返回一个时间戳。感觉应该是K8s他们调整了那套e2e-test的YAML，功能发生了变化。我做这个issue的时候一并修正了哦。

好的

**Comment by CH3CHO** [comment]
详细内容请见： https://github.com/higress-group/higress-group.github.io/pull/66
