### ISSUE TITLE
Support APISIX plugin - request-validation

### ISSUE THREAD

**Issue by WeixinX** [alibaba/higress#682]
https://apisix.apache.org/docs/apisix/plugins/request-validation/
In implementation, however, we need not replicate APISIX exactly, but instead should focus on the actual user needs behind the plugins, combined with the specific circumstances of Higress, to re-abstract configuration fields and corresponding capabilities. We can draw lessons from others, but we should not copy them exactly.

**Comment by sjcsjc123** [comment]
Could i have a try?
