### ISSUE TITLE
http转dubbo-支持将RequestBody直接序列化为对象

### ISSUE THREAD

**Issue by davidzj** [alibaba/higress#707]
## Why do you need it?
当前不能直接将整个RequestBody序列化为对象，只能将ResponseBody中某个属性的值序列化对象，很不方便。建议这块参考下SpringMVC的设计，这样更易用易懂

## How could it be?
建议参考Spring MVC进行设计，其中一种：
![image](https://github.com/alibaba/higress/assets/1204059/b6112e14-5d57-4f65-aeb3-47b9cc213029)

## Other related information
参考：https://docs.spring.io/spring-framework/reference/web/webflux/controller/ann-methods/requestbody.html
<img width="471" alt="image" src="https://github.com/alibaba/higress/assets/1204059/149f4996-cc9d-4f98-bf99-ba2b99803563">

**Comment by johnlanni** [comment]
需要完善下文档和e2e test

**Comment by johnlanni** [comment]
@davidzj 1.3.2版本已经发布支持了这个，可以使用看看
