### ISSUE TITLE
e2e 测试优化

### ISSUE THREAD

**Issue by 2456868764** [alibaba/higress#709]
## Why do you need it?
 Is your feature request related to a problem? Please describe in details

现在本地跑e2e 测试通过 make higress-conformance-test 运行 e2e 测试， 这个测试包含准备环境和运行测试用例两部分，
在开发e2e测试时候，发现准备环境很耗时间，测试用例需要反复运行，这个过程很久

## How could it be?
make higress-conformance-test 运行 e2e 测试，整个过程可以独立拆分成环境准备，和运行测试用例两个部分。

**Comment by sjcsjc123** [comment]
有个cleanup的flag参数可支持环境复用，但需要手动移除某些pod节点

**Comment by sjcsjc123** [comment]
个人觉得e2e优化可以体现在cleanup参数设置为false的时候，如何避免去update一个正在Terminating的pod所引起的冲突，预计采用cleanup参数设置为false的时候不让pods进入Terminating的状态，来完成cleanup参数的正常使用，如果这个方案可以的话，我可以尝试一下，这只是优化中的一部分，更多地还需要修改makefile中的脚本文件。

**Comment by sjcsjc123** [comment]
1、higress环境准备部分，修改makefile，将其分成环境准备、运行e2e测试、环境清除三部分
2、e2e的base环境准备部分，把TestHigressConformanceTests拆分成三份，第一部分启动base resource，第二部分运行测试，第三部分清除base resource，中间过程中取消cleanup参数。

以上为我的优化思路，如果可以的话，我可以尝试一下。

**Comment by 2456868764** [comment]
可以按照这个优化思路来。
