### ISSUE TITLE
key-auth 插件的 README 文档翻译

### ISSUE THREAD

**Issue by johnlanni** [alibaba/higress#71]
key-auth 插件的 README 文档翻译
https://github.com/alibaba/higress/blob/main/plugins/wasm-cpp/extensions/key_auth

**Comment by Fkbqf** [comment]
Is this task to translate the key-auth plugin's README document into English?

**Comment by CH3CHO** [comment]
> Is this task to translate the key-auth plugin's README document into English?

You bet!
