### ISSUE TITLE
Standalone模式部署后添加eureka注册中心后无法服务发现

### ISSUE THREAD

**Issue by lcfang** [alibaba/higress#713]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via [ASRC](https://security.alibaba.com/)(Alibaba Security Response Center) where the issue will be triaged appropriately.**

- [x] I have searched the [issues](https://github.com/alibaba/higress/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
添加eureka为服务来源后，服务列表为空，查看higres-controller-1日志发现报错

### Ⅱ. Describe what happened
![image](https://github.com/alibaba/higress/assets/30678878/c687e0f6-ebe9-4f53-b86d-149a89d21a43)

### Ⅲ. Describe what you expected to happen
能够正常服务发现

### Ⅳ. Environment:

- Higress version:  1.3.1
- OS : SUSE
- Others: 内网环境离线安装

**Comment by johnlanni** [comment]
@lcfang 是standalone模式部署吗

**Comment by lcfang** [comment]
> @lcfang 是standalone模式部署吗

是的，用`configure.sh`安装的
