### ISSUE TITLE
e2e test中的envoy config校验可以支持定位判断，例如listener里name为xxx的config里是否match/exist/notexist

### ISSUE THREAD

**Issue by johnlanni** [alibaba/higress#725]
加个TODO吧，可以支持定位判断，例如listener里name为xxx的config里是否match/exist/notexist，这样这个配置检查功能会更通用。可以用于一般的e2e test，而非只是envoyfilter的场景。

_Originally posted by @johnlanni in https://github.com/alibaba/higress/pull/710#discussion_r1433384546_

**Comment by sjcsjc123** [comment]
我可以预定一下这个issue

**Comment by 2456868764** [comment]
PR  https://github.com/alibaba/higress/pull/710 已经支持 Existed, NotExisted, Match 这三种操作。
