### ISSUE TITLE
e2e支持发送指定http协议的http请求

### ISSUE THREAD

**Issue by sjcsjc123** [alibaba/higress#730]
目前e2e框架暂时不支持发送http2/http3的请求，需要添加支持一下。

**Comment by spacewander** [comment]
我可以来做这件事。准备怎么指定 Protocol？在 https://github.com/alibaba/higress/blob/612c94dd8a7ea7b96268f63df62ac2a9960f520a/test/e2e/conformance/utils/http/http.go#L89 里面加个字段如何？

**Comment by sjcsjc123** [comment]
可以的

**Comment by spacewander** [comment]
发现现在已经有 protocol 字段，不需要我加了。
另外 HTTP3 的支持需要 https://github.com/quic-go/quic-go，而这个库要求 Go 1.21. Higress 目前是 Go 1.19，是先只支持 HTTP2，还是升级到 Go 1.21？

**Comment by sjcsjc123** [comment]
先只支持http2吧
