### ISSUE TITLE
无法从 consul 注册中心获取IP数据

### ISSUE THREAD

**Issue by nlg521** [alibaba/higress#740]
服务来源设置了 Consul 类型，可以同步服务名，但是无法同步服务名对应 IP 列表 

**consul 配置**
<img width="1441" alt="image" src="https://github.com/alibaba/higress/assets/7973318/3ce9db8b-8a22-421d-99b1-4cf30ad18d36">
**没有同步  ip 列表**
<img width="1125" alt="image" src="https://github.com/alibaba/higress/assets/7973318/4363da46-dbc5-46e7-9b41-0ed58e3f0620">
<img width="663" alt="image" src="https://github.com/alibaba/higress/assets/7973318/862430fb-368f-435e-94cc-66de72a41354">

- Higress version:  v1.3.1
- Consul：v1.12.2
- Others:

**Comment by johnlanni** [comment]
@2456868764 看下这个问题

**Comment by CH3CHO** [comment]
编辑的时候数据中心没显示的话可以考虑清理一下浏览器缓存，我这边本地看在编辑的时候有显式的。不太确定是不是缓存的问题。

**Comment by 2456868764** [comment]
看一下 consul 服务发现里能看到这个服务节点注册上来IP地址吗？
另外看一下 higress controller 日志 kubectl  logs -f higress-controller-XXXX   higress-core   -n higress-system
 higress-controller-XXXX 这个是 higress-controller pod name

**Comment by nlg521** [comment]
> 编辑的时候数据中心没显示的话可以考虑清理一下浏览器缓存，我这边本地看在编辑的时候有显式的。不太确定是不是缓存的问题。

谢谢您的回复，我换了一个浏览器也不行，只有这个字段没有显示。

**Comment by CH3CHO** [comment]
> 谢谢您的回复，我换了一个浏览器也不行，只有这个字段没有显示。

那这个有点奇怪。麻烦提供一下 higress-console 所使用的镜像版本，以及 `kubectl get mcpbridge default -n higress-system` 的输出。我本地尝试重现一下。

**Comment by nlg521** [comment]
> kubectl logs -f higress-controller-XXXX higress-core -n higress-system

<img width="837" alt="image" src="https://github.com/alibaba/higress/assets/7973318/5b6a5e4d-d0c0-49cd-96d4-4fa8f08eb539">
从日志上看是能拿到 服务名，但是 服务对应的 ip 没有显示。
有一个小问题，consul 地址不能包含 http://xxx. 只能录入 ip 。

**Comment by nlg521** [comment]
> kubectl get mcpbridge default -n higress-system
输出的日志
<img width="571" alt="image" src="https://github.com/alibaba/higress/assets/7973318/0b14d96a-613c-40e8-b491-0ce5a2594183">
镜像的版本是：
    image: higress-registry.cn-hangzhou.cr.aliyuncs.com/higress/console:1.3.1

**Comment by CH3CHO** [comment]
> > kubectl get mcpbridge default -n higress-system
> > 输出的日志
> 
> <img alt="image" width="571" src="https://private-user-images.githubusercontent.com/7973318/293300844-0b14d96a-613c-40e8-b491-0ce5a2594183.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM4MTc3NzEsIm5iZiI6MTcwMzgxNzQ3MSwicGF0aCI6Ii83OTczMzE4LzI5MzMwMDg0NC0wYjE0ZDk2YS02MTNjLTQwZTgtYjQ5MS0wY2U1YTI1OTQxODMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDIzMTIyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjlUMDIzNzUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTYyMDkzZGE3ZmEwZDgxMWU0ODAxNTZlODUxYjU2MGEwYTQzYzRiYTM2OTA4NTU3M2QxMjVmZTMxMTk3NmI1NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.GvFXNmEz4iyH_srKc06lMEJCLV0aGcZ8Vye0E9EBByI">
> 镜像的版本是： image: higress-registry.cn-hangzhou.cr.aliyuncs.com/higress/console:1.3.1

忘记输出为 yaml 了。请再执行一次 `kubectl get mcpbridge default -n higress-system -o yaml`

**Comment by CH3CHO** [comment]
> > kubectl logs -f higress-controller-XXXX higress-core -n higress-system
> 
> <img alt="image" width="837" src="https://private-user-images.githubusercontent.com/7973318/293298525-5b6a5e4d-d0c0-49cd-96d4-4fa8f08eb539.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM4MTk0NDMsIm5iZiI6MTcwMzgxOTE0MywicGF0aCI6Ii83OTczMzE4LzI5MzI5ODUyNS01YjZhNWU0ZC1kMGMwLTQ5Y2QtOTZkNC00ZmE4ZjA4ZWI1MzkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDIzMTIyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjlUMDMwNTQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzZhNDIzNGZjMWFiOTNlNTAxMjJkMjYxOTM4NzAyMDY0ZDZkODE2YWIzYzYyNTkxOGMyNWNhMDg3Nzk3MTAwYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ARHnayI01ZgLxpHMl55IoFdKrNQJwP7ffXda0z-_2WU"> 从日志上看是能拿到 服务名，但是 服务对应的 ip 没有显示。 有一个小问题，consul 地址不能包含 http://xxx. 只能录入 ip 。

这里本身输入的就是地址，默认使用 HTTP 协议，所以不需要额外输入协议。而且端口也是要求独立输入的，这样 http://xxx 又不加端口也会比较奇怪。

**Comment by nlg521** [comment]
> kubectl get mcpbridge default -n higress-system -o yaml

 kubectl get mcpbridge default -n higress-system -o yaml
apiVersion: networking.higress.io/v1
kind: McpBridge
metadata:
  creationTimestamp: "2023-12-28T07:44:34Z"
  generation: 5
  name: default
  namespace: higress-system
  resourceVersion: "146899868"
  uid: 46f8a256-f33b-4d93-b695-c9202c79e858
spec:
  registries:
  - domain: 11.67.100.241
    name: consul
    port: 80
    type: consul

**Comment by CH3CHO** [comment]
> kubectl get mcpbridge default -n higress-system -o yaml apiVersion: networking.higress.io/v1 kind: McpBridge metadata: creationTimestamp: "2023-12-28T07:44:34Z" generation: 5 name: default namespace: higress-system resourceVersion: "146899868" uid: 46f8a256-f33b-4d93-b695-c9202c79e858 spec: registries:
> 
> * domain: 11.67.100.241
>   name: consul
>   port: 80
>   type: consul

单看这个配置数据，是不包含 dc 啊什么的信息的。不确定这个是否会影响行为，建议编辑一下把信息补充上去。

**Comment by nlg521** [comment]
> > > kubectl get mcpbridge default -n higress-system
> > > 输出的日志
> > 
> > 
> > <img alt="image" width="571" src="https://private-user-images.githubusercontent.com/7973318/293300844-0b14d96a-613c-40e8-b491-0ce5a2594183.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM4MTc3NzEsIm5iZiI6MTcwMzgxNzQ3MSwicGF0aCI6Ii83OTczMzE4LzI5MzMwMDg0NC0wYjE0ZDk2YS02MTNjLTQwZTgtYjQ5MS0wY2U1YTI1OTQxODMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDIzMTIyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjlUMDIzNzUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTYyMDkzZGE3ZmEwZDgxMWU0ODAxNTZlODUxYjU2MGEwYTQzYzRiYTM2OTA4NTU3M2QxMjVmZTMxMTk3NmI1NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.GvFXNmEz4iyH_srKc06lMEJCLV0aGcZ8Vye0E9EBByI">
> > 镜像的版本是： image: higress-registry.cn-hangzhou.cr.aliyuncs.com/higress/console:1.3.1
> 
> 忘记输出为 yaml 了。请再执行一次 `kubectl get mcpbridge default -n higress-system -o yaml`

<img width="715" alt="image" src="https://github.com/alibaba/higress/assets/7973318/11a6ff85-f4fe-4dad-bab3-2c7e44ea77ea">

**Comment by 2456868764** [comment]
我在本地安装 consul 1.12.2 版本测试一下， 可以看到服务IP地址列表
<img width="655" alt="截屏2023-12-29 11 01 23" src="https://github.com/alibaba/higress/assets/108045855/78e7fd6b-0b8c-402b-886c-f085c6f684f4">
<img width="865" alt="截屏2023-12-29 11 01 39" src="https://github.com/alibaba/higress/assets/108045855/c52a41dc-cab5-4fd7-bc29-adf4af572fb1">

麻烦查一下 通过 higress controller debug 端口 是否输出IP地址

kubectl -n higress-system port-forward deploy/higress-controller 8888:8888

然后 通过URL 访问 http://127.0.0.1:8888/debug/configz 看输出 consul serviceEntry 是否包含IP地址

![WechatIMG729](https://github.com/alibaba/higress/assets/108045855/bad3b36d-d811-4809-9aa7-71ee6538d286)

**Comment by nlg521** [comment]
<img width="822" alt="image" src="https://github.com/alibaba/higress/assets/7973318/b341b87a-f4d8-4c98-b2c0-160069426812">
看起来也没有这个 ip 列表

**Comment by nlg521** [comment]
[
  {
    "ID": "",
    "Node": "console-0291dac9",
    "Address": "10.1.1.160",
    "Datacenter": "dc-tool",
    "TaggedAddresses": null,
    "NodeMeta": {
      "external-node": "true",
      "external-probe": "true"
    },
    "ServiceKind": "",
    "ServiceID": "1000022",
    "ServiceName": "app1",
    "ServiceTags": [
      "_app=app1",
      "_environment=pro",
      "_metrics_path=/actuator/prometheus"
    ],
    "ServiceAddress": "",
    "ServiceWeights": {
      "Passing": 1,
      "Warning": 1
    },
    "ServiceMeta": {
      
    },
    "ServicePort": 8080,
    "ServiceSocketPath": "",
    "ServiceEnableTagOverride": false,
    "ServiceProxy": {
      "Mode": "",
      "MeshGateway": {
        
      },
      "Expose": {
        
      }
    },
    "ServiceConnect": {
      
    },
    "CreateIndex": 715832,
    "ModifyIndex": 715832
  }
]

通过 http://${ip}/v1/catalog/service/app1 返回的数据如上，不知道是否是解析的问题。

**Comment by nlg521** [comment]
> kubectl get mcpbridge default -n higress-system -o yaml apiVersion: networking.higress.io/v1 kind: McpBridge metadata: creationTimestamp: "2023-12-28T07:44:34Z" generation: 5 name: default namespace: higress-system resourceVersion: "146899868" uid: 46f8a256-f33b-4d93-b695-c9202c79e858 spec: registries:

这个应该就是编辑时不能获取 dc 的原因吧。

**Comment by CH3CHO** [comment]
> 这个应该就是编辑时不能获取 dc 的原因吧。

是的，因为数据里就没有 dc。

**Comment by 2456868764** [comment]
> [ { "ID": "", "Node": "console-0291dac9", "Address": "10.1.1.160", "Datacenter": "dc-tool", "TaggedAddresses": null, "NodeMeta": { "external-node": "true", "external-probe": "true" }, "ServiceKind": "", "ServiceID": "1000022", "ServiceName": "app1", "ServiceTags": [ "_app=app1", "_environment=pro", "_metrics_path=/actuator/prometheus" ], "ServiceAddress": "", "ServiceWeights": { "Passing": 1, "Warning": 1 }, "ServiceMeta": { }, "ServicePort": 8080, "ServiceSocketPath": "", "ServiceEnableTagOverride": false, "ServiceProxy": { "Mode": "", "MeshGateway": {}, "Expose": {} }, "ServiceConnect": {}, "CreateIndex": 715832, "ModifyIndex": 715832 } ]
> 
> 通过 http://${ip}/v1/catalog/service/app1 返回的数据如上，不知道是否是解析的问题。

我看了 consul 数据， 这里 ServiceAddress 是空，服务IP没有注册到 consul， 你排查一下是否 服务没有把IP注册到consul 上，导致不能获取IP地址

**Comment by nlg521** [comment]
> Address

<img width="270" alt="image" src="https://github.com/alibaba/higress/assets/7973318/9b9fa3c4-4dfe-4169-b710-5e8da792a44d">
我们这注册的看起来只有这个字段有数据。

**Comment by 2456868764** [comment]
> > Address
> 
> <img alt="image" width="270" src="https://private-user-images.githubusercontent.com/7973318/293322873-9b9fa3c4-4dfe-4169-b710-5e8da792a44d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4MzM5MDUsIm5iZiI6MTcwMzgzMzYwNSwicGF0aCI6Ii83OTczMzE4LzI5MzMyMjg3My05YjlmYTNjNC00ZGZlLTQxNjktYjcxMC01ZThkYTc5MmE0NGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDIzMTIyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjlUMDcwNjQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzZjZTQzYTg5YjUwYWZlM2ZiYzNhZjNkOTgyNThlNTg5MzEzOGU3YzhlMjBhMjUyMGIyZmExZTA0MzliZTk2MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.z3CDChItUZfE0u5KWBvy4tY7qzG2HrXPwc-_xRwD-wY"> 我们这注册的看起来只有这个字段有数据。

这个Address应该是 consul 自身 Node 节点的IP地址，而不是注册到consul 上服务的IP地址

**Comment by nlg521** [comment]
> > > Address
> > 
> > 
> > <img alt="image" width="270" src="https://private-user-images.githubusercontent.com/7973318/293322873-9b9fa3c4-4dfe-4169-b710-5e8da792a44d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4MzM5MDUsIm5iZiI6MTcwMzgzMzYwNSwicGF0aCI6Ii83OTczMzE4LzI5MzMyMjg3My05YjlmYTNjNC00ZGZlLTQxNjktYjcxMC01ZThkYTc5MmE0NGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDIzMTIyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjlUMDcwNjQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzZjZTQzYTg5YjUwYWZlM2ZiYzNhZjNkOTgyNThlNTg5MzEzOGU3YzhlMjBhMjUyMGIyZmExZTA0MzliZTk2MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.z3CDChItUZfE0u5KWBvy4tY7qzG2HrXPwc-_xRwD-wY"> 我们这注册的看起来只有这个字段有数据。
> 
> 这个Address应该是 consul 自身 Node 节点的IP地址，而不是注册到consul 上服务的IP地址

好的明白了，我们的consul 应该在每个服务节点都有，所以误以为是哪个字段了，谢谢您了。

**Comment by nlg521** [comment]
> ttp://${ip}/v1/catalog/service

您好，这个能复现了吗，我这编辑的时候一直无法显示。
