### ISSUE TITLE
在私有环境Helm部署higress，gateway启动失败

### ISSUE THREAD

**Issue by lcfang** [alibaba/higress#751]
- [x] I have searched the [issues](https://github.com/alibaba/higress/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
使用Helm部署higress，gateway启动失败

### Ⅱ. Describe what happened

higress启动报错：
```
2024-01-04T12:06:54.5114527       warn    ca    ca request failed, starting attempt 3 in 420.340639ms
2024 - 01-04T12:06:54.9321827     warn    ca    ca request failed, starting attempt 4 in 724.700639ms
2024-01-04T12:06:55.657274Z       warn    sds    failed to warm certificate: failed to generate workload certificate: create certificate: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tp 122.244.24.248:15012: connect: connection refused"
[Envoy (Epoch 0)] [2024-01-04 12:07:04.494] [18] [warning] [config] StreamAggregatedResources gRPC config stream closed since 621413990ms ago: 14, connection error: desc = "transport: Error while dialing dial cp 122.244.24.248:15012: connect: connection refused'
[Envoy (Epoch 0)] [2024-01-04 12:07:06.5531 [18] [warning] [config] StreamAggregatedResources gRPC config stream closed since 621416049ms ago: 14, connection error: desc = "transport: Error while dialing dial tp 122.244.24.248:15012: connect: connection refused"
[Envoy (Epoch 0)] [2024-01-04 12:07:35.2251[18] [warning] [config] StreamAggregatedResources gRPC config stream closed since 621444721ms ago: 14, connection error: desc = "transport: Error while dialing dial tcp 122.244.24.248: 15012: connect： connection refused"
```
其中122.244.24.248为controller的IP地址
查看controller中higress-core容器，没有明显报错
查看controller中discovery日志有如下报错：
```
2024-01-02723: 39:42.821058Z       info     rootcertrotator Check and rotate root cert.
2024 - 01-02723:39:42.826907Z      info     rootcertrotator Root cert is not about to expire, skipping root cert rotation.
2024-01-03700: 15:28.186496Z       error    klog       Failed to update lock: Put "https://172.25.0.1:443/api/v1/namespaces/higress-system/configmaps/higress-namespace-controller-election": context deadline exceeded
2024 - 01-03T00: 15:28.186585Z     info     failed to renew lease higress-system/higress-namespace-controller-election: timed out waiting for the condition
2024-01-03T00:15:30.9901617        error    klog       Failed to release lock: Operation cannot be fulfilled on configmaps "higress-namespace-controller-election": the object has been modified; please apply your changes to the latest version and try again
2024-01-03700: 15:30.990253Z       info     leader election lock lost: higress-namespace-controller-election
2024-01-03700:15:30.9902727        error    Leader election cycle 1 lost. Trying again
2024-01-03T00: 15:30.9903237       info     klog        attempting to acquire leader lease higress-system/higress-namespace-controller-election...
2024-01-03T00: 15:43.208729Z       info     successfully acquired lease higress -system/higress-namespace-controller-election
2024-01-03T00: 15:43.208884Z       info     klog        leader election lock obtained: higress-namespace-controller-election
```

### Ⅲ. Describe what you expected to happen
所有组件启动正常

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

helm部署

### Ⅴ. Anything else we need to know?
1. 私有环境使用hostnetwork，没有使用k8s的网络模型
2. 部署时已将discoveryAdress地址换成了controllerIP:15012
3. 部署前为节点打了标签，节点只能部署在指定标签的节点上

### Ⅵ. Environment:

- Higress version:  1.3.2
- OS : SUSE
- Others: 内网离线部署

**Comment by CH3CHO** [comment]
看上去是连不上 K8s 的 API Server。可以从这个角度看一下。

> Failed to update lock: Put "https://172.25.0.1:443/api/v1/namespaces/higress-system/configmaps/higress-namespace-controller-election": context deadline exceeded

**Comment by lcfang** [comment]
> 看上去是连不上 K8s 的 API Server。可以从这个角度看一下。
> 
> > Failed to update lock: Put "https://172.25.0.1:443/api/v1/namespaces/higress-system/configmaps/higress-namespace-controller-election": context deadline exceeded

我们内部的k8s没有用容器网络，我把gateway的网络配置成hostNetwork后，启动成功了，但是有点疑问，为什么只需要把gateway的网络配成hostNetwork，controller不需要管呢？
还有一个问题，前台访问看起来能访问了，但是很多入口报超时，看起来是对controller域名解析的问题？
![6f8be773a272a86b84795091f2c25b1](https://github.com/alibaba/higress/assets/30678878/230de7f9-3604-422f-a07a-7ead9e8116a2)

![4af59d0f07dc0bf49a9fdc2c742a54f](https://github.com/alibaba/higress/assets/30678878/7cbb3958-8e79-4ba8-8ee0-004ed29f11f9)

**Comment by CH3CHO** [comment]
> > 看上去是连不上 K8s 的 API Server。可以从这个角度看一下。
> > > Failed to update lock: Put "https://172.25.0.1:443/api/v1/namespaces/higress-system/configmaps/higress-namespace-controller-election": context deadline exceeded
> 
> 我们内部的k8s没有用容器网络，我把gateway的网络配置成hostNetwork后，启动成功了，但是有点疑问，为什么只需要把gateway的网络配成hostNetwork，controller不需要管呢？ 还有一个问题，前台访问看起来能访问了，但是很多入口报超时，看起来是对controller域名解析的问题？ ![6f8be773a272a86b84795091f2c25b1](https://private-user-images.githubusercontent.com/30678878/294494138-230de7f9-3604-422f-a07a-7ead9e8116a2.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0NTkyNjYsIm5iZiI6MTcwNDQ1ODk2NiwicGF0aCI6Ii8zMDY3ODg3OC8yOTQ0OTQxMzgtMjMwZGU3ZjktMzYwNC00MjJmLWEwN2EtN2VhZDllODExNmEyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDEyNDkyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiMDUzNGFjMTFmNGNjOGNiYzI0ZjRmZGFiMjg0YTJjYjk2MjQwZWZiZjA3YTUzYWE3ZWQzYzBiNTdjZTc5NGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WneHOGHOe9eayCvczzYajTZeQTxVnxufw2C_DE1B4xo)
> 
> ![4af59d0f07dc0bf49a9fdc2c742a54f](https://private-user-images.githubusercontent.com/30678878/294494196-7cbb3958-8e79-4ba8-8ee0-004ed29f11f9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0NTkyNjYsIm5iZiI6MTcwNDQ1ODk2NiwicGF0aCI6Ii8zMDY3ODg3OC8yOTQ0OTQxOTYtN2NiYjM5NTgtOGU3OS00YmE4LThlZTAtMDA0ZWQyOWYxMWY5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDEyNDkyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhZDNkNWMxMjNjNGEzYTM0YzkyZGYwOGJjZGQ1NDI4OGNkMDA4OTNlZDVjYmRlNzc2N2E2OWE5ODBiMWFlMTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Qx-arO1x7JhQ23FbqlJ304-j6ruTgYqIa-bxj_OwZys)

那你把 controller 也改成 hostNetwork 试试看呢？

**Comment by lcfang** [comment]
> 
> 那你把 controller 也改成 hostNetwork 试试看呢？

试了一下，还是不行

**Comment by CH3CHO** [comment]
> 试了一下，还是不行

这部分我不太熟。建议从 K8s 开了 hostNetwork 之后如何使用 FQDN 访问集群内其他服务这个角度查一下。

**Comment by lcfang** [comment]
域名解析的问题通过配置/etc/hosts并挂载进行规避，内部k8s环境网络没有使用网络插件，可以通过安装网络插件解决。
