### ISSUE TITLE
Helm安装方式通过参数控制选择是否安装elb

### ISSUE THREAD

**Issue by hoocoo** [alibaba/higress#763]
## Why do you need it?
 Is your feature request related to a problem? Please describe in details

## How could it be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by CH3CHO** [comment]
应该是说 Service 如果使用 LoadBalancer 类型就会自动配置 ELB 吧？但如果不配置 ELB，你们要如何访问 Gateway 呢？

**Comment by hoocoo** [comment]
> 应该是说 Service 如果使用 LoadBalancer 类型就会自动配置 ELB 吧？但如果不配置 ELB，你们要如何访问 Gateway 呢？

嗯，因为前面有alb，gateway不直接向外面暴露，流量从alb转到service ip就好了

**Comment by CH3CHO** [comment]
> > 应该是说 Service 如果使用 LoadBalancer 类型就会自动配置 ELB 吧？但如果不配置 ELB，你们要如何访问 Gateway 呢？
> 
> 嗯，因为前面有alb，gateway不直接向外面暴露，流量从alb转到service ip就好了

但 Gateway 本身的功能和 ALB 就很像，没必要配两层 7 层 LB 吧。

**Comment by hoocoo** [comment]
> > > 应该是说 Service 如果使用 LoadBalancer 类型就会自动配置 ELB 吧？但如果不配置 ELB，你们要如何访问 Gateway 呢？
> > 
> > 
> > 嗯，因为前面有alb，gateway不直接向外面暴露，流量从alb转到service ip就好了
> 
> 但 Gateway 本身的功能和 ALB 就很像，没必要配两层 7 层 LB 吧。

历史原因alb配了很多waf能力及一些其他功能，还有elb的话会丢一些头信息，所以这层暂时去不掉。

**Comment by CH3CHO** [comment]
Helm 安装的时候加一个参数就行：`--set higress-core.gateway.service.type=ClusterIP`

**Comment by johnlanni** [comment]
> Helm 安装的时候加一个参数就行：`--set higress-core.gateway.service.type=ClusterIP`

是的 用这个方式就可以解决了
