### ISSUE TITLE
helm安装方式， higress-console控制台服务列表没有higress所在命名空间的服务

### ISSUE THREAD

**Issue by 1948486270** [alibaba/higress#790]
想在控制台页面设置路由控制台服务，但是服务列表没有找到控制台服务
![截屏-20240120004733-1422x901](https://github.com/alibaba/higress/assets/40079084/4b7cee05-1b22-423a-afe7-a4ff157e7788)

**Comment by llahu** [comment]
和社区开发者咨询过，当前higress-console不会list出higress所在namespace里的svc。

**Comment by CH3CHO** [comment]
把console暴露到网关上是有安全风险的。

**Comment by 1948486270** [comment]
确实
