### ISSUE TITLE
无法返回自定义HTTP状态码

### ISSUE THREAD

**Issue by linkyaa** [alibaba/higress#819]
### Ⅰ. Issue Description
websocket服务器在客户端升级时返回自定义的HTTP状态码1xxx,经过higress后变为502。

higress 用的是一键部署的默认配置

### Ⅱ. Describe what happened
higress 日志

```json
{
  "response_code":"502",
  "response_flags":"UPE"
}
```

### Ⅲ. Describe what you expected to happen
Higress对自定义的状态码不做处理

### Ⅵ. Environment:

- Higress version:  1.3.2

**Comment by johnlanni** [comment]
这个是不符合RFC规范的，所以产生了UPE错误，Upstream Protocol Error

**Comment by johnlanni** [comment]
这个社区不能支持哈，太hack了

**Comment by YuiStar-Lin** [comment]
如果有和常规状态码语义进行区分需求，有什么好的建议吗

**Comment by johnlanni** [comment]
在websocket协议内部进行封装，修改协议升级的状态码是没办法穿透代理的
