### ISSUE TITLE
自定义应答插件不能正常设置Content-Type

### ISSUE THREAD

**Issue by bwcxyk** [alibaba/higress#832]
使用默认的 Content-Type=application/json 配置，浏览器返回为 content-type: text/plain
![3651fdb39527bbf6163eb453f4fd7baf](https://github.com/alibaba/higress/assets/28802427/bac4037b-3e78-40fc-ac91-3f13198fd575)
![image](https://github.com/alibaba/higress/assets/28802427/16ebead7-1f24-4ded-9f2d-d8ad4c51b0bc)

**Comment by OnlyPiglet** [comment]
want fix this, can I have a try

**Comment by johnlanni** [comment]
@OnlyPiglet Already fixed :)

**Comment by johnlanni** [comment]
@bwcxyk 已经修复并推送了新的插件镜像，可以重启下数据面就能生效
