### ISSUE TITLE
建议公开监控面板的指标采集规则

### ISSUE THREAD

**Issue by listapp99** [alibaba/higress#836]
## Why do you need it?
higress控制台样例的监控面板，运维无法确定采集的哪些指标

## How could it be?
希望公开监控面板的promql语句，比如开放grafana面板下拉菜单的explore，供运维参考

**Comment by CH3CHO** [comment]
后续版本会支持查看监控面板配置

**Comment by CH3CHO** [comment]
v1.4.0 版本将增加相关功能。
