### ISSUE TITLE
支持SSL证书共享

### ISSUE THREAD

**Issue by listapp99** [alibaba/higress#841]
## Why do you need it?
higress支持https访问，ssl证书与Ingress需要在同一命名空间，如果多个命名空间下的Ingress使用相同的ssl证书，Ingress无法跨命名空间引用secret，需要在每个命名空间创建secret，增加了不必要的代码逻辑且浪费资源

## How could it be?
同一份ssl证书，希望所有命名空间共享secret，不用在每个命名空间都创建secret

**Comment by CH3CHO** [comment]
不过 Ingress 并不要求与被访问服务在一个命名空间下吧？

**Comment by johnlanni** [comment]
https://github.com/alibaba/higress/blob/9c112a03db25f33f56dde3bc6019e335629955f1/pkg/ingress/kube/ingressv1/controller.go#L440

如上代码，机制上是可以支持的，这个需求也是合理的，一般ingress可能放在业务ns下给开发管理，secret更希望统一管理在系统ns下给运维统一管理。
Gateway API通过Gateway资源管理secret可以比较好解决这个问题，同时也支持了referenctGrant。
Ingress API要解决这个问题，直接让不同ns里的ingress跨ns使用secret不太合理，有安全隐患。
我们可以基于系统ns下的一份配置，来统一管理不同域名需要用到的证书，虽然底层也是跨ns引用secret，但ingress的创建者无法自己去配置secret，把权限收口在系统ns下。
这个 @2456868764 这边已经在开发能支持自动签发证书的管理工具，可以一并考虑在系统ns下全局配置证书的方式。例如可以对一个域名配置开启自动签发证书，或者对域名直接指定一个secret。

**Comment by daixijun** [comment]
> https://github.com/alibaba/higress/blob/9c112a03db25f33f56dde3bc6019e335629955f1/pkg/ingress/kube/ingressv1/controller.go#L440
> 
> 如上代码，机制上是可以支持的，这个需求也是合理的，一般ingress可能放在业务ns下给开发管理，secret更希望统一管理在系统ns下给运维统一管理。 Gateway API通过Gateway资源管理secret可以比较好解决这个问题，同时也支持了referenctGrant。 Ingress API要解决这个问题，直接让不同ns里的ingress跨ns使用secret不太合理，有安全隐患。 我们可以基于系统ns下的一份配置，来统一管理不同域名需要用到的证书，虽然底层也是跨ns引用secret，但ingress的创建者无法自己去配置secret，把权限收口在系统ns下。 这个 @2456868764 这边已经在开发能支持自动签发证书的管理工具，可以一并考虑在系统ns下全局配置证书的方式。例如可以对一个域名配置开启自动签发证书，或者对域名直接指定一个secret。

同样的需求，希望将 TLS Secret 放在系统NS下， 业务只需要部署 Ingress 去使用即可
