### ISSUE TITLE
无配置插件开启不生效

### ISSUE THREAD

**Issue by zhaojinxin409** [alibaba/higress#849]
### 问题
开启go-wasm无配置插件时，如果不填写YAML配置，则插件不生效。需要填写配置（任意内容都可以）才会生效

### 复现步骤

[参考文档，编写无配置插件](https://higress.io/zh-cn/docs/user/wasm-go#%E6%97%A0%E9%85%8D%E7%BD%AE%E6%8F%92%E4%BB%B6)，并在控制台中添加插件。

为路由开启插件，不写任何配置，插件不生效
![image](https://github.com/alibaba/higress/assets/5874804/b8970949-add3-4a89-88cd-d72da703f39f)

随意写入配置，插件生效
![image](https://github.com/alibaba/higress/assets/5874804/f5306f91-838f-4d1a-a401-347ff5ba878a)

### Ⅵ. Environment:

- Higress version:  1.3.2
- Kubernetes version: v1.22.10-aliyun.1

**Comment by johnlanni** [comment]
没配配置但开启时 执行 kubectl get wasmplugin 看下yaml是什么

**Comment by johnlanni** [comment]
可以先下发个空配置{} 绕过，新版本兼容下这个问题
