### ISSUE TITLE
e2e: add testcases for rate limit annotations

### ISSUE THREAD

**Issue by johnlanni** [alibaba/higress#862]
## Why do you need it?

annotations: 
+ `higress.io/route-limit-rps`
+ `higress.io/route-limit-rpm`
+ `higress.io/route-limit-burst-multiplier`

## How could it be?
see: https://higress.io/zh-cn/docs/user/annotation-use-case#%E5%8D%95%E6%9C%BA%E9%99%90%E6%B5%81

## Other related information
+ https://github.com/alibaba/higress/tree/main/test
+ https://github.com/alibaba/higress/issues/190

**Comment by dongdongh233** [comment]
please assign to me
