### ISSUE TITLE
e2e: add testcases for header control annotations

### ISSUE THREAD

**Issue by johnlanni** [alibaba/higress#863]
## Why do you need it?

annotations: 
+ `higress.io/request-header-control-add`
+ `higress.io/request-header-control-update`
+ `higress.io/request-header-control-remove`
+ `higress.io/response-header-control-add`
+ `higress.io/response-header-control-update`
+ `higress.io/response-header-control-remove`

## How could it be?

see: https://higress.io/zh-cn/docs/user/annotation-use-case#header%E6%8E%A7%E5%88%B6

## Other related information
+ https://github.com/alibaba/higress/tree/main/test
+ https://github.com/alibaba/higress/issues/190

**Comment by robynron** [comment]
plz assign this to me😃
