### ISSUE TITLE
Wasm SDK used in `hgctl plugin init`

### ISSUE THREAD

**Issue by CH3CHO** [alibaba/higress#885]
Currently, when creating a new Wasm plugin project using `hgctl plugin init` command, the new project uses `github.com/tetratelabs/proxy-wasm-go-sdk`. Should we switch to `https://github.com/higress-group/proxy-wasm-go-sdk` here?

https://github.com/alibaba/higress/blob/main/pkg/cmd/hgctl/plugin/init/templates.go#L35
```go
import (
	"github.com/tidwall/gjson"
	"github.com/tetratelabs/proxy-wasm-go-sdk/proxywasm" // <-----
	"github.com/tetratelabs/proxy-wasm-go-sdk/proxywasm/types" // <-----
	"github.com/alibaba/higress/plugins/wasm-go/pkg/wrapper"
)
```

**Comment by johnlanni** [comment]
cc @rinfx
