### ISSUE TITLE
【建议】服务来源配置Nacos等增加通讯检测和手动同步

### ISSUE THREAD

**Issue by huangye123** [alibaba/higress#913]
## Why do you need it?
 Is your feature request related to a problem? Please describe in details
![image](https://github.com/alibaba/higress/assets/28778519/3baf2019-64c4-4327-9fbf-b6f1b25c60b0)

实际配置过程遇到添加完Nacos参数后，服务未同步，经过排查是Nacos参数配置有误，但比较困难发现，

【建议】
1、如果有一个通讯检测功能就比方便。

2、在服务列表中，支持手动点击获取，提示获取失败原因，方便排查。

## How could it be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by CH3CHO** [comment]
因为实际执行服务发现的并不是控制台组件，这样做的话就有两个办法：

1. Console 针对性的对各种服务来源类型进行检测，这个不会太准；
2. Controller 开放一个接口，接受服务来源配置信息进行检测和服务发现，供 Console 调用。

@johnlanni 看一下这个需求呢？

**Comment by johnlanni** [comment]
嗯 可以的，controller的registry暴露统一的ready信息，再通过debug接口让Console查询比较合理，欢迎有兴趣的同学认领

**Comment by johnlanni** [comment]
ready状态统计可以基于：
https://github.com/alibaba/higress/blob/8c817cf80a609481b89aa032be098d3c3c982446/registry/reconcile/reconcile.go#L236

提供debug查询接口可以扩展这里httpMux的handler：

https://github.com/alibaba/higress/blob/8c817cf80a609481b89aa032be098d3c3c982446/pkg/bootstrap/server.go#L392-L402

**Comment by hanxiantao** [comment]
想要尝试下，请帮忙分配下，感谢 @johnlanni

**Comment by hanxiantao** [comment]
这边会新增一个"/debug/registry/watcherStatus"用于查询registryWatcher的状态
除了ready状态统计可以基于：https://github.com/alibaba/higress/blob/f1cadcbd732a749529fa5ad12e0ecc26f0b7aff0/registry/reconcile/reconcile.go#L236
还添加healthy状态
https://github.com/alibaba/higress/blob/f1cadcbd732a749529fa5ad12e0ecc26f0b7aff0/registry/watcher.go#L51
效果如下
<img width="466" alt="image" src="https://github.com/alibaba/higress/assets/45159482/4ef9162c-f4b3-4b6b-a123-086d10645186">
