### ISSUE TITLE
AI 代理 Wasm 插件对接百度文心一言

### ISSUE THREAD

**Issue by CH3CHO** [alibaba/higress#941]

**Comment by hanxiantao** [comment]
申请认领下这个任务，麻烦帮忙分配下 @CH3CHO

**Comment by hanxiantao** [comment]
@CH3CHO 您好，开发过程中有个问题沟通下，百度文心一言不同模型的url是不同的，不是通过requestBody中的model来区分的，如果要进行模型映射的话，需要在OnRequestBody中根据requestBody中的model来生成不同的requestPath，然后调用_ = util.OverwriteRequestPath(requestPath)方法替换请求头中的:path
但是验证的时候，我这边发现OnRequestBody方法中不能再修改请求头了（报错：error status returned by host: bad argument），这种好像只能参考azureServiceUrl这种手工配置地址了，无法进行模型映射
您看下有没有什么其他的建议
[百度文心一言文档](https://console.bce.baidu.com/tools/?_=1716019392341&u=qfdc#/api?product=QIANFAN&project=%E5%8D%83%E5%B8%86%E5%A4%A7%E6%A8%A1%E5%9E%8B%E5%B9%B3%E5%8F%B0&parent=ERNIE%204.0&api=rpc%2F2.0%2Fai_custom%2Fv1%2Fwenxinworkshop%2Fchat%2Fcompletions_pro&method=post)

**Comment by CH3CHO** [comment]
> @CH3CHO 您好，开发过程中有个问题沟通下，百度文心一言不同模型的url是不同的，不是通过requestBody中的model来区分的，如果要进行模型映射的话，需要在OnRequestBody中根据requestBody中的model来生成不同的requestPath，然后调用_ = util.OverwriteRequestPath(requestPath)方法替换请求头中的:path 但是验证的时候，我这边发现OnRequestBody方法中不能再修改请求头了（报错：error status returned by host: bad argument），这种好像只能参考azureServiceUrl这种手工配置地址了，无法进行模型映射 您看下有没有什么其他的建议 [百度文心一言文档](https://console.bce.baidu.com/tools/?_=1716019392341&u=qfdc#/api?product=QIANFAN&project=%E5%8D%83%E5%B8%86%E5%A4%A7%E6%A8%A1%E5%9E%8B%E5%B9%B3%E5%8F%B0&parent=ERNIE%204.0&api=rpc%2F2.0%2Fai_custom%2Fv1%2Fwenxinworkshop%2Fchat%2Fcompletions_pro&method=post)

可以先参考 Azure 的实现。后续会支持在 OnRequestBody 阶段修改 Header，到时候可以再调整。

**Comment by hanxiantao** [comment]
> OnRequestBody



> > @CH3CHO 您好，开发过程中有个问题沟通下，百度文心一言不同模型的url是不同的，不是通过requestBody中的model来区分的，如果要进行模型映射的话，需要在OnRequestBody中根据requestBody中的model来生成不同的requestPath，然后调用_ = util.OverwriteRequestPath(requestPath)方法替换请求头中的:path 但是验证的时候，我这边发现OnRequestBody方法中不能再修改请求头了（报错：error status returned by host: bad argument），这种好像只能参考azureServiceUrl这种手工配置地址了，无法进行模型映射 您看下有没有什么其他的建议 [百度文心一言文档](https://console.bce.baidu.com/tools/?_=1716019392341&u=qfdc#/api?product=QIANFAN&project=%E5%8D%83%E5%B8%86%E5%A4%A7%E6%A8%A1%E5%9E%8B%E5%B9%B3%E5%8F%B0&parent=ERNIE%204.0&api=rpc%2F2.0%2Fai_custom%2Fv1%2Fwenxinworkshop%2Fchat%2Fcompletions_pro&method=post)
> 
> 可以先参考 Azure 的实现。后续会支持在 OnRequestBody 阶段修改 Header，到时候可以再调整。

好的
