### ISSUE TITLE
 AI 代理 Wasm 插件对接腾讯混元大模型

### ISSUE THREAD

**Issue by CH3CHO** [alibaba/higress#944]
https://cloud.tencent.com/document/product/1729

**Comment by xychen5** [comment]
申领这个任务，麻烦帮忙分配下 @CH3CHO

**Comment by xychen5** [comment]
在开的时候遇到一个小问题，混元的api的验证token，需要body和header一起参与计算获得这个token，然后放在header里，在我了解到的目前的proxy-wasm-go-sdk，貌似并未提供这样的策略（也就是headers的处理函数里要获取body的值，但是这不被允许）？@CH3CHO 请问能给一些建议吗？

**Comment by CH3CHO** [comment]
现在是支持在处理 body 的时候修改 header 的。你可以参考一下 qwen 实现中对 streaming 的处理方式。

| |
Kent Dong
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年05月24日 11:45 |
| 收件人 | alibaba/higress ***@***.***> |
| 抄送人 | Kent ***@***.***>,
Mention ***@***.***> |
| 主题 | Re: [alibaba/higress] AI 代理 Wasm 插件对接腾讯混元大模型 (Issue #944) |

***@***.*** 请问能给一些建议吗？

**Comment by xychen5** [comment]
@CH3CHO  hi，我参考了qwen的代码，发现其中forcestreamming参数是写死的true（这导致在onRequestBody并没有实际执行的修改header的代码），我手动改为false，但是发现qwen执行失败，请问您知道是怎么回事吗？

**Comment by CH3CHO** [comment]
> @CH3CHO hi，我参考了qwen的代码，发现其中forcestreamming参数是写死的true（这导致在onRequestBody并没有实际执行的修改header的代码），我手动改为false，但是发现qwen执行失败，请问您知道是怎么回事吗？

你看的代码不是最新的吧。。。

**Comment by xychen5** [comment]
> > @CH3CHO hi，我参考了qwen的代码，发现其中forcestreamming参数是写死的true（这导致在onRequestBody并没有实际执行的修改header的代码），我手动改为false，但是发现qwen执行失败，请问您知道是怎么回事吗？
> 
> 你看的代码不是最新的吧。。。

hi，大佬，我参考了你的建议，然后按照https://higress.io/zh-cn/docs/user/wasm-go这篇文档本地测了一下(调通过月之暗面的代码)，在测试千问的时候，发现OnRequestBody这个函数没被调用啊？大佬能给点关于这种情况的可能性吗？

**Comment by CH3CHO** [comment]
> > > @CH3CHO hi，我参考了qwen的代码，发现其中forcestreamming参数是写死的true（这导致在onRequestBody并没有实际执行的修改header的代码），我手动改为false，但是发现qwen执行失败，请问您知道是怎么回事吗？
> > 
> > 
> > 你看的代码不是最新的吧。。。
> 
> hi，大佬，我参考了你的建议，然后按照[https://higress.io/zh-cn/docs/user/wasm-go这篇文档本地测了一下(调通过月之暗面的代码)，在测试千问的时候，发现OnRequestBody这个函数没被调用啊？大佬能给点关于这种情况的可能性吗？](https://higress.io/zh-cn/docs/user/wasm-go%E8%BF%99%E7%AF%87%E6%96%87%E6%A1%A3%E6%9C%AC%E5%9C%B0%E6%B5%8B%E4%BA%86%E4%B8%80%E4%B8%8B(%E8%B0%83%E9%80%9A%E8%BF%87%E6%9C%88%E4%B9%8B%E6%9A%97%E9%9D%A2%E7%9A%84%E4%BB%A3%E7%A0%81)%EF%BC%8C%E5%9C%A8%E6%B5%8B%E8%AF%95%E5%8D%83%E9%97%AE%E7%9A%84%E6%97%B6%E5%80%99%EF%BC%8C%E5%8F%91%E7%8E%B0OnRequestBody%E8%BF%99%E4%B8%AA%E5%87%BD%E6%95%B0%E6%B2%A1%E8%A2%AB%E8%B0%83%E7%94%A8%E5%95%8A%EF%BC%9F%E5%A4%A7%E4%BD%AC%E8%83%BD%E7%BB%99%E7%82%B9%E5%85%B3%E4%BA%8E%E8%BF%99%E7%A7%8D%E6%83%85%E5%86%B5%E7%9A%84%E5%8F%AF%E8%83%BD%E6%80%A7%E5%90%97%EF%BC%9F)

要不你先提一个 draft PR 我看看？

**Comment by xychen5** [comment]
好的

**Comment by xychen5** [comment]
> > > > @CH3CHO hi，我参考了qwen的代码，发现其中forcestreamming参数是写死的true（这导致在onRequestBody并没有实际执行的修改header的代码），我手动改为false，但是发现qwen执行失败，请问您知道是怎么回事吗？
> > > 
> > > 
> > > 你看的代码不是最新的吧。。。
> > 
> > 
> > hi，大佬，我参考了你的建议，然后按照[https://higress.io/zh-cn/docs/user/wasm-go这篇文档本地测了一下(调通过月之暗面的代码)，在测试千问的时候，发现OnRequestBody这个函数没被调用啊？大佬能给点关于这种情况的可能性吗？](https://higress.io/zh-cn/docs/user/wasm-go%E8%BF%99%E7%AF%87%E6%96%87%E6%A1%A3%E6%9C%AC%E5%9C%B0%E6%B5%8B%E4%BA%86%E4%B8%80%E4%B8%8B(%E8%B0%83%E9%80%9A%E8%BF%87%E6%9C%88%E4%B9%8B%E6%9A%97%E9%9D%A2%E7%9A%84%E4%BB%A3%E7%A0%81)%EF%BC%8C%E5%9C%A8%E6%B5%8B%E8%AF%95%E5%8D%83%E9%97%AE%E7%9A%84%E6%97%B6%E5%80%99%EF%BC%8C%E5%8F%91%E7%8E%B0OnRequestBody%E8%BF%99%E4%B8%AA%E5%87%BD%E6%95%B0%E6%B2%A1%E8%A2%AB%E8%B0%83%E7%94%A8%E5%95%8A%EF%BC%9F%E5%A4%A7%E4%BD%AC%E8%83%BD%E7%BB%99%E7%82%B9%E5%85%B3%E4%BA%8E%E8%BF%99%E7%A7%8D%E6%83%85%E5%86%B5%E7%9A%84%E5%8F%AF%E8%83%BD%E6%80%A7%E5%90%97%EF%BC%9F)
> 
> 要不你先提一个 draft PR 我看看？

等等，大佬，那个draftPR中，是要提供我写的未完成的hunyuan的代码？还是本地测试千问的配置文件呢？

**Comment by xychen5** [comment]
> > > > @CH3CHO hi，我参考了qwen的代码，发现其中forcestreamming参数是写死的true（这导致在onRequestBody并没有实际执行的修改header的代码），我手动改为false，但是发现qwen执行失败，请问您知道是怎么回事吗？
> > > 
> > > 
> > > 你看的代码不是最新的吧。。。
> > 
> > 
> > hi，大佬，我参考了你的建议，然后按照[https://higress.io/zh-cn/docs/user/wasm-go这篇文档本地测了一下(调通过月之暗面的代码)，在测试千问的时候，发现OnRequestBody这个函数没被调用啊？大佬能给点关于这种情况的可能性吗？](https://higress.io/zh-cn/docs/user/wasm-go%E8%BF%99%E7%AF%87%E6%96%87%E6%A1%A3%E6%9C%AC%E5%9C%B0%E6%B5%8B%E4%BA%86%E4%B8%80%E4%B8%8B(%E8%B0%83%E9%80%9A%E8%BF%87%E6%9C%88%E4%B9%8B%E6%9A%97%E9%9D%A2%E7%9A%84%E4%BB%A3%E7%A0%81)%EF%BC%8C%E5%9C%A8%E6%B5%8B%E8%AF%95%E5%8D%83%E9%97%AE%E7%9A%84%E6%97%B6%E5%80%99%EF%BC%8C%E5%8F%91%E7%8E%B0OnRequestBody%E8%BF%99%E4%B8%AA%E5%87%BD%E6%95%B0%E6%B2%A1%E8%A2%AB%E8%B0%83%E7%94%A8%E5%95%8A%EF%BC%9F%E5%A4%A7%E4%BD%AC%E8%83%BD%E7%BB%99%E7%82%B9%E5%85%B3%E4%BA%8E%E8%BF%99%E7%A7%8D%E6%83%85%E5%86%B5%E7%9A%84%E5%8F%AF%E8%83%BD%E6%80%A7%E5%90%97%EF%BC%9F)
> 
> 要不你先提一个 draft PR 我看看？
关于本地测试的pr如下：
https://github.com/alibaba/higress/pull/1018
