### ISSUE TITLE
 AI 代理 Wasm 插件对接 Google Gemini/Gemini Flash

### ISSUE THREAD

**Issue by CH3CHO** [alibaba/higress#947]
https://developers.generativeai.google/

**Comment by UniDra001** [comment]
我想尝试下这个issue~

**Comment by UniDra001** [comment]
您好，我在开发的时候遇到一个问题，gemini的模型选择和api_key都是放在请求url中的，但是在wasm代理的时候只能在ProcessRequestBody获取body绑定的model类型，这样的话就没法修改请求url，请问有解决方法吗？ [gemini API](https://ai.google.dev/gemini-api/docs/get-started/tutorial?lang=rest&hl=zh-cn)

**Comment by CH3CHO** [comment]
> 您好，我在开发的时候遇到一个问题，gemini的模型选择和api_key都是放在请求url中的，但是在wasm代理的时候只能在ProcessRequestBody获取body绑定的model类型，这样的话就没法修改请求url，请问有解决方法吗？ [gemini API](https://ai.google.dev/gemini-api/docs/get-started/tutorial?lang=rest&hl=zh-cn)

1.4.0 里是可以在 ProcessRequestBody 里修改 header 的。可以参考一下 qwen 的实现和这个 PR https://github.com/alibaba/higress/pull/1005 。

**Comment by UniDra001** [comment]
好的，另外还想问下，开发wsam插件有本地调试的方案吗？

**Comment by UniDra001** [comment]
嗯嗯这个我看过了，我想问的是支持单步调试吗？

**Comment by CH3CHO** [comment]
> 嗯嗯这个我看过了，我想问的是支持单步调试吗？

这个应该还不支持的。

**Comment by UniDra001** [comment]
请问有什么办法能看到网关发送给LLM服务商的请求吗？我这边显示请求格式错误，但是不好调试排错

**Comment by CH3CHO** [comment]
> 请问有什么办法能看到网关发送给LLM服务商的请求吗？我这边显示请求格式错误，但是不好调试排错

打日志就行了，在gateway容器里看

**Comment by johnlanni** [comment]
@UniDra001 这个插件有进展吗，没有进展的话，会再分配给其他同学

**Comment by UniDra001** [comment]
不好意思，暂时没有进展，麻烦分给其他同学吧

**Comment by hanxiantao** [comment]
我这边来开发下，麻烦帮忙分配下 @johnlanni

**Comment by hanxiantao** [comment]
gemini对接过程中遇到两个问题沟通下：

1）目前支持原有协议时还是通过/v1/chat/completions路径请求，从requestBody中获取模型名称和是否流式请求，但gemini的请求体中不包含这两个字段，是通过请求路径区分模型和是否流式请求
gemini原生协议requestBody对应结构体：
<img width="838" alt="image" src="https://github.com/user-attachments/assets/6566de63-56f9-4d92-a020-e008ee7947da">
请求路径拼接逻辑：
<img width="989" alt="image" src="https://github.com/user-attachments/assets/ec4b9ac7-6048-4aa6-80ea-0314e13fca92">
这里实现gemini原有协议对接的时候，会在gemini原生协议requestBody中加上model和stream来支持

2）代理gemini流式响应返回的好像没有进入OnStreamingResponseBody阶段处理，我试了下gemini的流式接口并没有返回类似流式的chunk响应头，而是采用了sse协议，这种情况会进入OnStreamingResponseBody阶段处理吗？（这个我也会再详细定位下，先确认下逻辑）
<img width="1325" alt="image" src="https://github.com/user-attachments/assets/0013a539-d1d5-4d1d-b3a8-a755d4354749">

**Comment by hanxiantao** [comment]
> @hanxiantao 插件sdk里的chunk参数并不表示chunked传输，就是可以处理SSE协议的

好的，我再调试下，我也理解应该是可以处理SSE协议的
