### ISSUE TITLE
 AI 代理 Wasm 插件对接字节豆包大模型

### ISSUE THREAD

**Issue by CH3CHO** [alibaba/higress#954]
https://www.volcengine.com/docs/82379/1263512

**Comment by zxxsong** [comment]
申请领取这个任务，麻烦帮忙分配下。

**Comment by johnlanni** [comment]
@zxxsong 这块有进展吗，没有的话，会重新提供其他人认领

**Comment by n3A87** [comment]
我想尝试下这个issue，麻烦分配一下~

**Comment by johnlanni** [comment]
@n3A87 这个插件有进展吗

**Comment by n3A87** [comment]
@johnlanni 开始在做了，但是最近有点忙，再留给我一些时间，我会尽快完成~😊

**Comment by johnlanni** [comment]
@n3A87 时间比较久了 有进展吗

**Comment by johnlanni** [comment]
这个报错看上去是tinygo的问题，在windows你可以用mingw等类UNIX环境，然后用这里介绍的 make 命令来编译：https://github.com/alibaba/higress/tree/main/plugins/wasm-go

**Comment by johnlanni** [comment]
https://github.com/alibaba/higress/pull/1337

@n3A87 有其他同学提交了 PR 解决这个 issue 了
