### ISSUE TITLE
 AI 代理 Wasm 插件对接 Ollama

### ISSUE THREAD

**Issue by CH3CHO** [alibaba/higress#956]
https://github.com/ollama/ollama

**Comment by Claire-w** [comment]
申请认领这个任务，麻烦帮忙分配下 @CH3CHO

**Comment by Claire-w** [comment]
@CH3CHO 您好，Ollama似乎只能在本地运行然后通过localhost调用API？我目前已开发并测试在本地部署模型的版本，但不太确定是不是只能本地运行，想和您确认一下

**Comment by CH3CHO** [comment]
> @CH3CHO 您好，Ollama似乎只能在本地运行然后通过localhost调用API？我目前已开发并测试在本地部署模型的版本，但不太确定是不是只能本地运行，想和您确认一下

试试这个呢？https://github.com/ollama/ollama/issues/1179

**Comment by CH3CHO** [comment]
经测试，现在的对接实现存在一定问题，无法正常工作。希望社区感兴趣的同学参与修正。

**Comment by Claire-w** [comment]
> 经测试，现在的对接实现存在一定问题，无法正常工作。希望社区感兴趣的同学参与修正。

您好，Ollama这边没有一个集中的服务器，它是需要在本地下载运行Ollma服务器(https://github.com/ollama/ollama)，然后修改ai-proxy配置文件中的ollamaServerHost和ollamaServerPort为服务运行对应的IP地址和端口号，不知道是否是这里导致的问题

**Comment by CH3CHO** [comment]
> 您好，Ollama这边没有一个集中的服务器，它是需要在本地下载运行Ollma服务器

经过再次验证，是我之前测试工艺的问题。现在插件可以正常工作。请忽略。抱歉。
