### ISSUE TITLE
 AI 代理 Wasm 插件对接 Coze

### ISSUE THREAD

**Issue by CH3CHO** [alibaba/higress#959]
https://www.coze.com/

**Comment by sosyz** [comment]
可以分配给我吗？我想试试

**Comment by sosyz** [comment]
@CH3CHO Hi~
我在开发过程中遇到了一些问题，我替换请求地址和内容了但是返回404
<img width="1312" alt="image" src="https://github.com/user-attachments/assets/be538526-cf73-4ce9-9ba4-d37f595c28b0">
我尝试本地起了个http server打印请求但没收到这个请求
代码地址：https://github.com/sosyz/higress/blob/2981e1a4404b9324806b51cddc807b0bb1996d46/plugins/wasm-go/extensions/ai-proxy/provider/coze.go#L416
我该怎么处理呢，请求协助🙏（envoy中有临时key可以测试

**Comment by sosyz** [comment]
编译参考的 https://github.com/alibaba/higress/pull/1005

**Comment by CH3CHO** [comment]
> @CH3CHO Hi~ 我在开发过程中遇到了一些问题，我替换请求地址和内容了但是返回404 <img alt="image" width="1312" src="https://private-user-images.githubusercontent.com/30596875/362524099-be538526-cf73-4ce9-9ba4-d37f595c28b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MDM2MDUsIm5iZiI6MTcyNDkwMzMwNSwicGF0aCI6Ii8zMDU5Njg3NS8zNjI1MjQwOTktYmU1Mzg1MjYtY2Y3My00Y2U5LTliYTQtZDM3ZjU5NWMyOGIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDAzNDgyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5NjRhYjYwNmE4OTIxN2VhYjNmYjA1MjE3MWQxZjU1NWNjZjQ4MWNiZGEyYjgwMzEwYTYzNzE1ZjI3YTM0MmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yaKMXWnNJapBeDGuN5NFxSaXGf5gzpTqFQHdljEdS2w"> 我尝试本地起了个http server打印请求但没收到这个请求 代码地址：https://github.com/sosyz/higress/blob/2981e1a4404b9324806b51cddc807b0bb1996d46/plugins/wasm-go/extensions/ai-proxy/provider/coze.go#L416 我该怎么处理呢，请求协助🙏（envoy中有临时key可以测试

这里的问题是 Coze 的 API 地址是这个吗？

**Comment by sosyz** [comment]
> > @CH3CHO Hi~ 我在开发过程中遇到了一些问题，我替换请求地址和内容了但是返回404 <img alt="image" width="1312" src="https://private-user-images.githubusercontent.com/30596875/362524099-be538526-cf73-4ce9-9ba4-d37f595c28b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MDM2MDUsIm5iZiI6MTcyNDkwMzMwNSwicGF0aCI6Ii8zMDU5Njg3NS8zNjI1MjQwOTktYmU1Mzg1MjYtY2Y3My00Y2U5LTliYTQtZDM3ZjU5NWMyOGIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDAzNDgyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5NjRhYjYwNmE4OTIxN2VhYjNmYjA1MjE3MWQxZjU1NWNjZjQ4MWNiZGEyYjgwMzEwYTYzNzE1ZjI3YTM0MmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yaKMXWnNJapBeDGuN5NFxSaXGf5gzpTqFQHdljEdS2w"> 我尝试本地起了个http server打印请求但没收到这个请求 代码地址：https://github.com/sosyz/higress/blob/2981e1a4404b9324806b51cddc807b0bb1996d46/plugins/wasm-go/extensions/ai-proxy/provider/coze.go#L416 我该怎么处理呢，请求协助🙏（envoy中有临时key可以测试
> 
> 这里的问题是 Coze 的 API 地址是这个吗？

![image](https://github.com/user-attachments/assets/278eaf8d-d11a-4ef4-ae68-4c0af80bb338)
通过curl调用是可以的

**Comment by CH3CHO** [comment]
> 通过curl调用是可以的

你是本地走 envoy 配置对吗？upstream cluster 配的对吗？

**Comment by sosyz** [comment]
> 你是本地走 envoy 配置对吗？upstream cluster 配的对吗？

Get！我改了下upstream现在是200了，还有想问一下因为 coze 的 api 需要轮训去查询消息的生成状态，这个过程要加一个`time.Sleep(1 * time.Second)` 限制下查询请求，但我加了以后会报错 `wasi_snapshot_preview1.poll_oneoff` ，这个怎么解决呢

**Comment by johnlanni** [comment]
https://www.coze.cn/docs/developer_guides/chat_v3#2824d907
@sosyz 可以先实现流式的即可

**Comment by johnlanni** [comment]
实际上非流式的，也可以基于这个流式协议实现

**Comment by sosyz** [comment]
> 实际上非流式的，也可以基于这个流式协议实现

@johnlanni 明白，这也是个好办法！我修改一下实现

**Comment by johnlanni** [comment]
implemented by #1387
