### ISSUE TITLE
 AI 代理 Wasm 插件对接 DeepL

### ISSUE THREAD

**Issue by CH3CHO** [alibaba/higress#963]
https://www.deepl.com/

**Comment by urlyy** [comment]
deepl有文本翻译、文档翻译、术语库的上传与管理、可使用的语言列表这几个api。这个issue主要是对接哪些？是只需要对接翻译功能吗？
![image](https://github.com/user-attachments/assets/04f9e2e4-17e0-4431-9383-d39365044aa6)

**Comment by CH3CHO** [comment]
> deepl有文本翻译、文档翻译、术语库的上传与管理、可使用的语言列表这几个api。这个issue主要是对接哪些？是只需要对接翻译功能吗？

对接翻译功能就可以。因为本身现在提供的就是OpenAI ChatCompletion接口。

**Comment by urlyy** [comment]
好的，请分配给我

**Comment by johnlanni** [comment]
https://github.com/songquanpeng/one-api/blob/main/relay/adaptor/deepl/main.go
@urlyy 可以参考下
