### ISSUE TITLE
Kubernetes 在 低版本内核中，Gateway 创建报错

### ISSUE THREAD

**Issue by iutx** [alibaba/higress#97]
- [ ] I have searched the [issues](https://github.com/alibaba/higress/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

gateway 创建报错。

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```console
helm upgrade --install higress -n higress-system  oci://higress-registry.cn-hangzhou.cr.aliyuncs.com/charts/higress
```
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/31346321/205502041-20fb420e-7d77-493f-8ed6-30b7f285fe41.png">

### Ⅲ. Describe what you expected to happen

这种情况建议通过增加 QA 来引导用户自己配置 securityContext 以及 containerSecurityContext

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
5. xxx
6. xxx

### Ⅵ. Environment:
1. Kubernetes 1.23
2. OS: CentOS7
3. Linux Kernel: 3.10

**Comment by johnlanni** [comment]
@iutx 可以帮忙更新下官方文档的部署说明吗，关于适配不同内核需要做的改动，包括这个 hostnetwork 的配置说明
在这里：https://github.com/higress-group/higress-group.github.io/blob/master/docs/zh-cn/ops/deploy-by-helm.md

**Comment by iutx** [comment]
> @iutx 可以帮忙更新下官方文档的部署说明吗，关于适配不同内核需要做的改动，包括这个 hostnetwork 的配置说明 在这里：https://github.com/higress-group/higress-group.github.io/blob/master/docs/zh-cn/ops/deploy-by-helm.md

好的，会尝试几个内核版本再去测试下。
